import { Router, Request, Response } from 'express';
const router = Router();
const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string' }, success: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Website Change Monitor API', version: '1.0.0', description: 'Monitor web pages for content changes, detect diffs, and configure alert rules for competitive intelligence, compliance, and automated research workflows.', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 200, requests_per_month: 6000 }, pay_per_call: { check: '$0.002', diff: '$0.004', 'alert-rule': '$0.003', 'execution-gate': '$0.001', monitor: '$0.006' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/website-change-monitor' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/check': { post: { operationId: 'check', summary: 'Check URL for content changes — hash, status, change flag', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['url'], properties: { url: { type: 'string' } } } } } }, responses: { '200': { description: 'Check result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, url: { type: 'string' }, check: { type: 'object', properties: { has_changed: { type: 'boolean' }, last_checked: { type: 'string' }, content_hash: { type: 'string' }, status_code: { type: 'number' } } }, change_summary: { type: 'string' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing url' }, '500': { description: 'Failed' } } } },
      '/diff': { post: { operationId: 'diff', summary: 'Content diff since a timestamp — added, removed, modified sections', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['url', 'since'], properties: { url: { type: 'string' }, since: { type: 'string', description: 'ISO 8601 date' } } } } } }, responses: { '200': { description: 'Content diff', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, url: { type: 'string' }, since: { type: 'string' }, diff: { type: 'object', properties: { added_content: { type: 'array', items: { type: 'string' } }, removed_content: { type: 'array', items: { type: 'string' } }, change_percentage: { type: 'number' }, severity: { type: 'string', enum: ['minor', 'moderate', 'major', 'critical'] } } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing url or since' }, '500': { description: 'Failed' } } } },
      '/alert-rule': { post: { operationId: 'alertRule', summary: 'Configure keyword alert rule for a URL', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['url', 'keywords'], properties: { url: { type: 'string' }, keywords: { type: 'array', items: { type: 'string' } } } } } } }, responses: { '200': { description: 'Alert rule configured', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, url: { type: 'string' }, alert_rule: { type: 'object', properties: { rule_id: { type: 'string' }, keywords: { type: 'array', items: { type: 'string' } }, status: { type: 'string' } } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing url or keywords' }, '500': { description: 'Failed' } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['url'], properties: { url: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, next_api: { type: 'string' }, blocking_flags: actions, confidence_per_section: confidence, privacy } } } } } } } },
      '/monitor': { post: { operationId: 'monitor', summary: 'ONE-CALL: full change monitoring — state + changes + alerts + health', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['url'], properties: { url: { type: 'string' } } } } } }, responses: { '200': { description: 'Full monitoring intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, url: { type: 'string' }, current_state: { type: 'object' }, recent_changes: { type: 'array', items: { type: 'object' } }, alert_rules: { type: 'array', items: { type: 'object' } }, monitor_health: { type: 'object' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing url' }, '500': { description: 'Failed' } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
