import { Router, Request, Response } from 'express';
const router = Router();

const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string', format: 'date-time' }, success: { type: 'boolean' } };
const provenance = { type: 'object', properties: { provider: { type: 'string' }, retrieved_at: { type: 'string', format: 'date-time' }, freshness_score: { type: 'number', minimum: 0, maximum: 1 } } };
const chainFields = { source_provenance: provenance, cache_ttl_seconds: { type: 'integer' }, cache_recommended: { type: 'boolean' }, recommended_next_api: { type: 'string' }, recommended_next_endpoint: { type: 'string' }, automation_safe: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Smart Contract Decoder API', version: '1.0.0', description: 'Decode contract ABIs, analyze logic, run quick security audits and list public functions for DeFi and Web3 agent workflows', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 200 }, pay_per_call: { decode: '$0.004', analyze: '$0.005', audit: '$0.006', 'execution-gate': '$0.001', 'contract-intelligence': '$0.012', functions: '$0.003', batch: '$0.025' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/smart-contract-decoder' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/decode': { post: { operationId: 'decodeContract', summary: 'Decode contract ABI and functions', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { address: { type: 'string' }, chain: { type: 'string' }, abi: { type: 'array' } } } } } }, responses: { '200': { description: 'Decoded ABI', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, contract_name: { type: 'string' }, functions: { type: 'array', items: { type: 'object' } }, is_proxy: { type: 'boolean' }, ...chainFields, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } } } } },
      '/analyze': { post: { operationId: 'analyzeContract', summary: 'Analyze contract logic and mechanisms', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['address'], properties: { address: { type: 'string' }, chain: { type: 'string' } } } } } }, responses: { '200': { description: 'Contract analysis', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, contract_type: { type: 'string' }, purpose: { type: 'string' }, admin_controls: { type: 'array', items: { type: 'string' } }, upgradability: { type: 'string' }, ...chainFields, privacy } } } } } } } },
      '/audit': { post: { operationId: 'auditContract', summary: 'Quick security audit for vulnerabilities', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['address'], properties: { address: { type: 'string' }, chain: { type: 'string' } } } } } }, responses: { '200': { description: 'Security audit', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, risk_score: { type: 'integer' }, is_verified: { type: 'boolean' }, vulnerabilities: { type: 'array', items: { type: 'object' } }, ...chainFields, privacy } } } } } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['address'], properties: { address: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, ...chainFields, privacy } } } } } } } },
      '/contract-intelligence': { post: { operationId: 'contractIntelligence', summary: 'ONE-CALL: decode + analyze + audit + interaction safety', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['address'], properties: { address: { type: 'string' }, chain: { type: 'string' } } } } } }, responses: { '200': { description: 'Full contract intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, contract_type: { type: 'string' }, risk_level: { type: 'string' }, safe_to_interact: { type: 'boolean' }, interaction_warnings: { type: 'array', items: { type: 'string' } }, ...chainFields, confidence_per_section: confidence, privacy } } } } } } } },
      '/functions': { post: { operationId: 'listFunctions', summary: 'List public contract functions', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['address'], properties: { address: { type: 'string' }, chain: { type: 'string' }, visibility: { type: 'string' } } } } } }, responses: { '200': { description: 'Function list', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, function_count: { type: 'integer' }, functions: { type: 'array', items: { type: 'object' } }, admin_functions: { type: 'array', items: { type: 'string' } }, ...chainFields, privacy } } } } } } } },
      '/batch': { post: { operationId: 'batchContracts', summary: 'Batch overview up to 5 contracts', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['contracts'], properties: { contracts: { type: 'array', items: { type: 'object' }, maxItems: 5 } } } } } }, responses: { '200': { description: 'Batch results', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, batch_count: { type: 'integer' }, results: { type: 'array', items: { type: 'object' } }, ...chainFields } } } } } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
