import { Router, Request, Response } from 'express';
export const openapiRouter = Router();
openapiRouter.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: {
      title: 'Image to Content API',
      version: '1.0.0',
      description: 'Convert images to structured content using AI vision — captions, tags, metadata, OCR and face analysis.',
      'x-agent-callable': true,
      'x-mcp-compatible': true,
      'x-pricing': { '/analyze': 0.005, '/batch': 0.015, 
      '/extract-document': { post: { operationId: 'extractDocument', summary: 'Extract structured content from document images including tables, forms, and layout analysis', 'x-agent-callable': true,
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['image'], properties: {
          image: { type: 'string', description: 'Base64-encoded image or URL' },
          image_format: { type: 'string', enum: ['jpeg', 'png', 'webp', 'pdf'] },
          extract_tables: { type: 'boolean', default: true },
          extract_forms: { type: 'boolean', default: true },
          extract_headings: { type: 'boolean', default: true },
          language: { type: 'string', default: 'en' },
        }}}}},
        responses: { '200': { description: 'Structured document extraction', content: { 'application/json': { schema: { type: 'object', required: ['trace_id', 'status', 'document_type'], properties: {
          trace_id: { type: 'string' },
          status: { type: 'string', enum: ['success', 'error'] },
          document_type: { type: 'string', enum: ['invoice','form','report','article','table','letter','receipt','contract','other'] },
          title: { type: 'string', nullable: true },
          language: { type: 'string' },
          layout: { type: 'object', properties: { sections: { type: 'array', items: { type: 'object', properties: { heading: { type: 'string', nullable: true }, content: { type: 'string' }, position: { type: 'string', enum: ['top','middle','bottom'] } } } }, has_tables: { type: 'boolean' }, has_forms: { type: 'boolean' }, column_count: { type: 'integer' } } },
          tables: { type: 'array', items: { type: 'object', properties: { headers: { type: 'array', items: { type: 'string' } }, rows: { type: 'array', items: { type: 'array', items: { type: 'string' } } }, caption: { type: 'string', nullable: true } } } },
          form_fields: { type: 'array', items: { type: 'object', properties: { label: { type: 'string' }, value: { type: 'string', nullable: true }, field_type: { type: 'string', enum: ['text','checkbox','signature','date'] } } } },
          key_value_pairs: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, value: { type: 'string' } } } },
          full_text: { type: 'string' },
          summary: { type: 'string' },
          confidence: { type: 'number', minimum: 0, maximum: 1 },
          recommended_actions_priority_order: { type: 'array', items: { type: 'string' } },
          chain_to: { type: 'array', items: { type: 'string' } },
          privacy: { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } },
          latency_ms: { type: 'number' },
        }}}}}}}},
      '/entity-link': { post: { operationId: 'entityLink', summary: 'Link extracted entities to canonical concepts and knowledge base entries', 'x-agent-callable': true,
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['entities'], properties: {
          entities: { type: 'array', items: { type: 'string' }, minItems: 1, maxItems: 50, description: 'List of entity strings to link' },
          context: { type: 'string', description: 'Optional context for disambiguation' },
          domain: { type: 'string', description: 'Domain hint e.g. finance, medical, legal' },
        }}}}},
        responses: { '200': { description: 'Linked entities', content: { 'application/json': { schema: { type: 'object', required: ['trace_id', 'linked_entities'], properties: {
          trace_id: { type: 'string' },
          status: { type: 'string', enum: ['success', 'error'] },
          linked_entities: { type: 'array', items: { type: 'object', properties: {
            entity: { type: 'string' }, type: { type: 'string', enum: ['person','org','location','product','concept','event','date','currency','other'] },
            canonical_name: { type: 'string' }, description: { type: 'string' },
            confidence: { type: 'number', minimum: 0, maximum: 1 },
            related_concepts: { type: 'array', items: { type: 'string' } },
            domain_relevance: { type: 'string', enum: ['high','medium','low'] },
          }}},
          entity_count: { type: 'integer' },
          high_confidence_count: { type: 'integer' },
          entity_graph_summary: { type: 'string' },
          recommended_actions_priority_order: { type: 'array', items: { type: 'string' } },
          chain_to: { type: 'array', items: { type: 'string' } },
          privacy: { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } },
          latency_ms: { type: 'number' },
        }}}}}}}},
      '/compare': { post: { operationId: 'compareImages', summary: 'Cross-image comparison for visual consistency, style matching, and ranking', 'x-agent-callable': true,
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['images'], properties: {
          images: { type: 'array', minItems: 2, maxItems: 5, items: { type: 'object', required: ['image'], properties: {
            image: { type: 'string', description: 'Base64 or URL' },
            image_format: { type: 'string', enum: ['jpeg','png','webp'] },
            label: { type: 'string', description: 'Optional label for this image' },
          }}},
          comparison_focus: { type: 'string', description: 'What to focus comparison on e.g. style, quality, content' },
          language: { type: 'string', default: 'en' },
        }}}}},
        responses: { '200': { description: 'Image comparison result', content: { 'application/json': { schema: { type: 'object', required: ['trace_id', 'comparison_summary'], properties: {
          trace_id: { type: 'string' },
          status: { type: 'string', enum: ['success', 'error'] },
          image_count: { type: 'integer' },
          comparison_focus: { type: 'string' },
          comparison_summary: { type: 'string' },
          similarities: { type: 'array', items: { type: 'string' } },
          differences: { type: 'array', items: { type: 'object', properties: { aspect: { type: 'string' }, description: { type: 'string' }, significance: { type: 'string', enum: ['high','medium','low'] } } } },
          ranking: { type: 'array', items: { type: 'object', properties: { image_index: { type: 'integer' }, label: { type: 'string' }, rank: { type: 'integer' }, reason: { type: 'string' } } } },
          best_for: { type: 'object', properties: { purpose: { type: 'string' }, image_index: { type: 'integer' }, reason: { type: 'string' } } },
          visual_consistency_score: { type: 'number', minimum: 0, maximum: 1 },
          style_match_score: { type: 'number', minimum: 0, maximum: 1 },
          confidence: { type: 'number', minimum: 0, maximum: 1 },
          recommended_actions_priority_order: { type: 'array', items: { type: 'string' } },
          chain_to: { type: 'array', items: { type: 'string' } },
          privacy: { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } },
          latency_ms: { type: 'number' },
        }}}}}}}},
      '/jobs/{jobId}': 0.0005 },
      privacy: { data_stored: false, retention: 'none', note: 'Images processed in memory only, not stored' },
      'x-execution-gate-required': true,
      'x-paper-mode-recommended': false,
    },
    servers: [{ url: 'https://orbis-apis.onrender.com/image-to-content' }],
    security: [{ ApiKeyAuth: [] }],
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
    paths: {
      '/': { get: { summary: 'API discovery', operationId: 'discovery', 'x-agent-callable': true,
      responses: { '200': { description: 'API info', content: { 'application/json': { schema: { type: 'object', properties: {
        title: { type: 'string' }, version: { type: 'string' }, description: { type: 'string' },
        status: { type: 'string', enum: ['ok'] },
        privacy: { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } },
        endpoints: { type: 'array', items: { type: 'object', properties: { path: { type: 'string' }, method: { type: 'string' }, price_usdc: { type: 'number' }, description: { type: 'string' } } } },
      } } } } } } } },
      '/analyze': { post: { operationId: 'analyzeImage', summary: 'Analyze an image and extract structured content', 'x-agent-callable': true, 'x-human-approval-required': true,
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['image'], properties: {
          image: { type: 'string', description: 'Base64-encoded image string' },
          image_format: { type: 'string', enum: ['jpeg', 'png', 'gif', 'webp'], description: 'Image format' },
          modules: { type: 'array', items: { type: 'string', enum: ['caption', 'summary', 'tags', 'metadata', 'ocr', 'faces'] }, default: ['caption', 'summary', 'tags', 'metadata'] },
          language: { type: 'string', default: 'en', description: 'Output language code' },
          max_tags: { type: 'integer', minimum: 1, maximum: 50, default: 10 },
          caption_style: { type: 'string', enum: ['brief', 'detailed', 'seo'], default: 'detailed' },
          async: { type: 'boolean', default: false },
        }}}}},
        responses: { '200': { description: 'Structured image content', content: { 'application/json': { schema: { type: 'object', properties: {
          caption: { type: 'string', description: 'AI-generated image caption' },
          summary: { type: 'string', description: 'Detailed image description' },
          tags: { type: 'array', items: { type: 'string' }, description: 'Extracted tags' },
          metadata: { type: 'object', properties: {
            width: { type: 'integer' }, height: { type: 'integer' },
            format: { type: 'string' }, file_size_bytes: { type: 'integer' },
            color_palette: { type: 'array', items: { type: 'string' } },
          }},
          ocr: { type: 'object', properties: { text: { type: 'string' }, confidence: { type: 'number', minimum: 0, maximum: 1 }, language_detected: { type: 'string' } } },
          faces: { type: 'array', items: { type: 'object', properties: {
            emotion: { type: 'string' }, age_range: { type: 'string' },
            profile_score: { type: 'integer', minimum: 0, maximum: 100 },
            improvement_suggestions: { type: 'array', items: { type: 'string' } },
            safety_note: { type: 'string', description: 'Face detection is used for aesthetic profile scoring only. This API does not identify individuals, verify identity, infer protected characteristics, or perform biometric recognition of any kind.' },
          }}},
          confidence_per_section: { type: 'object', properties: {
            caption: { type: 'number' }, tags: { type: 'number' }, ocr: { type: 'number' }, faces: { type: 'number' },
          }},
          recommended_actions_priority_order: { type: 'array', items: { type: 'string' } },
          chain_to: { type: 'array', items: { type: 'string' } },
          privacy: { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } },
        }}}}}}}},
      '/batch': { post: { operationId: 'batchAnalyze', summary: 'Batch analyze up to 20 images', 'x-agent-callable': true,
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['images'], properties: {
          images: { type: 'array', minItems: 1, maxItems: 20, items: { type: 'object', required: ['image'], properties: {
            image: { type: 'string' }, image_format: { type: 'string' }, modules: { type: 'array', items: { type: 'string' } },
          }}},
        }}}}},
        responses: { '200': { description: 'Batch results', content: { 'application/json': { schema: { type: 'object', properties: {
          batch_id: { type: 'string' },
          total: { type: 'integer' },
          succeeded: { type: 'integer' },
          failed: { type: 'integer' },
          results: { type: 'array', items: { type: 'object', properties: { index: { type: 'integer' }, success: { type: 'boolean' }, caption: { type: 'string' }, tags: { type: 'array', items: { type: 'string' } }, error: { type: 'string', nullable: true } } } },
          latency_ms: { type: 'number' },
          recommended_actions_priority_order: { type: 'array', items: { type: 'string' } },
          chain_to: { type: 'array', items: { type: 'string' } },
          privacy: { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } },
        }}}}}}}},
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Gate image processing based on content safety', 'x-agent-callable': true,
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['image'], properties: {
          image: { type: 'string' }, safety_check: { type: 'boolean', default: true },
          max_cost: { type: 'number' },
        }}}}},
        responses: { '200': { description: 'Gate decision', content: { 'application/json': { schema: { type: 'object', properties: {
          execute: { type: 'boolean' }, confidence: { type: 'number', minimum: 0, maximum: 1 },
          blocking_flags: { type: 'array', items: { type: 'string' } },
          recommended_actions_priority_order: { type: 'array', items: { type: 'string' } },
          chain_to: { type: 'array', items: { type: 'string' } },
          privacy: { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } },
        }}}}}}}},
      
      '/extract-document': { post: { operationId: 'extractDocument', summary: 'Extract structured content from document images including tables, forms, and layout analysis', 'x-agent-callable': true,
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['image'], properties: {
          image: { type: 'string', description: 'Base64-encoded image or URL' },
          image_format: { type: 'string', enum: ['jpeg', 'png', 'webp', 'pdf'] },
          extract_tables: { type: 'boolean', default: true },
          extract_forms: { type: 'boolean', default: true },
          extract_headings: { type: 'boolean', default: true },
          language: { type: 'string', default: 'en' },
        }}}}},
        responses: { '200': { description: 'Structured document extraction', content: { 'application/json': { schema: { type: 'object', required: ['trace_id', 'status', 'document_type'], properties: {
          trace_id: { type: 'string' },
          status: { type: 'string', enum: ['success', 'error'] },
          document_type: { type: 'string', enum: ['invoice','form','report','article','table','letter','receipt','contract','other'] },
          title: { type: 'string', nullable: true },
          language: { type: 'string' },
          layout: { type: 'object', properties: { sections: { type: 'array', items: { type: 'object', properties: { heading: { type: 'string', nullable: true }, content: { type: 'string' }, position: { type: 'string', enum: ['top','middle','bottom'] } } } }, has_tables: { type: 'boolean' }, has_forms: { type: 'boolean' }, column_count: { type: 'integer' } } },
          tables: { type: 'array', items: { type: 'object', properties: { headers: { type: 'array', items: { type: 'string' } }, rows: { type: 'array', items: { type: 'array', items: { type: 'string' } } }, caption: { type: 'string', nullable: true } } } },
          form_fields: { type: 'array', items: { type: 'object', properties: { label: { type: 'string' }, value: { type: 'string', nullable: true }, field_type: { type: 'string', enum: ['text','checkbox','signature','date'] } } } },
          key_value_pairs: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, value: { type: 'string' } } } },
          full_text: { type: 'string' },
          summary: { type: 'string' },
          confidence: { type: 'number', minimum: 0, maximum: 1 },
          recommended_actions_priority_order: { type: 'array', items: { type: 'string' } },
          chain_to: { type: 'array', items: { type: 'string' } },
          privacy: { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } },
          latency_ms: { type: 'number' },
        }}}}}}}},
      '/entity-link': { post: { operationId: 'entityLink', summary: 'Link extracted entities to canonical concepts and knowledge base entries', 'x-agent-callable': true,
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['entities'], properties: {
          entities: { type: 'array', items: { type: 'string' }, minItems: 1, maxItems: 50, description: 'List of entity strings to link' },
          context: { type: 'string', description: 'Optional context for disambiguation' },
          domain: { type: 'string', description: 'Domain hint e.g. finance, medical, legal' },
        }}}}},
        responses: { '200': { description: 'Linked entities', content: { 'application/json': { schema: { type: 'object', required: ['trace_id', 'linked_entities'], properties: {
          trace_id: { type: 'string' },
          status: { type: 'string', enum: ['success', 'error'] },
          linked_entities: { type: 'array', items: { type: 'object', properties: {
            entity: { type: 'string' }, type: { type: 'string', enum: ['person','org','location','product','concept','event','date','currency','other'] },
            canonical_name: { type: 'string' }, description: { type: 'string' },
            confidence: { type: 'number', minimum: 0, maximum: 1 },
            related_concepts: { type: 'array', items: { type: 'string' } },
            domain_relevance: { type: 'string', enum: ['high','medium','low'] },
          }}},
          entity_count: { type: 'integer' },
          high_confidence_count: { type: 'integer' },
          entity_graph_summary: { type: 'string' },
          recommended_actions_priority_order: { type: 'array', items: { type: 'string' } },
          chain_to: { type: 'array', items: { type: 'string' } },
          privacy: { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } },
          latency_ms: { type: 'number' },
        }}}}}}}},
      '/compare': { post: { operationId: 'compareImages', summary: 'Cross-image comparison for visual consistency, style matching, and ranking', 'x-agent-callable': true,
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['images'], properties: {
          images: { type: 'array', minItems: 2, maxItems: 5, items: { type: 'object', required: ['image'], properties: {
            image: { type: 'string', description: 'Base64 or URL' },
            image_format: { type: 'string', enum: ['jpeg','png','webp'] },
            label: { type: 'string', description: 'Optional label for this image' },
          }}},
          comparison_focus: { type: 'string', description: 'What to focus comparison on e.g. style, quality, content' },
          language: { type: 'string', default: 'en' },
        }}}}},
        responses: { '200': { description: 'Image comparison result', content: { 'application/json': { schema: { type: 'object', required: ['trace_id', 'comparison_summary'], properties: {
          trace_id: { type: 'string' },
          status: { type: 'string', enum: ['success', 'error'] },
          image_count: { type: 'integer' },
          comparison_focus: { type: 'string' },
          comparison_summary: { type: 'string' },
          similarities: { type: 'array', items: { type: 'string' } },
          differences: { type: 'array', items: { type: 'object', properties: { aspect: { type: 'string' }, description: { type: 'string' }, significance: { type: 'string', enum: ['high','medium','low'] } } } },
          ranking: { type: 'array', items: { type: 'object', properties: { image_index: { type: 'integer' }, label: { type: 'string' }, rank: { type: 'integer' }, reason: { type: 'string' } } } },
          best_for: { type: 'object', properties: { purpose: { type: 'string' }, image_index: { type: 'integer' }, reason: { type: 'string' } } },
          visual_consistency_score: { type: 'number', minimum: 0, maximum: 1 },
          style_match_score: { type: 'number', minimum: 0, maximum: 1 },
          confidence: { type: 'number', minimum: 0, maximum: 1 },
          recommended_actions_priority_order: { type: 'array', items: { type: 'string' } },
          chain_to: { type: 'array', items: { type: 'string' } },
          privacy: { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } },
          latency_ms: { type: 'number' },
        }}}}}}}},
      '/jobs/{jobId}': { get: { operationId: 'getJob', summary: 'Poll async job status', 'x-agent-callable': true,
        parameters: [{ name: 'jobId', in: 'path', required: true, schema: { type: 'string' } }],
        responses: { '200': { description: 'Job status', content: { 'application/json': { schema: { type: 'object', properties: {
          job_id: { type: 'string' }, status: { type: 'string', enum: ['pending', 'processing', 'success', 'error'] },
          confidence: { type: 'number', minimum: 0, maximum: 1 },
          recommended_actions_priority_order: { type: 'array', items: { type: 'string' } },
          chain_to: { type: 'array', items: { type: 'string' } },
          privacy: { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } },
          result: { type: 'object', properties: { caption: { type: 'string' }, tags: { type: 'array', items: { type: 'string' } }, confidence_per_section: { type: 'object', properties: { caption: { type: 'number' }, tags: { type: 'number' }, ocr: { type: 'number' }, faces: { type: 'number' } } } } }, error: { type: 'string', nullable: true },
        }}}}}}}},
    },
  });
});
