import { Router, Request, Response } from 'express';
const router = Router();

const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string', format: 'date-time' }, success: { type: 'boolean' } };
const provenance = { type: 'object', properties: { provider: { type: 'string' }, retrieved_at: { type: 'string', format: 'date-time' }, freshness_score: { type: 'number', minimum: 0, maximum: 1 } } };
const chainFields = { source_provenance: provenance, cache_ttl_seconds: { type: 'integer' }, cache_recommended: { type: 'boolean' }, recommended_next_api: { type: 'string' }, recommended_next_endpoint: { type: 'string' }, automation_safe: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Blockchain Transaction Lookup API', version: '1.0.0', description: 'Look up blockchain transactions, decode calldata, trace internal calls and assess transaction risk for onchain compliance agents', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 300 }, pay_per_call: { lookup: '$0.002', decode: '$0.003', trace: '$0.004', 'execution-gate': '$0.001', 'tx-intelligence': '$0.008', risk: '$0.004', batch: '$0.015' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/blockchain-tx-lookup' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/lookup': { post: { operationId: 'lookupTx', summary: 'Look up transaction details by hash', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['tx_hash'], properties: { tx_hash: { type: 'string' }, chain: { type: 'string' } } } } } }, responses: { '200': { description: 'Transaction details', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, tx_hash: { type: 'string' }, status: { type: 'string' }, value_usd: { type: 'number' }, transaction_type: { type: 'string' }, ...chainFields, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } } } } },
      '/decode': { post: { operationId: 'decodeTx', summary: 'Decode transaction input data', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { tx_hash: { type: 'string' }, chain: { type: 'string' }, input_data: { type: 'string' } } } } } }, responses: { '200': { description: 'Decoded transaction', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, method_name: { type: 'string' }, decoded_params: { type: 'array', items: { type: 'object' } }, protocol: { type: 'string' }, ...chainFields, privacy } } } } } } } },
      '/trace': { post: { operationId: 'traceTx', summary: 'Trace internal transaction calls', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['tx_hash'], properties: { tx_hash: { type: 'string' }, chain: { type: 'string' } } } } } }, responses: { '200': { description: 'Transaction trace', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, internal_txs: { type: 'array', items: { type: 'object' } }, token_transfers: { type: 'array', items: { type: 'object' } }, protocols_used: { type: 'array', items: { type: 'string' } }, ...chainFields, privacy } } } } } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['tx_hash'], properties: { tx_hash: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, ...chainFields, privacy } } } } } } } },
      '/tx-intelligence': { post: { operationId: 'txIntelligence', summary: 'ONE-CALL: lookup + decode + trace + risk assessment', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['tx_hash'], properties: { tx_hash: { type: 'string' }, chain: { type: 'string' } } } } } }, responses: { '200': { description: 'Full transaction intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, status: { type: 'string' }, action_summary: { type: 'string' }, risk_level: { type: 'string' }, is_suspicious: { type: 'boolean' }, ...chainFields, confidence_per_section: confidence, privacy } } } } } } } },
      '/risk': { post: { operationId: 'assessTxRisk', summary: 'Assess transaction risk and compliance flags', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['tx_hash'], properties: { tx_hash: { type: 'string' }, chain: { type: 'string' } } } } } }, responses: { '200': { description: 'Transaction risk', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, risk_score: { type: 'number' }, risk_level: { type: 'string' }, risk_flags: { type: 'array', items: { type: 'object' } }, recommended_action: { type: 'string' }, ...chainFields, privacy } } } } } } } },
      '/batch': { post: { operationId: 'batchTransactions', summary: 'Batch lookup up to 5 transactions', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['transactions'], properties: { transactions: { type: 'array', items: { type: 'object' }, maxItems: 5 } } } } } }, responses: { '200': { description: 'Batch results', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, batch_count: { type: 'integer' }, results: { type: 'array', items: { type: 'object' } }, ...chainFields } } } } } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
