import { Router, Request, Response } from 'express';
const router = Router();
const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string' }, success: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Hotel Price Lookup API', version: '1.0.0', description: 'Search hotels by location, look up pricing and availability, and compare options for travel booking automation, expense management, and itinerary planning agents', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 100, requests_per_month: 3000 }, pay_per_call: { search: '$0.004', price: '$0.003', availability: '$0.003', 'execution-gate': '$0.001', lookup: '$0.008' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/hotel-price' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/search': { post: { operationId: 'searchHotels', summary: 'Search hotels by location and date range', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['location', 'check_in', 'check_out'], properties: { location: { type: 'string' }, check_in: { type: 'string' }, check_out: { type: 'string' } } } } } }, responses: { '200': { description: 'Hotel search results', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, hotels: { type: 'array', items: { type: 'object' } }, price_range: { type: 'object' }, disclaimer: { type: 'string' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing fields' }, '500': { description: 'Failed' } } } },
      '/price': { post: { operationId: 'getHotelPrice', summary: 'Get pricing for a specific hotel and dates', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['hotel_id', 'check_in', 'check_out'], properties: { hotel_id: { type: 'string' }, check_in: { type: 'string' }, check_out: { type: 'string' } } } } } }, responses: { '200': { description: 'Hotel pricing', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, hotel_id: { type: 'string' }, room_types: { type: 'array', items: { type: 'object' } }, lowest_price_usd: { type: 'number' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing fields' }, '500': { description: 'Failed' } } } },
      '/availability': { post: { operationId: 'checkAvailability', summary: 'Check room availability for a hotel and dates', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['hotel_id', 'check_in', 'check_out'], properties: { hotel_id: { type: 'string' }, check_in: { type: 'string' }, check_out: { type: 'string' } } } } } }, responses: { '200': { description: 'Availability result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, hotel_id: { type: 'string' }, is_available: { type: 'boolean' }, available_rooms: { type: 'array', items: { type: 'object' } }, last_room_warning: { type: 'boolean' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing fields' }, '500': { description: 'Failed' } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['location'], properties: { location: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, next_api: { type: 'string' }, blocking_flags: actions, confidence_per_section: confidence, privacy } } } } } } } },
      '/lookup': { post: { operationId: 'lookup', summary: 'ONE-CALL: full hotel intelligence — search + best value + best rated + price ranges', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['location', 'check_in', 'check_out'], properties: { location: { type: 'string' }, check_in: { type: 'string' }, check_out: { type: 'string' } } } } } }, responses: { '200': { description: 'Full hotel intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, top_hotels: { type: 'array', items: { type: 'object' } }, best_value: { type: 'object' }, best_rated: { type: 'object' }, price_range: { type: 'object' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing fields' }, '500': { description: 'Failed' } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
