import { Router, Request, Response } from 'express';
const router = Router();
const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string' }, success: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Package Tracking API', version: '1.0.0', description: 'Track packages across all major carriers, auto-detect carrier from tracking number, and bulk-track multiple shipments for logistics, e-commerce, and supply chain automation', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 100, requests_per_month: 3000 }, pay_per_call: { track: '$0.002', 'detect-carrier': '$0.001', bulk: '$0.008', 'execution-gate': '$0.001', lookup: '$0.003' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/package-tracking' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/track': { post: { operationId: 'trackPackage', summary: 'Track a package by tracking number', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['tracking_number'], properties: { tracking_number: { type: 'string' }, carrier: { type: 'string' } } } } } }, responses: { '200': { description: 'Package tracking result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, tracking_number: { type: 'string' }, carrier: { type: 'string' }, status: { type: 'string', enum: ['in_transit', 'delivered', 'out_for_delivery', 'pending', 'exception', 'unknown'] }, estimated_delivery: { type: 'string' }, events: { type: 'array', items: { type: 'object' } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing tracking_number' }, '500': { description: 'Failed' } } } },
      '/detect-carrier': { post: { operationId: 'detectCarrier', summary: 'Auto-detect carrier from tracking number format', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['tracking_number'], properties: { tracking_number: { type: 'string' } } } } } }, responses: { '200': { description: 'Carrier detection result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, detected_carrier: { type: 'string' }, carrier_code: { type: 'string' }, confidence: { type: 'number' }, tracking_url: { type: 'string' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing tracking_number' }, '500': { description: 'Failed' } } } },
      '/bulk': { post: { operationId: 'bulkTrack', summary: 'Bulk track up to 20 packages', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['tracking_numbers'], properties: { tracking_numbers: { type: 'array', items: { type: 'string' }, maxItems: 20 } } } } } }, responses: { '200': { description: 'Bulk tracking results', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, results: { type: 'array', items: { type: 'object' } }, summary: { type: 'object', properties: { total: { type: 'number' }, delivered: { type: 'number' }, in_transit: { type: 'number' }, exceptions: { type: 'number' } } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing tracking_numbers' }, '500': { description: 'Failed' } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['tracking_number'], properties: { tracking_number: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, next_api: { type: 'string' }, blocking_flags: actions, confidence_per_section: confidence, privacy } } } } } } } },
      '/lookup': { post: { operationId: 'lookup', summary: 'ONE-CALL: full package tracking — detect carrier + track + delay risk', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['tracking_number'], properties: { tracking_number: { type: 'string' } } } } } }, responses: { '200': { description: 'Full tracking intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, tracking_number: { type: 'string' }, carrier: { type: 'string' }, tracking_url: { type: 'string' }, status: { type: 'string' }, delay_risk: { type: 'string', enum: ['high', 'medium', 'low', 'none'] }, events: { type: 'array', items: { type: 'object' } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing tracking_number' }, '500': { description: 'Failed' } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
