import { Router, Request, Response } from 'express';
const router = Router();

const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string', format: 'date-time' }, success: { type: 'boolean' } };
const provenance = { type: 'object', properties: { provider: { type: 'string' }, retrieved_at: { type: 'string', format: 'date-time' }, freshness_score: { type: 'number', minimum: 0, maximum: 1 } } };
const chainFields = { source_provenance: provenance, cache_ttl_seconds: { type: 'integer' }, cache_recommended: { type: 'boolean' }, recommended_next_api: { type: 'string' }, recommended_next_endpoint: { type: 'string' }, automation_safe: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Executive Risk API', version: '1.0.0', description: 'Assess executive risk profiles, identify red flags, score reputation for partnership and compliance diligence agents', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 100 }, pay_per_call: { assess: '$0.006', 'red-flags': '$0.005', reputation: '$0.005', 'execution-gate': '$0.001', 'executive-intelligence': '$0.015', 'news-signals': '$0.005', batch: '$0.025' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/executive-risk' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/assess': { post: { operationId: 'assessExecutiveRisk', summary: 'Assess executive risk profile', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['name'], properties: { name: { type: 'string' }, company: { type: 'string' }, role: { type: 'string' } } } } } }, responses: { '200': { description: 'Risk assessment', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, overall_risk: { type: 'string', enum: ['low', 'medium', 'high', 'critical'] }, risk_score: { type: 'number' }, risk_dimensions: { type: 'object' }, ...chainFields, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } } } } },
      '/red-flags': { post: { operationId: 'identifyRedFlags', summary: 'Identify executive red flags', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['name'], properties: { name: { type: 'string' }, company: { type: 'string' } } } } } }, responses: { '200': { description: 'Red flags', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, red_flags: { type: 'array', items: { type: 'object' } }, flag_count: { type: 'integer' }, escalation_required: { type: 'boolean' }, ...chainFields, privacy } } } } } } } },
      '/reputation': { post: { operationId: 'getReputation', summary: 'Get executive reputation score', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['name'], properties: { name: { type: 'string' }, company: { type: 'string' }, industry: { type: 'string' } } } } } }, responses: { '200': { description: 'Reputation score', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, reputation_score: { type: 'number' }, industry_standing: { type: 'string' }, media_sentiment: { type: 'string' }, ...chainFields, privacy } } } } } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['name'], properties: { name: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, ...chainFields, privacy } } } } } } } },
      '/executive-intelligence': { post: { operationId: 'executiveIntelligence', summary: 'ONE-CALL: risk + red flags + reputation + recommendation', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['name'], properties: { name: { type: 'string' }, company: { type: 'string' }, role: { type: 'string' }, context: { type: 'string' } } } } } }, responses: { '200': { description: 'Full executive intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, overall_risk: { type: 'string' }, red_flags: { type: 'array', items: { type: 'object' } }, reputation_score: { type: 'number' }, engagement_recommendation: { type: 'string' }, ...chainFields, confidence_per_section: confidence, privacy } } } } } } } },
      '/news-signals': { post: { operationId: 'getNewsSignals', summary: 'Get news-based risk signals', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['name'], properties: { name: { type: 'string' }, company: { type: 'string' } } } } } }, responses: { '200': { description: 'News risk signals', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, news_risk_score: { type: 'number' }, recent_headlines: { type: 'array', items: { type: 'object' } }, alert_level: { type: 'string' }, ...chainFields, privacy } } } } } } } },
      '/batch': { post: { operationId: 'batchExecutives', summary: 'Batch assess up to 5 executives', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['executives'], properties: { executives: { type: 'array', items: { type: 'object' }, maxItems: 5 } } } } } }, responses: { '200': { description: 'Batch results', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, batch_count: { type: 'integer' }, results: { type: 'array', items: { type: 'object' } }, ...chainFields } } } } } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
