import { Router, Request, Response } from 'express';
const router = Router();
const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string' }, success: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Image OCR API', version: '1.0.0', description: 'Extract text, parse receipts, documents, and tables from image URLs for autonomous agents', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 100, requests_per_month: 3000 }, pay_per_call: { ocr: '$0.004', 'receipt-ocr': '$0.004', 'document-ocr': '$0.004', 'table-extract': '$0.003', extract: '$0.006', execution_gate: '$0.001' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/image-ocr' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/ocr': { post: { operationId: 'ocr', summary: 'Extract all text from an image URL with structured blocks and language detection', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['image_url'], properties: { image_url: { type: 'string' }, language: { type: 'string' } } } } } }, responses: { '200': { description: 'OCR result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, raw_text: { type: 'string' }, text_blocks: { type: 'array', items: { type: 'object', properties: { id: { type: 'number' }, text: { type: 'string' }, type: { type: 'string', enum: ['heading', 'paragraph', 'list', 'table', 'code', 'other'] }, confidence: { type: 'number' }, bounding_box: { type: 'object', properties: { x: { type: 'number' }, y: { type: 'number' }, width: { type: 'number' }, height: { type: 'number' } } } } } }, language_detected: { type: 'string' }, word_count: { type: 'number' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing image_url' }, '500': { description: 'Failed' } } } },
      '/receipt-ocr': { post: { operationId: 'receiptOcr', summary: 'Parse receipt image — merchant, date, line items, totals, payment method', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['image_url'], properties: { image_url: { type: 'string' } } } } } }, responses: { '200': { description: 'Parsed receipt', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, merchant: { type: 'object', properties: { name: { type: 'string' }, address: { type: 'string' }, category: { type: 'string' } } }, line_items: { type: 'array', items: { type: 'object', properties: { description: { type: 'string' }, quantity: { type: 'number' }, total: { type: 'number' } } } }, totals: { type: 'object', properties: { subtotal: { type: 'number' }, tax: { type: 'number' }, total: { type: 'number' }, currency: { type: 'string' } } }, payment_method: { type: 'string', enum: ['cash', 'credit', 'debit', 'contactless', 'unknown'] }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing image_url' }, '500': { description: 'Failed' } } } },
      '/document-ocr': { post: { operationId: 'documentOcr', summary: 'Parse document image — title, sections, paragraphs, tables, form fields', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['image_url'], properties: { image_url: { type: 'string' }, document_type: { type: 'string' } } } } } }, responses: { '200': { description: 'Parsed document', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, document_type: { type: 'string', enum: ['invoice', 'form', 'letter', 'contract', 'report', 'id', 'other'] }, title: { type: 'string' }, sections: { type: 'array', items: { type: 'object', properties: { heading: { type: 'string' }, content: { type: 'string' } } } }, form_fields: { type: 'array', items: { type: 'object', properties: { label: { type: 'string' }, value: { type: 'string' } } } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing image_url' }, '500': { description: 'Failed' } } } },
      '/table-extract': { post: { operationId: 'tableExtract', summary: 'Extract tables from image as structured JSON with headers and rows', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['image_url'], properties: { image_url: { type: 'string' } } } } } }, responses: { '200': { description: 'Extracted tables', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, tables: { type: 'array', items: { type: 'object', properties: { table_id: { type: 'number' }, headers: actions, rows: { type: 'array', items: actions }, confidence: { type: 'number' } } } }, tables_found: { type: 'number' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing image_url' }, '500': { description: 'Failed' } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['image_url'], properties: { image_url: { type: 'string' }, document_type: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, recommended_endpoint: { type: 'string' }, blocking_flags: actions, confidence_per_section: confidence, privacy } } } } } } } },
      '/extract': { post: { operationId: 'extract', summary: 'ONE-CALL: auto-detect document type and extract structured data', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['image_url'], properties: { image_url: { type: 'string' }, hint: { type: 'string' } } } } } }, responses: { '200': { description: 'Auto-extracted structured data', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, detected_type: { type: 'string', enum: ['receipt', 'invoice', 'form', 'table', 'document', 'id', 'other'] }, raw_text: { type: 'string' }, structured_data: { type: 'object' }, tables: { type: 'array', items: { type: 'object' } }, extraction_confidence: { type: 'number' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing image_url' }, '500': { description: 'Failed' } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
