import { Router, Request, Response } from 'express';
const router = Router();
const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string' }, success: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'URL Screenshot Diff API', version: '1.0.0', description: 'Capture screenshots of URLs, compare visual changes between two URLs or timestamps, and monitor visual regressions for QA and competitive intelligence agents.', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 200, requests_per_month: 6000 }, pay_per_call: { capture: '$0.004', diff: '$0.006', monitor: '$0.003', 'execution-gate': '$0.001', analyze: '$0.008' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/url-screenshot-diff' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/capture': { post: { operationId: 'capture', summary: 'Capture screenshot of URL — image URL, dimensions, load time', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['url'], properties: { url: { type: 'string' } } } } } }, responses: { '200': { description: 'Screenshot captured', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, url: { type: 'string' }, screenshot: { type: 'object', properties: { image_url: { type: 'string' }, width: { type: 'number' }, height: { type: 'number' }, format: { type: 'string' }, captured_at: { type: 'string' } } }, page_info: { type: 'object' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing url' }, '500': { description: 'Failed' } } } },
      '/diff': { post: { operationId: 'diff', summary: 'Visual diff between two URLs — change %, changed regions, severity', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['url_a', 'url_b'], properties: { url_a: { type: 'string' }, url_b: { type: 'string' } } } } } }, responses: { '200': { description: 'Visual diff result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, url_a: { type: 'string' }, url_b: { type: 'string' }, diff: { type: 'object', properties: { diff_image_url: { type: 'string' }, change_percentage: { type: 'number' }, similarity_score: { type: 'number' }, severity: { type: 'string', enum: ['none', 'low', 'medium', 'high', 'critical'] } } }, regression_detected: { type: 'boolean' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing url_a or url_b' }, '500': { description: 'Failed' } } } },
      '/monitor': { post: { operationId: 'monitor', summary: 'Configure visual monitoring — set interval, alert threshold, viewports', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['url'], properties: { url: { type: 'string' }, interval: { type: 'string', default: '1h' } } } } } }, responses: { '200': { description: 'Monitor configured', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, url: { type: 'string' }, monitor_config: { type: 'object', properties: { monitor_id: { type: 'string' }, interval: { type: 'string' }, status: { type: 'string' }, next_check: { type: 'string' } } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing url' }, '500': { description: 'Failed' } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['url'], properties: { url: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, next_api: { type: 'string' }, blocking_flags: actions, confidence_per_section: confidence, privacy } } } } } } } },
      '/analyze': { post: { operationId: 'analyze', summary: 'ONE-CALL: full visual analysis — screenshot + page info + visual analysis + monitor recommendation', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['url'], properties: { url: { type: 'string' } } } } } }, responses: { '200': { description: 'Full visual intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, url: { type: 'string' }, screenshot: { type: 'object' }, page_info: { type: 'object' }, visual_analysis: { type: 'object' }, monitor_recommendation: { type: 'object' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing url' }, '500': { description: 'Failed' } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
