// Curated static ISO-3166 (country) + ISO-4217 (currency) reference data.
// Hand-maintained constants — no LLM, no network. Covers all G20 plus the most
// commonly transacted countries/currencies. Extend as needed.

export interface Country { name: string; iso2: string; iso3: string; numeric: string; dial_code: string; currency: string; region: string; }
export interface Currency { code: string; name: string; symbol: string; minor_units: number; }

export const COUNTRIES: Country[] = [
  { name: 'United States', iso2: 'US', iso3: 'USA', numeric: '840', dial_code: '+1', currency: 'USD', region: 'Americas' },
  { name: 'Canada', iso2: 'CA', iso3: 'CAN', numeric: '124', dial_code: '+1', currency: 'CAD', region: 'Americas' },
  { name: 'Mexico', iso2: 'MX', iso3: 'MEX', numeric: '484', dial_code: '+52', currency: 'MXN', region: 'Americas' },
  { name: 'Brazil', iso2: 'BR', iso3: 'BRA', numeric: '076', dial_code: '+55', currency: 'BRL', region: 'Americas' },
  { name: 'Argentina', iso2: 'AR', iso3: 'ARG', numeric: '032', dial_code: '+54', currency: 'ARS', region: 'Americas' },
  { name: 'United Kingdom', iso2: 'GB', iso3: 'GBR', numeric: '826', dial_code: '+44', currency: 'GBP', region: 'Europe' },
  { name: 'Germany', iso2: 'DE', iso3: 'DEU', numeric: '276', dial_code: '+49', currency: 'EUR', region: 'Europe' },
  { name: 'France', iso2: 'FR', iso3: 'FRA', numeric: '250', dial_code: '+33', currency: 'EUR', region: 'Europe' },
  { name: 'Italy', iso2: 'IT', iso3: 'ITA', numeric: '380', dial_code: '+39', currency: 'EUR', region: 'Europe' },
  { name: 'Spain', iso2: 'ES', iso3: 'ESP', numeric: '724', dial_code: '+34', currency: 'EUR', region: 'Europe' },
  { name: 'Netherlands', iso2: 'NL', iso3: 'NLD', numeric: '528', dial_code: '+31', currency: 'EUR', region: 'Europe' },
  { name: 'Switzerland', iso2: 'CH', iso3: 'CHE', numeric: '756', dial_code: '+41', currency: 'CHF', region: 'Europe' },
  { name: 'Sweden', iso2: 'SE', iso3: 'SWE', numeric: '752', dial_code: '+46', currency: 'SEK', region: 'Europe' },
  { name: 'Norway', iso2: 'NO', iso3: 'NOR', numeric: '578', dial_code: '+47', currency: 'NOK', region: 'Europe' },
  { name: 'Poland', iso2: 'PL', iso3: 'POL', numeric: '616', dial_code: '+48', currency: 'PLN', region: 'Europe' },
  { name: 'Russia', iso2: 'RU', iso3: 'RUS', numeric: '643', dial_code: '+7', currency: 'RUB', region: 'Europe' },
  { name: 'Turkey', iso2: 'TR', iso3: 'TUR', numeric: '792', dial_code: '+90', currency: 'TRY', region: 'Europe' },
  { name: 'China', iso2: 'CN', iso3: 'CHN', numeric: '156', dial_code: '+86', currency: 'CNY', region: 'Asia' },
  { name: 'Japan', iso2: 'JP', iso3: 'JPN', numeric: '392', dial_code: '+81', currency: 'JPY', region: 'Asia' },
  { name: 'South Korea', iso2: 'KR', iso3: 'KOR', numeric: '410', dial_code: '+82', currency: 'KRW', region: 'Asia' },
  { name: 'India', iso2: 'IN', iso3: 'IND', numeric: '356', dial_code: '+91', currency: 'INR', region: 'Asia' },
  { name: 'Indonesia', iso2: 'ID', iso3: 'IDN', numeric: '360', dial_code: '+62', currency: 'IDR', region: 'Asia' },
  { name: 'Singapore', iso2: 'SG', iso3: 'SGP', numeric: '702', dial_code: '+65', currency: 'SGD', region: 'Asia' },
  { name: 'Hong Kong', iso2: 'HK', iso3: 'HKG', numeric: '344', dial_code: '+852', currency: 'HKD', region: 'Asia' },
  { name: 'Saudi Arabia', iso2: 'SA', iso3: 'SAU', numeric: '682', dial_code: '+966', currency: 'SAR', region: 'Asia' },
  { name: 'United Arab Emirates', iso2: 'AE', iso3: 'ARE', numeric: '784', dial_code: '+971', currency: 'AED', region: 'Asia' },
  { name: 'Israel', iso2: 'IL', iso3: 'ISR', numeric: '376', dial_code: '+972', currency: 'ILS', region: 'Asia' },
  { name: 'Australia', iso2: 'AU', iso3: 'AUS', numeric: '036', dial_code: '+61', currency: 'AUD', region: 'Oceania' },
  { name: 'New Zealand', iso2: 'NZ', iso3: 'NZL', numeric: '554', dial_code: '+64', currency: 'NZD', region: 'Oceania' },
  { name: 'South Africa', iso2: 'ZA', iso3: 'ZAF', numeric: '710', dial_code: '+27', currency: 'ZAR', region: 'Africa' },
  { name: 'Nigeria', iso2: 'NG', iso3: 'NGA', numeric: '566', dial_code: '+234', currency: 'NGN', region: 'Africa' },
  { name: 'Egypt', iso2: 'EG', iso3: 'EGY', numeric: '818', dial_code: '+20', currency: 'EGP', region: 'Africa' },
  { name: 'Kenya', iso2: 'KE', iso3: 'KEN', numeric: '404', dial_code: '+254', currency: 'KES', region: 'Africa' },
  { name: 'Ireland', iso2: 'IE', iso3: 'IRL', numeric: '372', dial_code: '+353', currency: 'EUR', region: 'Europe' },
  { name: 'Portugal', iso2: 'PT', iso3: 'PRT', numeric: '620', dial_code: '+351', currency: 'EUR', region: 'Europe' },
  { name: 'Belgium', iso2: 'BE', iso3: 'BEL', numeric: '056', dial_code: '+32', currency: 'EUR', region: 'Europe' },
  { name: 'Austria', iso2: 'AT', iso3: 'AUT', numeric: '040', dial_code: '+43', currency: 'EUR', region: 'Europe' },
  { name: 'Denmark', iso2: 'DK', iso3: 'DNK', numeric: '208', dial_code: '+45', currency: 'DKK', region: 'Europe' },
  { name: 'Finland', iso2: 'FI', iso3: 'FIN', numeric: '246', dial_code: '+358', currency: 'EUR', region: 'Europe' },
  { name: 'Thailand', iso2: 'TH', iso3: 'THA', numeric: '764', dial_code: '+66', currency: 'THB', region: 'Asia' },
  { name: 'Vietnam', iso2: 'VN', iso3: 'VNM', numeric: '704', dial_code: '+84', currency: 'VND', region: 'Asia' },
  { name: 'Malaysia', iso2: 'MY', iso3: 'MYS', numeric: '458', dial_code: '+60', currency: 'MYR', region: 'Asia' },
  { name: 'Philippines', iso2: 'PH', iso3: 'PHL', numeric: '608', dial_code: '+63', currency: 'PHP', region: 'Asia' },
  { name: 'Chile', iso2: 'CL', iso3: 'CHL', numeric: '152', dial_code: '+56', currency: 'CLP', region: 'Americas' },
  { name: 'Colombia', iso2: 'CO', iso3: 'COL', numeric: '170', dial_code: '+57', currency: 'COP', region: 'Americas' },
];

export const CURRENCIES: Record<string, Currency> = {
  USD: { code: 'USD', name: 'US Dollar', symbol: '$', minor_units: 2 },
  EUR: { code: 'EUR', name: 'Euro', symbol: '€', minor_units: 2 },
  GBP: { code: 'GBP', name: 'Pound Sterling', symbol: '£', minor_units: 2 },
  JPY: { code: 'JPY', name: 'Yen', symbol: '¥', minor_units: 0 },
  CNY: { code: 'CNY', name: 'Yuan Renminbi', symbol: '¥', minor_units: 2 },
  CAD: { code: 'CAD', name: 'Canadian Dollar', symbol: '$', minor_units: 2 },
  AUD: { code: 'AUD', name: 'Australian Dollar', symbol: '$', minor_units: 2 },
  NZD: { code: 'NZD', name: 'New Zealand Dollar', symbol: '$', minor_units: 2 },
  CHF: { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', minor_units: 2 },
  SEK: { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', minor_units: 2 },
  NOK: { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', minor_units: 2 },
  DKK: { code: 'DKK', name: 'Danish Krone', symbol: 'kr', minor_units: 2 },
  PLN: { code: 'PLN', name: 'Zloty', symbol: 'zł', minor_units: 2 },
  RUB: { code: 'RUB', name: 'Russian Ruble', symbol: '₽', minor_units: 2 },
  TRY: { code: 'TRY', name: 'Turkish Lira', symbol: '₺', minor_units: 2 },
  KRW: { code: 'KRW', name: 'Won', symbol: '₩', minor_units: 0 },
  INR: { code: 'INR', name: 'Indian Rupee', symbol: '₹', minor_units: 2 },
  IDR: { code: 'IDR', name: 'Rupiah', symbol: 'Rp', minor_units: 2 },
  SGD: { code: 'SGD', name: 'Singapore Dollar', symbol: '$', minor_units: 2 },
  HKD: { code: 'HKD', name: 'Hong Kong Dollar', symbol: '$', minor_units: 2 },
  SAR: { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', minor_units: 2 },
  AED: { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', minor_units: 2 },
  ILS: { code: 'ILS', name: 'New Israeli Sheqel', symbol: '₪', minor_units: 2 },
  ZAR: { code: 'ZAR', name: 'Rand', symbol: 'R', minor_units: 2 },
  NGN: { code: 'NGN', name: 'Naira', symbol: '₦', minor_units: 2 },
  EGP: { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£', minor_units: 2 },
  KES: { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', minor_units: 2 },
  THB: { code: 'THB', name: 'Baht', symbol: '฿', minor_units: 2 },
  VND: { code: 'VND', name: 'Dong', symbol: '₫', minor_units: 0 },
  MYR: { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', minor_units: 2 },
  PHP: { code: 'PHP', name: 'Philippine Peso', symbol: '₱', minor_units: 2 },
  MXN: { code: 'MXN', name: 'Mexican Peso', symbol: '$', minor_units: 2 },
  BRL: { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', minor_units: 2 },
  ARS: { code: 'ARS', name: 'Argentine Peso', symbol: '$', minor_units: 2 },
  CLP: { code: 'CLP', name: 'Chilean Peso', symbol: '$', minor_units: 0 },
  COP: { code: 'COP', name: 'Colombian Peso', symbol: '$', minor_units: 2 },
};
