import { Router, Request, Response } from 'express';
const router = Router();

const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string', format: 'date-time' }, success: { type: 'boolean' } };
const provenance = { type: 'object', properties: { provider: { type: 'string' }, retrieved_at: { type: 'string', format: 'date-time' }, freshness_score: { type: 'number', minimum: 0, maximum: 1 } } };
const chainFields = { source_provenance: provenance, cache_ttl_seconds: { type: 'integer' }, cache_recommended: { type: 'boolean' }, recommended_next_api: { type: 'string' }, recommended_next_endpoint: { type: 'string' }, automation_safe: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Virality Score API', version: '1.0.0', description: 'Score content virality potential, predict share velocity, analyze emotional triggers and optimize for maximum reach in social media agent workflows', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 300 }, pay_per_call: { score: '$0.003', predict: '$0.004', analyze: '$0.003', 'execution-gate': '$0.001', 'virality-intelligence': '$0.009', optimize: '$0.004', batch: '$0.020' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/virality-score' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/score': { post: { operationId: 'scoreVirality', summary: 'Score content virality potential 0-100', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['content'], properties: { content: { type: 'string' }, platform: { type: 'string' }, content_type: { type: 'string' } } } } } }, responses: { '200': { description: 'Virality score', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, virality_score: { type: 'integer' }, grade: { type: 'string' }, score_breakdown: { type: 'object' }, ...chainFields, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } } } } },
      '/predict': { post: { operationId: 'predictShares', summary: 'Predict share velocity and reach potential', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['content'], properties: { content: { type: 'string' }, platform: { type: 'string' }, audience_size: { type: 'integer' } } } } } }, responses: { '200': { description: 'Share prediction', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, predicted_shares: { type: 'string' }, share_velocity: { type: 'string' }, reach_multiplier: { type: 'number' }, ...chainFields, privacy } } } } } } } },
      '/analyze': { post: { operationId: 'analyzeEmotions', summary: 'Analyze emotional triggers and engagement drivers', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['content'], properties: { content: { type: 'string' }, platform: { type: 'string' } } } } } }, responses: { '200': { description: 'Emotion analysis', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, primary_emotion: { type: 'string' }, emotion_scores: { type: 'object' }, engagement_drivers: { type: 'array', items: { type: 'string' } }, ...chainFields, privacy } } } } } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['content'], properties: { content: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, ...chainFields, privacy } } } } } } } },
      '/virality-intelligence': { post: { operationId: 'viralityIntelligence', summary: 'ONE-CALL: score + predict + emotions + optimization tips', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['content'], properties: { content: { type: 'string' }, platform: { type: 'string' }, content_type: { type: 'string' } } } } } }, responses: { '200': { description: 'Full virality intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, virality_score: { type: 'integer' }, grade: { type: 'string' }, primary_emotion: { type: 'string' }, share_potential: { type: 'string' }, top_improvements: { type: 'array', items: { type: 'string' } }, ...chainFields, confidence_per_section: confidence, privacy } } } } } } } },
      '/optimize': { post: { operationId: 'optimizeContent', summary: 'Get optimization suggestions to increase virality', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['content'], properties: { content: { type: 'string' }, platform: { type: 'string' }, target_score: { type: 'integer' } } } } } }, responses: { '200': { description: 'Optimization suggestions', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, suggestions: { type: 'array', items: { type: 'string' } }, rewritten_hook: { type: 'string' }, expected_improvement: { type: 'string' }, ...chainFields, privacy } } } } } } } },
      '/batch': { post: { operationId: 'batchVirality', summary: 'Batch score up to 10 content pieces', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['items'], properties: { items: { type: 'array', items: { type: 'object' }, maxItems: 10 } } } } } }, responses: { '200': { description: 'Batch results', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, batch_count: { type: 'integer' }, results: { type: 'array', items: { type: 'object' } }, ...chainFields } } } } } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
