import { Router, Request, Response } from 'express';
const router = Router();

const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string', format: 'date-time' }, success: { type: 'boolean' } };
const provenance = { type: 'object', properties: { provider: { type: 'string' }, retrieved_at: { type: 'string', format: 'date-time' }, freshness_score: { type: 'number', minimum: 0, maximum: 1 } } };
const chainFields = { source_provenance: provenance, cache_ttl_seconds: { type: 'integer' }, cache_recommended: { type: 'boolean' }, recommended_next_api: { type: 'string' }, recommended_next_endpoint: { type: 'string' }, automation_safe: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Contract Clause Extractor API', version: '2.0.0', description: 'Extract contract clauses, analyze risk, compare versions, and identify red flags for legal and procurement automation agents', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 200 }, pay_per_call: { extract: '$0.010', 'analyze-risk': '$0.010', compare: '$0.015', 'execution-gate': '$0.001', 'contract-intelligence': '$0.020', 'red-flags': '$0.010', batch: '$0.040' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/contract-clause' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/extract': { post: { operationId: 'extractClauses', summary: 'Extract all clauses from contract document', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['contract_text'], properties: { contract_text: { type: 'string' }, clause_types: { type: 'string' } } } } } }, responses: { '200': { description: 'Extracted clauses', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, contract_type: { type: 'string' }, clauses: { type: 'array', items: { type: 'object' } }, parties: { type: 'array', items: { type: 'object' } }, ...chainFields, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } } } } },
      '/analyze-risk': { post: { operationId: 'analyzeRisk', summary: 'Analyze contract risk from party perspective', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['contract_text'], properties: { contract_text: { type: 'string' }, party_role: { type: 'string', enum: ['buyer', 'seller', 'licensor', 'licensee', 'employer', 'employee'] } } } } } }, responses: { '200': { description: 'Risk analysis', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, overall_risk: { type: 'string', enum: ['low', 'medium', 'high', 'critical'] }, risks: { type: 'array', items: { type: 'object' } }, ...chainFields, confidence_per_section: confidence, privacy } } } } } } } },
      '/compare': { post: { operationId: 'compareContracts', summary: 'Compare two contract versions for changes', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['contract_a', 'contract_b'], properties: { contract_a: { type: 'string' }, contract_b: { type: 'string' } } } } } }, responses: { '200': { description: 'Comparison result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, changes: { type: 'array', items: { type: 'object' } }, recommendation: { type: 'string' }, ...chainFields, confidence_per_section: confidence, privacy } } } } } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['contract_text'], properties: { contract_text: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, ...chainFields, confidence_per_section: confidence, privacy } } } } } } } },
      '/contract-intelligence': { post: { operationId: 'contractIntelligence', summary: 'ONE-CALL: extract + risk + red flags + recommendation', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['contract_text'], properties: { contract_text: { type: 'string' }, party_role: { type: 'string' }, context: { type: 'string' } } } } } }, responses: { '200': { description: 'Full contract intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, contract_type: { type: 'string' }, overall_risk: { type: 'string' }, red_flags: { type: 'array', items: { type: 'string' } }, recommended_action: { type: 'string', enum: ['sign', 'negotiate', 'reject'] }, ...chainFields, confidence_per_section: confidence, privacy } } } } } } } },
      '/red-flags': { post: { operationId: 'identifyRedFlags', summary: 'Identify red flag clauses requiring negotiation', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['contract_text'], properties: { contract_text: { type: 'string' } } } } } }, responses: { '200': { description: 'Red flags', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, red_flags: { type: 'array', items: { type: 'object' } }, sign_recommendation: { type: 'string' }, ...chainFields, confidence_per_section: confidence, privacy } } } } } } } },
      '/batch': { post: { operationId: 'batchContracts', summary: 'Batch analyze up to 5 contracts', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['contracts'], properties: { contracts: { type: 'array', items: { type: 'object' }, maxItems: 5 } } } } } }, responses: { '200': { description: 'Batch results', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, batch_count: { type: 'integer' }, results: { type: 'array', items: { type: 'object' } }, ...chainFields } } } } } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
