import { Router, Request, Response } from 'express';
const router = Router();

router.get('/', (req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Local Business API', version: '1.0.0', description: 'AI-powered local business intelligence, reputation analysis, foot traffic signals and competitive positioning for autonomous agents.', 'x-agent-callable': true, 'x-mcp-compatible': true },
    servers: [{ url: 'https://orbis-apis.onrender.com/local-business' }],
    paths: {
      '/analyze-business': { post: { operationId: 'analyzeBusiness', summary: 'Full local business analysis with SWOT, demographics and recommendations', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['business_name', 'location'], properties: { business_name: { type: 'string' }, location: { type: 'string' }, category: { type: 'string' }, competitors: { type: 'array', items: { type: 'string' } } } } } } }, responses: { '200': { description: 'Business score, market position, SWOT, demographics, foot traffic, recommendations', content: { 'application/json': { schema: { type: 'object', properties: { success: { type: 'boolean' }, business_score: { type: 'number' }, market_position: { type: 'string' }, strengths: { type: 'array', items: { type: 'string' } }, weaknesses: { type: 'array', items: { type: 'string' } }, opportunities: { type: 'array', items: { type: 'string' } }, threats: { type: 'array', items: { type: 'string' } }, confidence: { type: 'object' }, analyzed_at: { type: 'string' } } } } } }, '400': { description: 'Missing required fields' }, '500': { description: 'Error' } } } },
      '/reputation-analysis': { post: { operationId: 'reputationAnalysis', summary: 'Reputation score, sentiment breakdown and improvement priorities', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['business_name', 'location'], properties: { business_name: { type: 'string' }, location: { type: 'string' }, category: { type: 'string' }, review_data: { type: 'object' } } } } } }, responses: { '200': { description: 'Reputation score, sentiment, themes, trust signals, response templates', content: { 'application/json': { schema: { type: 'object', properties: { success: { type: 'boolean' }, reputation_score: { type: 'number' }, sentiment_breakdown: { type: 'object' }, review_themes: { type: 'object' }, improvement_priorities: { type: 'array', items: { type: 'object' } }, confidence: { type: 'object' } } } } } }, '400': { description: 'Missing fields' }, '500': { description: 'Error' } } } },
      '/foot-traffic-signals': { post: { operationId: 'footTrafficSignals', summary: 'Foot traffic estimates, peak times and catchment area profile', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['business_name', 'location'], properties: { business_name: { type: 'string' }, location: { type: 'string' }, category: { type: 'string' }, time_period: { type: 'string' } } } } } }, responses: { '200': { description: 'Traffic score, daily visitors, peak days/hours, catchment area, seasonal index', content: { 'application/json': { schema: { type: 'object', properties: { success: { type: 'boolean' }, traffic_score: { type: 'number' }, estimated_daily_visitors: { type: 'string' }, peak_days: { type: 'array', items: { type: 'string' } }, peak_hours: { type: 'array', items: { type: 'string' } }, confidence: { type: 'object' } } } } } }, '400': { description: 'Missing fields' }, '500': { description: 'Error' } } } },
      '/local-competitors': { post: { operationId: 'localCompetitors', summary: 'Local competitive landscape with competitor profiles and differentiation opportunities', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['business_name', 'location'], properties: { business_name: { type: 'string' }, location: { type: 'string' }, category: { type: 'string' }, radius_km: { type: 'number' } } } } } }, responses: { '200': { description: 'Competitor density, profiles, differentiation opportunities, positioning', content: { 'application/json': { schema: { type: 'object', properties: { success: { type: 'boolean' }, competitive_density: { type: 'string' }, competitor_profiles: { type: 'array', items: { type: 'object' } }, differentiation_opportunities: { type: 'array', items: { type: 'string' } }, confidence: { type: 'object' } } } } } }, '400': { description: 'Missing fields' }, '500': { description: 'Error' } } } },
      '/market-opportunity': { post: { operationId: 'marketOpportunity', summary: 'Local market opportunity score with ROI projections', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['location', 'category'], properties: { location: { type: 'string' }, category: { type: 'string' }, target_demographic: { type: 'string' }, investment_level: { type: 'string' } } } } } }, responses: { '200': { description: 'Opportunity score, market size, demand signals, ROI projections', content: { 'application/json': { schema: { type: 'object', properties: { success: { type: 'boolean' }, opportunity_score: { type: 'number' }, market_size_estimate: { type: 'object' }, roi_projection: { type: 'object' }, confidence: { type: 'object' } } } } } }, '400': { description: 'Missing fields' }, '500': { description: 'Error' } } } },
      '/customer-profile': { post: { operationId: 'customerProfile', summary: 'Build local customer personas with LTV and acquisition channels', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['business_name', 'location'], properties: { business_name: { type: 'string' }, location: { type: 'string' }, category: { type: 'string' }, existing_customer_data: { type: 'object' } } } } } }, responses: { '200': { description: 'Primary persona, secondary personas, LTV, acquisition channels, retention drivers', content: { 'application/json': { schema: { type: 'object', properties: { success: { type: 'boolean' }, primary_persona: { type: 'object' }, secondary_personas: { type: 'array', items: { type: 'object' } }, lifetime_value_estimate: { type: 'string' }, acquisition_channels: { type: 'array', items: { type: 'object' } }, confidence: { type: 'object' } } } } } }, '400': { description: 'Missing fields' }, '500': { description: 'Error' } } } },
      '/location-score': { post: { operationId: 'locationScore', summary: 'Score a commercial location across 7 dimensions with grade', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['address', 'category'], properties: { address: { type: 'string' }, category: { type: 'string' }, business_requirements: { type: 'object' } } } } } }, responses: { '200': { description: 'Location score, grade, 7 dimension scores, strengths, weaknesses, lease tips', content: { 'application/json': { schema: { type: 'object', properties: { success: { type: 'boolean' }, location_score: { type: 'number' }, grade: { type: 'string' }, dimension_scores: { type: 'object' }, recommended_actions_priority_order: { type: 'array', items: { type: 'string' } }, confidence: { type: 'object' } } } } } }, '400': { description: 'Missing fields' }, '500': { description: 'Error' } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Gate — checks local business readiness before proceeding', 'x-agent-callable': true, requestBody: { required: false, content: { 'application/json': { schema: { type: 'object', properties: { business_score: { type: 'number' }, reputation_score: { type: 'number' }, market_opportunity_score: { type: 'number' }, location_grade: { type: 'string' } } } } } }, responses: { '200': { description: 'Execution readiness, blocking flags, next API', content: { 'application/json': { schema: { type: 'object', properties: { execution_ready: { type: 'boolean' }, blocking_flags: { type: 'array', items: { type: 'string' } }, next_api: { type: 'string' }, recommended_action: { type: 'string' } } } } } } } } },
      '/analyze-local-business': { post: { operationId: 'analyzeLocalBusiness', summary: 'ONE-CALL: full local business intelligence workflow', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['business_name', 'location'], properties: { business_name: { type: 'string' }, location: { type: 'string' }, category: { type: 'string' }, competitors: { type: 'array', items: { type: 'string' } }, review_data: { type: 'object' } } } } } }, responses: { '200': { description: 'Full analysis: score, reputation, foot traffic, competitors, persona, location grade, recommendations', content: { 'application/json': { schema: { type: 'object', properties: { success: { type: 'boolean' }, business_score: { type: 'number' }, reputation_score: { type: 'number' }, location_grade: { type: 'string' }, recommended_actions_priority_order: { type: 'array', items: { type: 'string' } }, executive_summary: { type: 'string' }, confidence: { type: 'object' }, execution_gate: { type: 'object' } } } } } }, '400': { description: 'Missing fields' }, '500': { description: 'Error' } } } }
    }
  });
});

export default router;
