import { Router, Request, Response } from 'express';
const router = Router();

const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string', format: 'date-time' }, success: { type: 'boolean' } };
const provenance = { type: 'object', properties: { provider: { type: 'string' }, retrieved_at: { type: 'string', format: 'date-time' }, freshness_score: { type: 'number', minimum: 0, maximum: 1 } } };
const chainFields = { source_provenance: provenance, cache_ttl_seconds: { type: 'integer' }, cache_recommended: { type: 'boolean' }, recommended_next_api: { type: 'string' }, recommended_next_endpoint: { type: 'string' }, automation_safe: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'DeFi Pool Data API', version: '1.0.0', description: 'Look up DeFi liquidity pool data, calculate APY, analyze liquidity depth and assess pool risk for yield farming agents', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 300 }, pay_per_call: { lookup: '$0.002', apy: '$0.003', liquidity: '$0.003', 'execution-gate': '$0.001', 'pool-intelligence': '$0.008', risk: '$0.004', batch: '$0.015' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/defi-pool-data' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/lookup': { post: { operationId: 'lookupPool', summary: 'Look up DeFi pool data', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { pool_address: { type: 'string' }, protocol: { type: 'string' }, chain: { type: 'string' } } } } } }, responses: { '200': { description: 'Pool data', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, protocol: { type: 'string' }, tvl_usd: { type: 'number' }, volume_24h_usd: { type: 'number' }, apy_7d: { type: 'number' }, ...chainFields, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } } } } },
      '/apy': { post: { operationId: 'calculateApy', summary: 'Calculate pool APY/APR components', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { pool_address: { type: 'string' }, protocol: { type: 'string' }, chain: { type: 'string' } } } } } }, responses: { '200': { description: 'APY data', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, apy_7d: { type: 'number' }, apy_30d: { type: 'number' }, impermanent_loss_risk: { type: 'string' }, ...chainFields, privacy } } } } } } } },
      '/liquidity': { post: { operationId: 'analyzeLiquidity', summary: 'Analyze liquidity depth and slippage', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { pool_address: { type: 'string' }, protocol: { type: 'string' }, chain: { type: 'string' } } } } } }, responses: { '200': { description: 'Liquidity analysis', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, tvl_usd: { type: 'number' }, liquidity_depth: { type: 'string' }, slippage_1k: { type: 'number' }, slippage_100k: { type: 'number' }, ...chainFields, privacy } } } } } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { pool_address: { type: 'string' }, protocol: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, ...chainFields, privacy } } } } } } } },
      '/pool-intelligence': { post: { operationId: 'poolIntelligence', summary: 'ONE-CALL: data + APY + liquidity + risk + entry recommendation', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { pool_address: { type: 'string' }, protocol: { type: 'string' }, chain: { type: 'string' } } } } } }, responses: { '200': { description: 'Full pool intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, tvl_usd: { type: 'number' }, apy_7d: { type: 'number' }, risk_score: { type: 'number' }, entry_recommendation: { type: 'string' }, ...chainFields, confidence_per_section: confidence, privacy } } } } } } } },
      '/risk': { post: { operationId: 'assessPoolRisk', summary: 'Assess DeFi pool risk factors', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { pool_address: { type: 'string' }, protocol: { type: 'string' }, chain: { type: 'string' } } } } } }, responses: { '200': { description: 'Pool risk assessment', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, risk_score: { type: 'number' }, risk_level: { type: 'string' }, smart_contract_risk: { type: 'string' }, rug_pull_risk: { type: 'string' }, ...chainFields, privacy } } } } } } } },
      '/batch': { post: { operationId: 'batchPools', summary: 'Batch lookup up to 5 pools', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['pools'], properties: { pools: { type: 'array', items: { type: 'object' }, maxItems: 5 } } } } } }, responses: { '200': { description: 'Batch results', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, batch_count: { type: 'integer' }, results: { type: 'array', items: { type: 'object' } }, ...chainFields } } } } } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
