import { Router, Request, Response } from 'express';
const router = Router();
const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string' }, success: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'GitHub Repo Stats API', version: '1.0.0', description: 'GitHub repository health, contributors, activity metrics, and dependency risk analysis for autonomous agents', 'x-agent-callable': true, 'x-mcp-compatible': true },
    servers: [{ url: 'https://orbis-apis.onrender.com/github-repo-stats' }],
    paths: {
      '/repo': { post: { operationId: 'repoMetadata', summary: 'Repo metadata — stars, forks, language, license, topics, last commit', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['repo'], properties: { repo: { type: 'string' }, owner: { type: 'string' } } } } } }, responses: { '200': { description: 'Repo metadata', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, repo: { type: 'object', properties: { full_name: { type: 'string' }, stars: { type: 'number' }, forks: { type: 'number' }, language: { type: 'string' }, license: { type: 'string' }, topics: actions, open_issues: { type: 'number' } } }, health_score: { type: 'number' }, activity_grade: { type: 'string', enum: ['A', 'B', 'C', 'D', 'F'] }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing repo' }, '500': { description: 'Failed' } } } },
      '/contributors': { post: { operationId: 'contributors', summary: 'Top contributors, commit counts, activity trend, bus factor score', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['repo'], properties: { repo: { type: 'string' }, owner: { type: 'string' } } } } } }, responses: { '200': { description: 'Contributors', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, top_contributors: { type: 'array', items: { type: 'object', properties: { username: { type: 'string' }, commits: { type: 'number' }, activity_trend: { type: 'string', enum: ['increasing', 'stable', 'decreasing'] }, is_core_maintainer: { type: 'boolean' } } } }, bus_factor_score: { type: 'number' }, bus_factor_risk: { type: 'string', enum: ['high', 'medium', 'low'] }, community_health: { type: 'string', enum: ['thriving', 'healthy', 'moderate', 'low'] }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing repo' }, '500': { description: 'Failed' } } } },
      '/activity': { post: { operationId: 'repoActivity', summary: 'Commit frequency, PR velocity, issue close rate, release cadence', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['repo'], properties: { repo: { type: 'string' }, owner: { type: 'string' } } } } } }, responses: { '200': { description: 'Activity metrics', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, commit_frequency: { type: 'object', properties: { avg_per_week: { type: 'number' }, trend: { type: 'string', enum: ['increasing', 'stable', 'decreasing'] } } }, pr_velocity: { type: 'object', properties: { merge_rate_pct: { type: 'number' }, avg_review_days: { type: 'number' } } }, activity_score: { type: 'number' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing repo' }, '500': { description: 'Failed' } } } },
      '/dependencies': { post: { operationId: 'dependencies', summary: 'Package dependencies — outdated, vulnerable, license risks', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['repo'], properties: { repo: { type: 'string' }, owner: { type: 'string' }, ecosystem: { type: 'string', default: 'npm', enum: ['npm', 'pip', 'maven', 'cargo', 'go'] } } } } } }, responses: { '200': { description: 'Dependency analysis', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, dependencies: { type: 'array', items: { type: 'object', properties: { name: { type: 'string' }, version: { type: 'string' }, is_outdated: { type: 'boolean' }, vulnerability_risk: { type: 'string', enum: ['critical', 'high', 'medium', 'low', 'none'] }, license: { type: 'string' } } } }, summary: { type: 'object', properties: { total: { type: 'number' }, vulnerable: { type: 'number' }, risk_score: { type: 'number' } } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing repo' }, '500': { description: 'Failed' } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['repo'], properties: { repo: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, next_api: { type: 'string' }, blocking_flags: actions, confidence_per_section: confidence, privacy } } } } } } } },
      '/analyze': { post: { operationId: 'analyze', summary: 'ONE-CALL: full repo health — stats + contributors + activity + risk score', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['repo'], properties: { repo: { type: 'string' }, owner: { type: 'string' } } } } } }, responses: { '200': { description: 'Full repo health report', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, repo: { type: 'object' }, contributors: { type: 'object' }, activity: { type: 'object' }, dependencies: { type: 'object' }, overall_health_score: { type: 'number' }, health_grade: { type: 'string', enum: ['A', 'B', 'C', 'D', 'F'] }, risks: { type: 'array', items: { type: 'object' } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing repo' }, '500': { description: 'Failed' } } } },
    },
  });
});

export default router;
