import { Router, Request, Response } from 'express';
const router = Router();
const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string' }, success: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Resume Parser API', version: '1.0.0', description: 'Parse resumes, extract skills and experience, and score ATS compatibility for recruiting automation, talent intelligence, and HR workflow agents.', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 200, requests_per_month: 6000 }, pay_per_call: { parse: '$0.005', skills: '$0.004', experience: '$0.004', 'execution-gate': '$0.001', analyze: '$0.010' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/resume-parser' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/parse': { post: { operationId: 'parse', summary: 'Parse resume — candidate info, education, experience, skills, certifications', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['resume_url'], properties: { resume_url: { type: 'string', description: 'URL to resume PDF or plain text' } } } } } }, responses: { '200': { description: 'Parsed resume', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, resume_url: { type: 'string' }, candidate: { type: 'object', properties: { name: { type: 'string' }, email: { type: 'string' }, phone: { type: 'string' }, location: { type: 'string' }, linkedin: { type: 'string' } } }, education: { type: 'array', items: { type: 'object' } }, experience: { type: 'array', items: { type: 'object' } }, skills: { type: 'array', items: { type: 'string' } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing resume_url' }, '500': { description: 'Failed' } } } },
      '/skills': { post: { operationId: 'extractSkills', summary: 'Extract and categorize skills — technical, soft, tools, frameworks, levels', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['resume_url'], properties: { resume_url: { type: 'string' } } } } } }, responses: { '200': { description: 'Skills extracted', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, resume_url: { type: 'string' }, skills: { type: 'object', properties: { technical: { type: 'array', items: { type: 'string' } }, programming_languages: { type: 'array', items: { type: 'string' } }, soft_skills: { type: 'array', items: { type: 'string' } }, top_skills: { type: 'array', items: { type: 'string' } } } }, skill_levels: { type: 'array', items: { type: 'object' } }, skill_gaps: { type: 'array', items: { type: 'string' } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing resume_url' }, '500': { description: 'Failed' } } } },
      '/experience': { post: { operationId: 'extractExperience', summary: 'Extract and analyze work experience — career progression, tenure, red flags', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['resume_url'], properties: { resume_url: { type: 'string' } } } } } }, responses: { '200': { description: 'Experience analyzed', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, resume_url: { type: 'string' }, experience: { type: 'array', items: { type: 'object', properties: { company: { type: 'string' }, title: { type: 'string' }, seniority: { type: 'string' }, duration_months: { type: 'number' }, achievements: { type: 'array', items: { type: 'string' } } } } }, career_summary: { type: 'object', properties: { total_years: { type: 'number' }, career_progression: { type: 'string', enum: ['accelerating', 'steady', 'lateral', 'declining'] } } }, red_flags: { type: 'array', items: { type: 'string' } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing resume_url' }, '500': { description: 'Failed' } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['resume_url'], properties: { resume_url: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, next_api: { type: 'string' }, blocking_flags: actions, confidence_per_section: confidence, privacy } } } } } } } },
      '/analyze': { post: { operationId: 'analyze', summary: 'ONE-CALL: full resume analysis — parse + ATS score + hire recommendation', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['resume_url'], properties: { resume_url: { type: 'string' }, job_description: { type: 'string' } } } } } }, responses: { '200': { description: 'Full resume intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, resume_url: { type: 'string' }, candidate: { type: 'object' }, skills: { type: 'object' }, experience: { type: 'object' }, ats_score: { type: 'object', properties: { overall_score: { type: 'number' }, keyword_match_pct: { type: 'number' }, matched_keywords: { type: 'array', items: { type: 'string' } }, missing_keywords: { type: 'array', items: { type: 'string' } } } }, hire_recommendation: { type: 'string', enum: ['strong_yes', 'yes', 'maybe', 'no', 'strong_no'] }, red_flags: { type: 'array', items: { type: 'string' } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing resume_url' }, '500': { description: 'Failed' } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
