import { Router, Request, Response } from 'express';
const router = Router();

router.get('/', (req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Cold Outreach API', version: '1.0.0', description: 'AI-powered cold outreach sequence generation, personalization, subject line optimization and reply intelligence for autonomous agents.', 'x-agent-callable': true, 'x-mcp-compatible': true },
    servers: [{ url: 'https://orbis-apis.onrender.com/cold-outreach' }],
    paths: {
      '/generate-sequence': { post: { operationId: 'generateSequence', summary: 'Generate a full cold outreach sequence', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['prospect_name', 'company_name'], properties: { prospect_name: { type: 'string' }, company_name: { type: 'string' }, industry: { type: 'string' }, pain_points: { type: 'array', items: { type: 'string' } }, your_solution: { type: 'string' }, sequence_length: { type: 'number' }, tone: { type: 'string' } } } } } }, responses: { '200': { description: 'Full sequence with subjects, bodies, CTAs, send times' }, '400': { description: 'Missing required fields' }, '500': { description: 'Error' } } } },
      '/personalize-email': { post: { operationId: 'personalizeEmail', summary: 'Deep-personalize an email template for a prospect', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['template', 'prospect_data'], properties: { template: { type: 'string' }, prospect_data: { type: 'object' }, company_data: { type: 'object' }, personalization_depth: { type: 'string' } } } } } }, responses: { '200': { description: 'Personalized subject, body, relevance score, spam risk' }, '400': { description: 'Missing fields' }, '500': { description: 'Error' } } } },
      '/optimize-subject': { post: { operationId: 'optimizeSubject', summary: 'Generate 5 optimized subject line variants with open rate predictions', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['subject_line'], properties: { subject_line: { type: 'string' }, prospect_data: { type: 'object' }, industry: { type: 'string' }, goal: { type: 'string' } } } } } }, responses: { '200': { description: '5 variants with open rate predictions, spam score, power words' }, '400': { description: 'Missing subject_line' }, '500': { description: 'Error' } } } },
      '/analyze-reply': { post: { operationId: 'analyzeReply', summary: 'Analyze a prospect reply for sentiment, intent and next action', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['reply_text'], properties: { reply_text: { type: 'string' }, original_email: { type: 'object' }, prospect_data: { type: 'object' } } } } } }, responses: { '200': { description: 'Sentiment, intent, buying signals, objections, next action' }, '400': { description: 'Missing reply_text' }, '500': { description: 'Error' } } } },
      '/generate-followup': { post: { operationId: 'generateFollowup', summary: 'Generate a contextual follow-up email', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['previous_emails', 'prospect_data'], properties: { previous_emails: { type: 'array', items: { type: 'object' } }, prospect_data: { type: 'object' }, followup_number: { type: 'number' }, reason: { type: 'string' } } } } } }, responses: { '200': { description: 'Follow-up subject, body, angle, breakup flag, predicted rates' }, '400': { description: 'Missing fields' }, '500': { description: 'Error' } } } },
      '/score-email': { post: { operationId: 'scoreEmail', summary: 'Score a cold email 0-100 across 6 dimensions', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['subject', 'body'], properties: { subject: { type: 'string' }, body: { type: 'string' }, prospect_data: { type: 'object' }, goal: { type: 'string' } } } } } }, responses: { '200': { description: 'Score, grade, dimension scores, spam risk, predicted rates' }, '400': { description: 'Missing fields' }, '500': { description: 'Error' } } } },
      '/ab-test': { post: { operationId: 'abTest', summary: 'Analyze email variants for A/B testing with winner prediction', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['email_variants'], properties: { email_variants: { type: 'array', items: { type: 'object' }, minItems: 2 }, prospect_segment: { type: 'object' }, goal: { type: 'string' } } } } } }, responses: { '200': { description: 'Winner, variant analysis, predicted rates, test recommendation' }, '400': { description: 'Missing variants' }, '500': { description: 'Error' } } } },
      '/objection-handler': { post: { operationId: 'objectionHandler', summary: 'Generate objection handling responses with 3 script variants', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['objection'], properties: { objection: { type: 'string' }, context: { type: 'object' }, prospect_data: { type: 'object' }, your_solution: { type: 'object' } } } } } }, responses: { '200': { description: 'Objection type, reframe strategy, 3 response scripts, proof points' }, '400': { description: 'Missing objection' }, '500': { description: 'Error' } } } },
      '/timing-optimizer': { post: { operationId: 'timingOptimizer', summary: 'Optimize email send timing by industry and timezone', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['industry'], properties: { prospect_timezone: { type: 'string' }, industry: { type: 'string' }, email_type: { type: 'string' }, prospect_behavior: { type: 'object' } } } } } }, responses: { '200': { description: 'Best send times, cadence recommendations, industry patterns' }, '400': { description: 'Missing industry' }, '500': { description: 'Error' } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Gate — checks if email is ready to send', 'x-agent-callable': true, requestBody: { required: false, content: { 'application/json': { schema: { type: 'object', properties: { email_score: { type: 'number' }, spam_risk: { type: 'string' }, prospect_status: { type: 'string' }, has_email: { type: 'boolean' }, do_not_contact: { type: 'boolean' } } } } } }, responses: { '200': { description: 'Execution readiness, blocking flags, next API' } } } },
      '/analyze-outreach': { post: { operationId: 'analyzeOutreach', summary: 'ONE-CALL: full outreach workflow — strategy + sequence + timing + scoring', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['prospect_name', 'company_name'], properties: { prospect_name: { type: 'string' }, company_name: { type: 'string' }, industry: { type: 'string' }, pain_points: { type: 'array', items: { type: 'string' } }, your_solution: { type: 'string' }, prospect_data: { type: 'object' } } } } } }, responses: { '200': { description: 'Full outreach plan: strategy, sequence, subject variants, objection prep, timing, quality score' }, '400': { description: 'Missing fields' }, '500': { description: 'Error' } } } }
    }
  });
});

export default router;
