import { Router, Request, Response } from 'express';
const router = Router();

const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string', format: 'date-time' }, success: { type: 'boolean' } };
const provenance = { type: 'object', properties: { provider: { type: 'string' }, retrieved_at: { type: 'string', format: 'date-time' }, freshness_score: { type: 'number', minimum: 0, maximum: 1 } } };
const chainFields = { source_provenance: provenance, cache_ttl_seconds: { type: 'integer' }, cache_recommended: { type: 'boolean' }, recommended_next_api: { type: 'string' }, recommended_next_endpoint: { type: 'string' }, automation_safe: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Token Risk Lite API', version: '1.0.0', description: 'Fast token risk scores, honeypot detection, rug pull risk flags and A-F grades for wallet UIs and DeFi agent guardrails', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 500 }, pay_per_call: { assess: '$0.002', score: '$0.002', flags: '$0.002', 'execution-gate': '$0.001', 'risk-intelligence': '$0.006', compare: '$0.003', batch: '$0.015' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/token-risk-lite' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/assess': { post: { operationId: 'assessTokenRisk', summary: 'Assess token risk with honeypot and rug pull detection', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { address: { type: 'string' }, chain: { type: 'string' }, symbol: { type: 'string' } } } } } }, responses: { '200': { description: 'Risk assessment', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, risk_score: { type: 'integer' }, risk_level: { type: 'string' }, honeypot: { type: 'boolean' }, rug_pull_risk: { type: 'string' }, ...chainFields, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } } } } },
      '/score': { post: { operationId: 'scoreToken', summary: 'Get 0-100 risk score with A-F grade', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { address: { type: 'string' }, chain: { type: 'string' }, symbol: { type: 'string' } } } } } }, responses: { '200': { description: 'Risk score and grade', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, risk_score: { type: 'integer' }, grade: { type: 'string' }, score_breakdown: { type: 'object' }, ...chainFields, privacy } } } } } } } },
      '/flags': { post: { operationId: 'listRiskFlags', summary: 'List all risk flags with severity', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { address: { type: 'string' }, chain: { type: 'string' }, symbol: { type: 'string' } } } } } }, responses: { '200': { description: 'Risk flags', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, flags: { type: 'array', items: { type: 'object' } }, critical_count: { type: 'integer' }, overall_verdict: { type: 'string' }, ...chainFields, privacy } } } } } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { address: { type: 'string' }, symbol: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, ...chainFields, privacy } } } } } } } },
      '/risk-intelligence': { post: { operationId: 'riskIntelligence', summary: 'ONE-CALL: score + flags + grade + user verdict', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { address: { type: 'string' }, chain: { type: 'string' }, symbol: { type: 'string' } } } } } }, responses: { '200': { description: 'Full risk intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, risk_score: { type: 'integer' }, grade: { type: 'string' }, honeypot: { type: 'boolean' }, critical_flags: { type: 'array', items: { type: 'string' } }, user_verdict: { type: 'string' }, explanation: { type: 'string' }, ...chainFields, confidence_per_section: confidence, privacy } } } } } } } },
      '/compare': { post: { operationId: 'compareRisk', summary: 'Compare risk between two tokens', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['token_a', 'token_b'], properties: { token_a: { type: 'string' }, token_b: { type: 'string' }, chain: { type: 'string' } } } } } }, responses: { '200': { description: 'Risk comparison', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, risk_scores: { type: 'object' }, grades: { type: 'object' }, lower_risk: { type: 'string' }, ...chainFields, privacy } } } } } } } },
      '/batch': { post: { operationId: 'batchTokenRisk', summary: 'Batch score up to 10 tokens', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['tokens'], properties: { tokens: { type: 'array', items: { type: 'object' }, maxItems: 10 } } } } } }, responses: { '200': { description: 'Batch results', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, batch_count: { type: 'integer' }, results: { type: 'array', items: { type: 'object' } }, ...chainFields } } } } } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
