import { Router, Request, Response } from 'express';
const router = Router();
const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string' }, success: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'LinkedIn Profile API', version: '1.0.0', description: 'AI-powered LinkedIn profile analysis, company intelligence, and person enrichment for autonomous agents', 'x-agent-callable': true, 'x-mcp-compatible': true },
    servers: [{ url: 'https://orbis-apis.onrender.com/linkedin-profile' }],
    paths: {
      '/profile': { post: { operationId: 'profileAnalysis', summary: 'Analyze LinkedIn profile from URL or name', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { url: { type: 'string' }, name: { type: 'string' }, company: { type: 'string' } } } } } }, responses: { '200': { description: 'Profile analysis', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, profile: { type: 'object', properties: { name: { type: 'string' }, headline: { type: 'string' }, location: { type: 'string' }, connections_estimate: { type: 'string', enum: ['500+', '1000+', '5000+'] }, engagement_score: { type: 'number' }, industry: { type: 'string' }, summary_keywords: actions } }, experience: { type: 'array', items: { type: 'object', properties: { title: { type: 'string' }, company: { type: 'string' }, duration_months: { type: 'number' }, is_current: { type: 'boolean' } } } }, skills: { type: 'array', items: { type: 'object', properties: { skill: { type: 'string' }, endorsement_level: { type: 'string', enum: ['high', 'medium', 'low'] } } } }, education: { type: 'array', items: { type: 'object', properties: { degree: { type: 'string' }, institution: { type: 'string' }, year: { type: 'number' } } } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing identifier' }, '500': { description: 'Analysis failed' } } } },
      '/company': { post: { operationId: 'companyPage', summary: 'LinkedIn company page intelligence', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { company_name: { type: 'string' }, company_url: { type: 'string' } } } } } }, responses: { '200': { description: 'Company page data', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, company: { type: 'object', properties: { name: { type: 'string' }, industry: { type: 'string' }, size: { type: 'string' }, followers_estimate: { type: 'number' }, headquarters: { type: 'string' }, founded: { type: 'number' } } }, hiring_signals: { type: 'object', properties: { is_hiring: { type: 'boolean' }, open_roles_estimate: { type: 'number' }, departments_hiring: actions, growth_signal: { type: 'string', enum: ['expanding', 'stable', 'contracting'] } } }, growth_signals: { type: 'array', items: { type: 'object', properties: { signal: { type: 'string' }, strength: { type: 'string', enum: ['strong', 'moderate', 'weak'] } } } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing identifier' }, '500': { description: 'Analysis failed' } } } },
      '/enrich': { post: { operationId: 'enrichPerson', summary: 'Enrich a person with LinkedIn data', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['name'], properties: { name: { type: 'string' }, email: { type: 'string' }, company: { type: 'string' } } } } } }, responses: { '200': { description: 'Enriched profile', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, enriched_profile: { type: 'object', properties: { name: { type: 'string' }, title: { type: 'string' }, seniority: { type: 'string', enum: ['c-suite', 'vp', 'director', 'manager', 'individual_contributor'] }, department: { type: 'string' } } }, contact_signals: { type: 'object', properties: { best_channel: { type: 'string', enum: ['linkedin', 'email', 'phone'] }, response_likelihood: { type: 'string', enum: ['high', 'medium', 'low'] }, email_pattern_guess: { type: 'string' } } }, enrichment_confidence: { type: 'number' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing name' }, '500': { description: 'Enrichment failed' } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { name: { type: 'string' }, url: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, next_api: { type: 'string' }, blocking_flags: actions, confidence_per_section: confidence, privacy } } } } } } } },
      '/lookup': { post: { operationId: 'lookup', summary: 'ONE-CALL: enrich person + company in one shot', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { name: { type: 'string' }, email: { type: 'string' }, company: { type: 'string' } } } } } }, responses: { '200': { description: 'Full LinkedIn enrichment', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, person: { type: 'object', properties: { name: { type: 'string' }, title: { type: 'string' }, seniority: { type: 'string' }, headline: { type: 'string' } } }, company: { type: 'object', properties: { name: { type: 'string' }, industry: { type: 'string' }, size: { type: 'string' } } }, engagement_score: { type: 'number' }, fit_score: { type: 'number' }, outreach_ready: { type: 'boolean' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing identifier' }, '500': { description: 'Lookup failed' } } } },
    },
  });
});

export default router;
