import { Router, Request, Response } from 'express';
const router = Router();
const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string' }, success: { type: 'boolean' } };
const addressInput = { type: 'object', required: ['address'], properties: { address: { type: 'string' }, chain: { type: 'string', default: 'ethereum', enum: ['ethereum', 'bitcoin', 'solana', 'polygon', 'bsc', 'arbitrum', 'base'] } } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Address Risk API', version: '1.0.0', description: 'Blockchain address risk scoring, sanctions checking, entity labeling, and cluster analysis for autonomous agents', 'x-agent-callable': true, 'x-mcp-compatible': true },
    servers: [{ url: 'https://orbis-apis.onrender.com/address-risk' }],
    paths: {
      '/address-risk': { post: { operationId: 'addressRisk', summary: 'Score blockchain address risk — risk level, risk factors, entity type, transaction pattern signals', requestBody: { required: true, content: { 'application/json': { schema: addressInput } } }, responses: { '200': { description: 'Address risk assessment', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, address: { type: 'string' }, chain: { type: 'string' }, risk_level: { type: 'string', enum: ['critical', 'high', 'medium', 'low', 'minimal'] }, risk_score: { type: 'number' }, entity_type: { type: 'string', enum: ['exchange', 'mixer', 'darknet', 'defi_protocol', 'wallet', 'contract', 'unknown'] }, risk_factors: { type: 'array', items: { type: 'object', properties: { factor: { type: 'string' }, severity: { type: 'string', enum: ['critical', 'high', 'medium', 'low'] } } } }, allow_or_block: { type: 'string', enum: ['allow', 'review', 'block'] }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing address' }, '500': { description: 'Failed' } } } },
      '/sanctions': { post: { operationId: 'sanctionsCheck', summary: 'Check address against OFAC, EU, UN sanctions lists — match status, entity name, program', requestBody: { required: true, content: { 'application/json': { schema: addressInput } } }, responses: { '200': { description: 'Sanctions check result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, address: { type: 'string' }, is_sanctioned: { type: 'boolean' }, match_confidence: { type: 'number' }, sanctions_matches: { type: 'array', items: { type: 'object', properties: { list: { type: 'string', enum: ['OFAC', 'EU', 'UN', 'OFSI', 'other'] }, entity_name: { type: 'string' }, program: { type: 'string' }, match_type: { type: 'string', enum: ['exact', 'fuzzy', 'indirect'] } } } }, verdict: { type: 'string', enum: ['clear', 'sanctioned', 'indirect_exposure', 'review_required'] }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing address' }, '500': { description: 'Failed' } } } },
      '/labels': { post: { operationId: 'addressLabels', summary: 'Get known labels — exchange, mixer, darknet, defi protocol, whale', requestBody: { required: true, content: { 'application/json': { schema: addressInput } } }, responses: { '200': { description: 'Address labels', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, address: { type: 'string' }, labels: { type: 'array', items: { type: 'object', properties: { label: { type: 'string' }, category: { type: 'string', enum: ['exchange', 'mixer', 'darknet', 'defi_protocol', 'whale', 'nft', 'dao', 'bridge', 'other'] }, confidence: { type: 'number' } } } }, primary_label: { type: 'string' }, is_contract: { type: 'boolean' }, is_whale: { type: 'boolean' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing address' }, '500': { description: 'Failed' } } } },
      '/cluster': { post: { operationId: 'clusterAddresses', summary: 'Cluster addresses likely belonging to the same entity — cluster score, common counterparties', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['addresses'], properties: { addresses: { type: 'array', items: { type: 'string' }, maxItems: 10 }, chain: { type: 'string', default: 'ethereum' } } } } } }, responses: { '200': { description: 'Cluster analysis', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, cluster_groups: { type: 'array', items: { type: 'object', properties: { cluster_id: { type: 'string' }, addresses: actions, cluster_score: { type: 'number' }, entity_hypothesis: { type: 'string' }, common_counterparties: actions } } }, total_addresses: { type: 'number' }, clustered_count: { type: 'number' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing addresses' }, '500': { description: 'Failed' } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: addressInput } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, next_api: { type: 'string' }, blocking_flags: actions, confidence_per_section: confidence, privacy } } } } } } } },
      '/assess': { post: { operationId: 'assess', summary: 'ONE-CALL: full address risk — risk score + sanctions + labels + recommendations', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: addressInput } } }, responses: { '200': { description: 'Full address risk assessment', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, address: { type: 'string' }, chain: { type: 'string' }, risk_score: { type: 'number' }, risk_level: { type: 'string', enum: ['critical', 'high', 'medium', 'low', 'minimal'] }, is_sanctioned: { type: 'boolean' }, labels: { type: 'array', items: { type: 'object' } }, allow_or_block: { type: 'string', enum: ['allow', 'review', 'block'] }, compliance_recommendation: { type: 'string' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing address' }, '500': { description: 'Failed' } } } },
    },
  });
});

export default router;
