// Curated, deduplicated word list for diceware-style passphrase generation.
// Short, common, unambiguous English words. The effective list size is computed
// from WORDS.length at runtime, so entropy claims stay honest regardless of the
// exact count (duplicates are removed by the Set below).
const RAW = [
  'able', 'acid', 'aged', 'also', 'area', 'army', 'away', 'baby', 'back', 'ball',
  'band', 'bank', 'base', 'bath', 'bean', 'bear', 'beat', 'beds', 'beer', 'bell',
  'belt', 'best', 'bird', 'bite', 'blue', 'boat', 'body', 'bold', 'bone', 'book',
  'boot', 'born', 'boss', 'both', 'bowl', 'bulk', 'burn', 'bush', 'busy', 'cake',
  'call', 'calm', 'came', 'camp', 'card', 'care', 'case', 'cash', 'cast', 'cell',
  'chat', 'chip', 'city', 'club', 'coal', 'coat', 'code', 'cold', 'come', 'cook',
  'cool', 'cope', 'copy', 'corn', 'cost', 'crew', 'crop', 'dark', 'data', 'date',
  'dawn', 'days', 'dead', 'deal', 'dear', 'debt', 'deep', 'deck', 'deny', 'desk',
  'dial', 'diet', 'dirt', 'dish', 'dock', 'does', 'door', 'dose', 'down', 'draw',
  'drew', 'drop', 'drum', 'dual', 'duck', 'dust', 'duty', 'each', 'earn', 'ease',
  'east', 'easy', 'edge', 'else', 'even', 'ever', 'evil', 'exit', 'face', 'fact',
  'fade', 'fail', 'fair', 'fall', 'farm', 'fast', 'fate', 'fear', 'feed', 'feel',
  'feet', 'fell', 'file', 'fill', 'film', 'find', 'fine', 'fire', 'firm', 'fish',
  'fist', 'five', 'flag', 'flat', 'flee', 'flow', 'fold', 'folk', 'food', 'foot',
  'ford', 'form', 'fort', 'four', 'free', 'frog', 'fuel', 'full', 'fund', 'gain',
  'game', 'gate', 'gave', 'gear', 'gift', 'girl', 'give', 'glad', 'goal', 'goat',
  'goes', 'gold', 'golf', 'gone', 'good', 'gray', 'grew', 'grid', 'grim', 'grip',
  'grow', 'gulf', 'hair', 'half', 'hall', 'hand', 'hang', 'hard', 'harm', 'hat',
  'have', 'hawk', 'head', 'heal', 'heap', 'hear', 'heat', 'held', 'hell', 'helm',
  'help', 'herb', 'herd', 'hero', 'hide', 'high', 'hill', 'hint', 'hire', 'hold',
  'hole', 'holy', 'home', 'hood', 'hook', 'hope', 'horn', 'host', 'hour', 'huge',
  'hunt', 'hurt', 'icon', 'idea', 'inch', 'into', 'iron', 'isle', 'item', 'jade',
  'jail', 'jazz', 'jeep', 'join', 'joke', 'jump', 'jury', 'just', 'keen', 'keep',
  'kept', 'kick', 'kind', 'king', 'kiss', 'kite', 'knee', 'knew', 'knot', 'know',
  'lace', 'lack', 'lake', 'lamb', 'lamp', 'land', 'lane', 'last', 'late', 'lawn',
  'lazy', 'lead', 'leaf', 'leak', 'lean', 'left', 'lend', 'lens', 'less', 'life',
  'lift', 'like', 'lime', 'line', 'link', 'lion', 'list', 'live', 'load', 'loan',
  'lock', 'loft', 'logic', 'lone', 'long', 'look', 'loop', 'lord', 'lose', 'loss',
  'lost', 'loud', 'love', 'luck', 'lump', 'lung', 'made', 'mail', 'main', 'make',
  'male', 'mall', 'many', 'maps', 'mark', 'mask', 'mass', 'mate', 'math', 'meal',
  'mean', 'meat', 'meet', 'melt', 'menu', 'mere', 'mesh', 'mild', 'mile', 'milk',
  'mill', 'mind', 'mine', 'mint', 'mist', 'moon', 'more', 'moss', 'most', 'moth',
  'move', 'much', 'mule', 'mush', 'must', 'nail', 'name', 'navy', 'near', 'neat',
  'neck', 'need', 'nest', 'news', 'next', 'nice', 'nine', 'node', 'none', 'noon',
  'norm', 'nose', 'note', 'noun', 'oath', 'obey', 'odds', 'oily', 'okay', 'once',
  'only', 'onto', 'open', 'oral', 'oven', 'over', 'pace', 'pack', 'page', 'paid',
  'pain', 'pair', 'palm', 'park', 'part', 'pass', 'past', 'path', 'peak', 'pear',
  'peer', 'pile', 'pink', 'pint', 'pipe', 'plan', 'play', 'plot', 'plug', 'plus',
  'poem', 'poet', 'pole', 'poll', 'pond', 'pool', 'poor', 'pork', 'port', 'pose',
  'post', 'pour', 'pray', 'prep', 'prey', 'pull', 'pump', 'pure', 'push', 'quit',
  'quiz', 'race', 'rack', 'raft', 'rage', 'raid', 'rail', 'rain', 'rake', 'rank',
  'rare', 'rate', 'read', 'real', 'reef', 'rely', 'rent', 'rest', 'rice', 'rich',
  'ride', 'ring', 'riot', 'rise', 'risk', 'road', 'roar', 'rock', 'role', 'roll',
  'roof', 'room', 'root', 'rope', 'rose', 'rosy', 'ruby', 'rule', 'rush', 'rust',
  'safe', 'sage', 'said', 'sail', 'salt', 'same', 'sand', 'save', 'scan', 'seal',
  'seat', 'seed', 'seek', 'seem', 'seen', 'self', 'sell', 'send', 'shed', 'ship',
  'shoe', 'shop', 'shot', 'show', 'shut', 'sick', 'side', 'sign', 'silk', 'sing',
  'sink', 'site', 'size', 'skin', 'skip', 'slab', 'slam', 'slid', 'slim', 'slip',
  'slot', 'slow', 'snap', 'snow', 'soap', 'sock', 'soft', 'soil', 'sold', 'sole',
  'some', 'song', 'soon', 'sort', 'soul', 'soup', 'sour', 'spin', 'spot', 'star',
  'stay', 'stem', 'step', 'stir', 'stop', 'such', 'suit', 'sure', 'surf', 'swap',
  'swim', 'tail', 'take', 'tale', 'talk', 'tall', 'tank', 'tape', 'task', 'team',
  'tear', 'tell', 'tend', 'tent', 'term', 'test', 'text', 'than', 'that', 'thaw',
  'them', 'then', 'thin', 'this', 'thus', 'tide', 'tidy', 'tile', 'time', 'tiny',
  'tire', 'toad', 'toll', 'tone', 'took', 'tool', 'torn', 'tour', 'town', 'trap',
  'tray', 'tree', 'trim', 'trip', 'true', 'tube', 'tuna', 'tune', 'turn', 'twin',
  'type', 'ugly', 'undo', 'unit', 'upon', 'urge', 'used', 'user', 'vain', 'vary',
  'vast', 'veal', 'veil', 'vent', 'verb', 'very', 'vest', 'view', 'vine', 'visa',
  'void', 'vote', 'wade', 'wage', 'wait', 'wake', 'walk', 'wall', 'want', 'ward',
  'warm', 'warn', 'wash', 'wave', 'weak', 'wear', 'week', 'well', 'went', 'were',
  'west', 'what', 'when', 'whip', 'whom', 'wide', 'wife', 'wild', 'will', 'wind',
  'wine', 'wing', 'wipe', 'wire', 'wise', 'wish', 'wolf', 'wood', 'wool', 'word',
  'wore', 'work', 'worm', 'wrap', 'yard', 'yarn', 'year', 'yoga', 'zero', 'zone',
];

export const WORDS: string[] = [...new Set(RAW)];
