import { Router, Request, Response } from 'express';
const router = Router();

const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string', format: 'date-time' }, success: { type: 'boolean' } };
const provenance = { type: 'object', properties: { provider: { type: 'string' }, retrieved_at: { type: 'string', format: 'date-time' }, freshness_score: { type: 'number', minimum: 0, maximum: 1 } } };
const chainFields = { source_provenance: provenance, cache_ttl_seconds: { type: 'integer' }, cache_recommended: { type: 'boolean' }, recommended_next_api: { type: 'string' }, recommended_next_endpoint: { type: 'string' }, automation_safe: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Decision Maker Fit API', version: '1.0.0', description: 'Score decision maker fit, build buyer personas, suggest outreach angles and detect buying signals for B2B sales agents', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 200 }, pay_per_call: { score: '$0.004', persona: '$0.005', 'outreach-angle': '$0.005', 'execution-gate': '$0.001', 'fit-intelligence': '$0.012', 'buying-signals': '$0.005', batch: '$0.020' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/decision-maker-fit' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/score': { post: { operationId: 'scoreFit', summary: 'Score decision maker fit for your ICP', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['name'], properties: { name: { type: 'string' }, title: { type: 'string' }, company: { type: 'string' }, product_description: { type: 'string' }, target_icp: { type: 'string' } } } } } }, responses: { '200': { description: 'Fit score', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, fit_score: { type: 'number' }, authority_score: { type: 'number' }, role_alignment: { type: 'string' }, icp_match: { type: 'string' }, ...chainFields, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } } } } },
      '/persona': { post: { operationId: 'buildPersona', summary: 'Build buyer persona for decision maker', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['name'], properties: { name: { type: 'string' }, title: { type: 'string' }, company: { type: 'string' }, industry: { type: 'string' } } } } } }, responses: { '200': { description: 'Buyer persona', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, archetype: { type: 'string' }, primary_goals: { type: 'array', items: { type: 'string' } }, pain_points: { type: 'array', items: { type: 'string' } }, ...chainFields, privacy } } } } } } } },
      '/outreach-angle': { post: { operationId: 'getOutreachAngle', summary: 'Suggest best outreach angle and messaging', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['name'], properties: { name: { type: 'string' }, title: { type: 'string' }, company: { type: 'string' }, product_description: { type: 'string' } } } } } }, responses: { '200': { description: 'Outreach strategy', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, primary_angle: { type: 'string' }, subject_line_ideas: { type: 'array', items: { type: 'string' } }, value_proposition_framing: { type: 'string' }, ...chainFields, privacy } } } } } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['name'], properties: { name: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, ...chainFields, privacy } } } } } } } },
      '/fit-intelligence': { post: { operationId: 'fitIntelligence', summary: 'ONE-CALL: fit score + persona + outreach angle + buying signals', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['name'], properties: { name: { type: 'string' }, title: { type: 'string' }, company: { type: 'string' }, product_description: { type: 'string' }, target_icp: { type: 'string' } } } } } }, responses: { '200': { description: 'Full fit intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, fit_score: { type: 'number' }, persona: { type: 'string' }, outreach_angle: { type: 'string' }, recommended_action: { type: 'string' }, ...chainFields, confidence_per_section: confidence, privacy } } } } } } } },
      '/buying-signals': { post: { operationId: 'detectBuyingSignals', summary: 'Detect in-market buying signals', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['name'], properties: { name: { type: 'string' }, company: { type: 'string' }, industry: { type: 'string' } } } } } }, responses: { '200': { description: 'Buying signals', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, buying_signal_score: { type: 'number' }, in_market: { type: 'string' }, signals: { type: 'array', items: { type: 'object' } }, ...chainFields, privacy } } } } } } } },
      '/batch': { post: { operationId: 'batchLeads', summary: 'Batch score up to 5 leads', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['leads'], properties: { leads: { type: 'array', items: { type: 'object' }, maxItems: 5 } } } } } }, responses: { '200': { description: 'Batch results', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, batch_count: { type: 'integer' }, results: { type: 'array', items: { type: 'object' } }, ...chainFields } } } } } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
