import { Router, Request, Response } from 'express';
const router = Router();
const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string' }, success: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Email Finder API', version: '1.0.0', description: 'Find, verify, and bulk-process professional emails for autonomous agents', 'x-agent-callable': true, 'x-mcp-compatible': true },
    servers: [{ url: 'https://orbis-apis.onrender.com/email-finder' }],
    paths: {
      '/find-email': { post: { operationId: 'findEmail', summary: 'Find professional email for a person at a company', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['last_name'], properties: { first_name: { type: 'string' }, last_name: { type: 'string' }, company: { type: 'string' }, domain: { type: 'string' } } } } } }, responses: { '200': { description: 'Email candidates with confidence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, email_candidates: { type: 'array', items: { type: 'object', properties: { email: { type: 'string' }, pattern: { type: 'string' }, confidence: { type: 'number' }, is_primary: { type: 'boolean' } } } }, deliverability_signal: { type: 'string', enum: ['valid', 'risky', 'invalid', 'unknown'] }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing fields' }, '500': { description: 'Failed' } } } },
      '/verify-email': { post: { operationId: 'verifyEmail', summary: 'Verify if email is valid, deliverable, disposable', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['email'], properties: { email: { type: 'string' } } } } } }, responses: { '200': { description: 'Verification result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, email: { type: 'string' }, verification: { type: 'object', properties: { is_valid_format: { type: 'boolean' }, is_deliverable: { type: 'boolean' }, is_disposable: { type: 'boolean' }, is_role_based: { type: 'boolean' }, catches_all: { type: 'boolean' } } }, risk_score: { type: 'number' }, risk_level: { type: 'string', enum: ['low', 'medium', 'high'] }, verdict: { type: 'string', enum: ['valid', 'risky', 'invalid', 'unknown'] }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing email' }, '500': { description: 'Failed' } } } },
      '/domain-search': { post: { operationId: 'domainSearch', summary: 'Find all emails at a domain with role-based groupings', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['domain'], properties: { domain: { type: 'string' } } } } } }, responses: { '200': { description: 'Domain email map', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, domain: { type: 'string' }, email_pattern: { type: 'string' }, role_based_emails: { type: 'array', items: { type: 'object', properties: { email: { type: 'string' }, role: { type: 'string' }, confidence: { type: 'number' } } } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing domain' }, '500': { description: 'Failed' } } } },
      '/bulk': { post: { operationId: 'bulkFind', summary: 'Bulk find/verify up to 20 emails', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['contacts'], properties: { contacts: { type: 'array', maxItems: 20, items: { type: 'object', properties: { first_name: { type: 'string' }, last_name: { type: 'string' }, company: { type: 'string' }, domain: { type: 'string' } } } } } } } } }, responses: { '200': { description: 'Bulk results', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, results: { type: 'array', items: { type: 'object', properties: { name: { type: 'string' }, email: { type: 'string' }, confidence: { type: 'number' }, verdict: { type: 'string' } } } }, summary: { type: 'object', properties: { total: { type: 'number' }, found: { type: 'number' }, verified: { type: 'number' } } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing contacts' }, '500': { description: 'Failed' } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { email: { type: 'string' }, domain: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, next_api: { type: 'string' }, blocking_flags: actions, confidence_per_section: confidence, privacy } } } } } } } },
      '/find': { post: { operationId: 'find', summary: 'ONE-CALL: find + verify in one shot', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { first_name: { type: 'string' }, last_name: { type: 'string' }, company: { type: 'string' }, domain: { type: 'string' } } } } } }, responses: { '200': { description: 'Found and verified email', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, email: { type: 'string' }, confidence: { type: 'number' }, verification: { type: 'object', properties: { is_deliverable: { type: 'boolean' }, verdict: { type: 'string' } } }, outreach_ready: { type: 'boolean' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing fields' }, '500': { description: 'Failed' } } } },
    },
  });
});

export default router;
