import { Router, Request, Response } from 'express';
export const openapiRouter = Router();
const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
openapiRouter.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Document Intelligence API', version: '2.0.0', description: 'Extract structured data from documents with field-level confidence scoring. Supports PDFs, contracts, invoices, forms and unstructured text.', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 100, requests_per_month: 3000 }, pay_per_call: { extract: '$0.008', batch: '$0.020', job_status: '$0.001' }, high_volume: { extract: '$0.005', batch: '$0.012' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/document-intelligence' }],
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/': { post: { operationId: 'extractDocument', summary: 'Extract structured data from a document with field-level confidence scoring', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['document'], properties: { document: { type: 'string', description: 'Base64 encoded document or URL' }, document_type: { type: 'string', enum: ['pdf', 'contract', 'invoice', 'form', 'text', 'auto'] }, extraction_schema: { type: 'object' }, language: { type: 'string' } } } } } }, responses: { '200': { description: 'Extracted data', content: { 'application/json': { schema: { type: 'object', properties: { document_id: { type: 'string' }, document_type: { type: 'string' }, extracted_fields: { type: 'object' }, field_confidence: { type: 'object', additionalProperties: { type: 'number' } }, overall_confidence: { type: 'number', minimum: 0, maximum: 1 }, page_count: { type: 'number' }, language_detected: { type: 'string' }, extraction_warnings: actions, extraction_method: { type: 'string', enum: ['ocr', 'native_text', 'hybrid'] }, citations: { type: 'array', items: { type: 'object', properties: { text: { type: 'string' }, page: { type: 'number' }, confidence: { type: 'number' } } } }, redactions_applied: { type: 'array', items: { type: 'string' } }, chain_to: { type: 'array', items: { type: 'string' } }, recommended_actions_priority_order: { type: 'array', items: { type: 'string' } }, confidence_per_section: confidence, privacy } } } } }, '400': { description: 'Missing document' }, '500': { description: 'Extraction failed' } } } },
      '/batch': { post: { operationId: 'extractBatch', summary: 'Batch extract structured data from multiple documents', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['documents'], properties: { documents: { type: 'array', items: { type: 'object', properties: { document: { type: 'string' }, document_type: { type: 'string' } } }, maxItems: 10 }, extraction_schema: { type: 'object' } } } } } }, responses: { '200': { description: 'Batch job created', content: { 'application/json': { schema: { type: 'object', properties: { job_id: { type: 'string' }, status: { type: 'string', enum: ['queued', 'processing'] }, total_documents: { type: 'number' }, estimated_completion_ms: { type: 'number' }, privacy } } } } }, '400': { description: 'Missing documents' }, '500': { description: 'Batch failed' } } } },
      '/jobs/:jobId': { get: { operationId: 'getJobStatus', summary: 'Get extraction job status and results', parameters: [{ name: 'jobId', in: 'path', required: true, schema: { type: 'string' } }], responses: { '200': { description: 'Job status', content: { 'application/json': { schema: { type: 'object', properties: { job_id: { type: 'string' }, status: { type: 'string', enum: ['queued', 'processing', 'completed', 'failed'] }, progress_pct: { type: 'number', minimum: 0, maximum: 100 }, results: { type: 'array', items: { type: 'object' } }, completed_at: { type: 'string', format: 'date-time', nullable: true }, privacy } } } } }, '404': { description: 'Job not found' }, '500': { description: 'Status check failed' } } } }
    }
  });
});
