import { Router, Request, Response } from 'express';
const router = Router();

const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string', format: 'date-time' }, success: { type: 'boolean' } };
const provenance = { type: 'object', properties: { provider: { type: 'string' }, retrieved_at: { type: 'string', format: 'date-time' }, freshness_score: { type: 'number', minimum: 0, maximum: 1 } } };
const chainFields = { source_provenance: provenance, cache_ttl_seconds: { type: 'integer' }, cache_recommended: { type: 'boolean' }, recommended_next_api: { type: 'string' }, recommended_next_endpoint: { type: 'string' }, automation_safe: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'CRM Contact Intelligence API', version: '1.0.0', description: 'Enrich, score, segment CRM contacts and detect buying intent for B2B sales automation agents', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 200 }, pay_per_call: { enrich: '$0.005', score: '$0.004', segment: '$0.004', 'execution-gate': '$0.001', 'contact-intelligence': '$0.012', 'intent-signals': '$0.005', batch: '$0.020' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/crm-contact-intelligence' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/enrich': { post: { operationId: 'enrichContact', summary: 'Enrich CRM contact with company and role data', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['email'], properties: { email: { type: 'string' }, name: { type: 'string' }, company: { type: 'string' } } } } } }, responses: { '200': { description: 'Enriched contact', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, email: { type: 'string' }, name: { type: 'string' }, title: { type: 'string' }, seniority: { type: 'string' }, ...chainFields, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } } } } },
      '/score': { post: { operationId: 'scoreContact', summary: 'Score contact for outreach priority', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['email'], properties: { email: { type: 'string' }, name: { type: 'string' }, company: { type: 'string' }, title: { type: 'string' }, use_case: { type: 'string' } } } } } }, responses: { '200': { description: 'Contact score', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, outreach_score: { type: 'number' }, fit_score: { type: 'number' }, recommended_action: { type: 'string' }, ...chainFields, privacy } } } } } } } },
      '/segment': { post: { operationId: 'segmentContact', summary: 'Segment contact into persona and buyer stage', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['email'], properties: { email: { type: 'string' }, name: { type: 'string' }, company: { type: 'string' }, title: { type: 'string' } } } } } }, responses: { '200': { description: 'Segment result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, persona: { type: 'string' }, buyer_stage: { type: 'string' }, engagement_tier: { type: 'string' }, ...chainFields, privacy } } } } } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['email'], properties: { email: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, ...chainFields, privacy } } } } } } } },
      '/contact-intelligence': { post: { operationId: 'contactIntelligence', summary: 'ONE-CALL: enrich + score + segment + intent', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['email'], properties: { email: { type: 'string' }, name: { type: 'string' }, company: { type: 'string' }, title: { type: 'string' }, use_case: { type: 'string' } } } } } }, responses: { '200': { description: 'Full contact intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, enriched_profile: { type: 'object' }, outreach_score: { type: 'number' }, persona: { type: 'string' }, recommended_action: { type: 'string' }, ...chainFields, confidence_per_section: confidence, privacy } } } } } } } },
      '/intent-signals': { post: { operationId: 'detectIntentSignals', summary: 'Detect buying intent signals for contact', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['email'], properties: { email: { type: 'string' }, company: { type: 'string' }, industry: { type: 'string' } } } } } }, responses: { '200': { description: 'Intent signals', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, intent_score: { type: 'number' }, intent_level: { type: 'string' }, signals: { type: 'array', items: { type: 'object' } }, ...chainFields, privacy } } } } } } } },
      '/batch': { post: { operationId: 'batchContacts', summary: 'Batch score up to 5 contacts', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['contacts'], properties: { contacts: { type: 'array', items: { type: 'object' }, maxItems: 5 } } } } } }, responses: { '200': { description: 'Batch results', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, batch_count: { type: 'integer' }, results: { type: 'array', items: { type: 'object' } }, ...chainFields } } } } } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
