import { Router, Request, Response } from 'express';
const router = Router();
const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string' }, success: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Amazon Product Scraper API', version: '1.0.0', description: 'Extract Amazon product details, reviews, and price history for market research, competitive pricing, and product intelligence agent workflows.', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 200, requests_per_month: 6000 }, pay_per_call: { product: '$0.004', reviews: '$0.005', 'price-history': '$0.004', 'execution-gate': '$0.001', analyze: '$0.010' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/amazon-product' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/product': { post: { operationId: 'getProduct', summary: 'Extract Amazon product details — title, brand, pricing, BSR, stock status', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['asin'], properties: { asin: { type: 'string', description: 'Amazon Standard Identification Number' } } } } } }, responses: { '200': { description: 'Product details', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, asin: { type: 'string' }, product: { type: 'object', properties: { title: { type: 'string' }, brand: { type: 'string' }, category: { type: 'string' }, bullet_points: { type: 'array', items: { type: 'string' } }, bsr: { type: 'array', items: { type: 'object' } } } }, pricing: { type: 'object', properties: { current_price: { type: 'number' }, list_price: { type: 'number' }, discount_pct: { type: 'number' }, prime_eligible: { type: 'boolean' }, in_stock: { type: 'boolean' } } }, ratings: { type: 'object' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing asin' }, '500': { description: 'Failed' } } } },
      '/reviews': { post: { operationId: 'getReviews', summary: 'Extract Amazon product reviews — sentiment, themes, rating distribution', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['asin'], properties: { asin: { type: 'string' }, limit: { type: 'integer', default: 10 } } } } } }, responses: { '200': { description: 'Reviews data', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, asin: { type: 'string' }, reviews: { type: 'array', items: { type: 'object', properties: { review_id: { type: 'string' }, rating: { type: 'number' }, title: { type: 'string' }, body: { type: 'string' }, sentiment: { type: 'string', enum: ['positive', 'neutral', 'negative'] }, verified_purchase: { type: 'boolean' } } } }, review_summary: { type: 'object' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing asin' }, '500': { description: 'Failed' } } } },
      '/price-history': { post: { operationId: 'priceHistory', summary: 'Amazon price history — min, max, trend, deal score, buy recommendation', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['asin'], properties: { asin: { type: 'string' } } } } } }, responses: { '200': { description: 'Price history', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, asin: { type: 'string' }, current_price: { type: 'number' }, price_history: { type: 'array', items: { type: 'object' } }, price_stats: { type: 'object', properties: { min_price: { type: 'number' }, max_price: { type: 'number' }, price_trend: { type: 'string', enum: ['falling', 'rising', 'stable'] }, deal_score: { type: 'number' } } }, buy_recommendation: { type: 'string', enum: ['buy_now', 'wait', 'hold'] }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing asin' }, '500': { description: 'Failed' } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['asin'], properties: { asin: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, next_api: { type: 'string' }, blocking_flags: actions, confidence_per_section: confidence, privacy } } } } } } } },
      '/analyze': { post: { operationId: 'analyze', summary: 'ONE-CALL: full Amazon product intelligence — product + pricing + reviews + market position', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['asin'], properties: { asin: { type: 'string' } } } } } }, responses: { '200': { description: 'Full Amazon product intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, asin: { type: 'string' }, product: { type: 'object' }, pricing: { type: 'object' }, price_history: { type: 'object' }, reviews: { type: 'object' }, market_position: { type: 'object' }, buy_recommendation: { type: 'string' }, investment_grade: { type: 'string', enum: ['A', 'B', 'C', 'D', 'F'] }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing asin' }, '500': { description: 'Failed' } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
