import { Router, Request, Response } from 'express';
const router = Router();
const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string' }, success: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Price Monitor API', version: '1.0.0', description: 'Extract product prices from URLs, track price changes over time, and compare prices across sources for procurement, retail, and competitive pricing workflows.', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 200, requests_per_month: 6000 }, pay_per_call: { 'extract-price': '$0.003', track: '$0.004', compare: '$0.008', 'execution-gate': '$0.001', analyze: '$0.008' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/price-monitor' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/extract-price': { post: { operationId: 'extractPrice', summary: 'Extract product price from URL — amount, currency, discount, stock status', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['url'], properties: { url: { type: 'string' } } } } } }, responses: { '200': { description: 'Price extracted', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, url: { type: 'string' }, price: { type: 'object', properties: { amount: { type: 'number' }, currency: { type: 'string' }, formatted: { type: 'string' }, discount_pct: { type: 'number' }, in_stock: { type: 'boolean' } } }, product: { type: 'object' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing url' }, '500': { description: 'Failed' } } } },
      '/track': { post: { operationId: 'track', summary: 'Track price history for a product — min, max, avg, trend, buy recommendation', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['url', 'product_name'], properties: { url: { type: 'string' }, product_name: { type: 'string' } } } } } }, responses: { '200': { description: 'Price tracking data', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, url: { type: 'string' }, product_name: { type: 'string' }, current_price: { type: 'object' }, price_history: { type: 'array', items: { type: 'object' } }, price_stats: { type: 'object', properties: { min_price: { type: 'number' }, max_price: { type: 'number' }, avg_price: { type: 'number' }, price_trend: { type: 'string', enum: ['falling', 'rising', 'stable'] } } }, buy_recommendation: { type: 'string', enum: ['buy_now', 'wait', 'hold'] }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing url or product_name' }, '500': { description: 'Failed' } } } },
      '/compare': { post: { operationId: 'compare', summary: 'Compare prices across up to 10 URLs — best deal, price spread', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['urls'], properties: { urls: { type: 'array', items: { type: 'string' }, maxItems: 10 } } } } } }, responses: { '200': { description: 'Price comparison', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, comparison: { type: 'array', items: { type: 'object', properties: { url: { type: 'string' }, seller: { type: 'string' }, price: { type: 'number' }, total_cost: { type: 'number' }, in_stock: { type: 'boolean' } } } }, best_deal: { type: 'object' }, price_range: { type: 'object' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing urls' }, '500': { description: 'Failed' } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['url'], properties: { url: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, next_api: { type: 'string' }, blocking_flags: actions, confidence_per_section: confidence, privacy } } } } } } } },
      '/analyze': { post: { operationId: 'analyze', summary: 'ONE-CALL: full price intelligence — extract + history + competitor prices + recommendation', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['url'], properties: { url: { type: 'string' } } } } } }, responses: { '200': { description: 'Full price intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, url: { type: 'string' }, product: { type: 'object' }, current_price: { type: 'object' }, price_history: { type: 'array', items: { type: 'object' } }, competitor_prices: { type: 'array', items: { type: 'object' } }, buy_recommendation: { type: 'string' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing url' }, '500': { description: 'Failed' } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
