import { Router, Request, Response } from 'express';
const router = Router();
const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string' }, success: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Favicon API', version: '1.0.0', description: 'Fetch, detect, and analyze favicons from any URL or domain with batch support and format metadata.', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 200, requests_per_month: 6000 }, pay_per_call: { favicon: '$0.001', batch: '$0.008', metadata: '$0.002', 'execution-gate': '$0.001', detect: '$0.003' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/favicon' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/favicon': { post: { operationId: 'getFavicon', summary: 'Fetch favicon URL, format, and accessibility for a URL', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['url'], properties: { url: { type: 'string' } } } } } }, responses: { '200': { description: 'Favicon data', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, url: { type: 'string' }, favicon: { type: 'object', properties: { url: { type: 'string' }, format: { type: 'string' }, size: { type: 'string' }, accessible: { type: 'boolean' }, content_type: { type: 'string' } } }, source_method: { type: 'string' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing url' }, '500': { description: 'Failed' } } } },
      '/batch': { post: { operationId: 'batchFavicons', summary: 'Batch favicon retrieval for up to 20 URLs', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['urls'], properties: { urls: { type: 'array', items: { type: 'string' }, maxItems: 20 } } } } } }, responses: { '200': { description: 'Batch results', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, results: { type: 'array', items: { type: 'object', properties: { url: { type: 'string' }, favicon_url: { type: 'string' }, format: { type: 'string' }, accessible: { type: 'boolean' }, error: { type: 'string', nullable: true } } } }, summary: { type: 'object', properties: { total: { type: 'number' }, successful: { type: 'number' }, failed: { type: 'number' } } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing urls' }, '500': { description: 'Failed' } } } },
      '/metadata': { post: { operationId: 'getFaviconMetadata', summary: 'Extract favicon metadata — size, color profile, transparency, dominant color', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['url'], properties: { url: { type: 'string' } } } } } }, responses: { '200': { description: 'Favicon metadata', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, url: { type: 'string' }, metadata: { type: 'object', properties: { favicon_url: { type: 'string' }, format: { type: 'string' }, sizes: { type: 'array', items: { type: 'string' } }, file_size_bytes: { type: 'number' }, dominant_color: { type: 'string' }, has_transparency: { type: 'boolean' } } }, apple_touch_icon: { type: 'string' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing url' }, '500': { description: 'Failed' } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['url'], properties: { url: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, next_api: { type: 'string' }, blocking_flags: actions, confidence_per_section: confidence, privacy } } } } } } } },
      '/detect': { post: { operationId: 'detect', summary: 'ONE-CALL: full favicon detection — favicon + metadata + quality score', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['url'], properties: { url: { type: 'string' } } } } } }, responses: { '200': { description: 'Full favicon intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, url: { type: 'string' }, favicon: { type: 'object' }, metadata: { type: 'object' }, apple_touch_icon: { type: 'string' }, quality_score: { type: 'number' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing url' }, '500': { description: 'Failed' } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
