import { Router, Request, Response } from 'express';
const router = Router();

const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: {
      title: 'Compliance API',
      version: '1.0.0',
      description: 'Full-stack compliance infrastructure for autonomous agents — KYC, sanctions screening, AML checks, jurisdiction validation, counterparty verification, transaction risk, watchlist management, audit trails, risk profiling and compliance reporting',
      'x-agent-callable': true,
      'x-mcp-compatible': true,
      'x-pricing': { free_tier: { requests_per_day: 100, requests_per_month: 3000 }, pay_per_call: { kyc_check: '$0.007', sanctions_screen: '$0.005', aml_check: '$0.006', jurisdiction_check: '$0.005', verify_counterparty: '$0.006', transaction_risk: '$0.005', watchlist_manage: '$0.004', audit_trail: '$0.003', risk_profile: '$0.008', compliance_report: '$0.012', execution_gate: '$0.002' } },
    },
    servers: [{ url: 'https://orbis-apis.onrender.com/compliance' }],
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/': { get: { operationId: 'complianceDiscovery', summary: 'API discovery', responses: { '200': { description: 'API discovery info' } } } },
      '/kyc-check': { post: { operationId: 'kycCheck', summary: 'KYC verification with identity scoring, document validation and jurisdiction requirements', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['entity_id', 'entity_type'], properties: { entity_id: { type: 'string' }, entity_type: { type: 'string' }, identity_data: { type: 'object' }, verification_level: { type: 'string', enum: ['basic', 'standard', 'enhanced', 'kyc'] }, jurisdiction: { type: 'string' } } } } } }, responses: { '200': { description: 'KYC result' }, '400': { description: 'Missing required fields' }, '500': { description: 'KYC check failed' } } } },
      '/sanctions-screen': { post: { operationId: 'complianceSanctionsScreen', summary: 'Screen entity against OFAC, UN, EU, OFSI sanctions lists with match confidence', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['entity_id'], properties: { entity_id: { type: 'string' }, wallet_address: { type: 'string' }, name: { type: 'string' }, jurisdiction: { type: 'string' }, screen_lists: { type: 'array', items: { type: 'string' } } } } } } }, responses: { '200': { description: 'Sanctions screening result' }, '400': { description: 'Missing entity_id' }, '500': { description: 'Screening failed' } } } },
      '/aml-check': { post: { operationId: 'complianceAmlCheck', summary: 'AML check with structuring detection, layering analysis, SAR/CTR requirements and jurisdiction risk', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['entity_id', 'amount_usdc'], properties: { entity_id: { type: 'string' }, wallet_address: { type: 'string' }, amount_usdc: { type: 'number' }, transaction_pattern: { type: 'object' }, jurisdiction: { type: 'string' } } } } } }, responses: { '200': { description: 'AML check result' }, '400': { description: 'Missing required fields' }, '500': { description: 'AML check failed' } } } },
      '/jurisdiction-check': { post: { operationId: 'jurisdictionCheck', summary: 'Check jurisdictional compliance for cross-border transactions with licensing and reporting requirements', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['entity_id', 'from_jurisdiction', 'to_jurisdiction'], properties: { entity_id: { type: 'string' }, from_jurisdiction: { type: 'string' }, to_jurisdiction: { type: 'string' }, transaction_type: { type: 'string' }, amount_usdc: { type: 'number' } } } } } }, responses: { '200': { description: 'Jurisdiction check result' }, '400': { description: 'Missing required fields' }, '500': { description: 'Jurisdiction check failed' } } } },
      '/verify-counterparty': { post: { operationId: 'complianceVerifyCounterparty', summary: 'Full counterparty verification including KYC, sanctions, AML and trust scoring', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['entity_id', 'counterparty_id'], properties: { entity_id: { type: 'string' }, counterparty_id: { type: 'string' }, wallet_address: { type: 'string' }, verification_level: { type: 'string', enum: ['basic', 'standard', 'enhanced', 'kyc'] }, transaction_context: { type: 'object' } } } } } }, responses: { '200': { description: 'Counterparty verification result' }, '400': { description: 'Missing required fields' }, '500': { description: 'Verification failed' } } } },
      '/transaction-risk': { post: { operationId: 'complianceTransactionRisk', summary: 'Comprehensive transaction risk scoring across counterparty, amount, pattern, jurisdiction and behavioral dimensions', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['entity_id', 'amount_usdc'], properties: { entity_id: { type: 'string' }, from_wallet: { type: 'string' }, to_wallet: { type: 'string' }, amount_usdc: { type: 'number' }, purpose: { type: 'string' }, metadata: { type: 'object' } } } } } }, responses: { '200': { description: 'Transaction risk assessment' }, '400': { description: 'Missing required fields' }, '500': { description: 'Risk assessment failed' } } } },
      '/watchlist-manage': { post: { operationId: 'watchlistManage', summary: 'Add, remove, check or update compliance watchlist entries with severity scoring and audit trail', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['action', 'entity_id'], properties: { action: { type: 'string', enum: ['add', 'remove', 'check', 'update'] }, entity_id: { type: 'string' }, watchlist_id: { type: 'string' }, reason: { type: 'string' }, severity: { type: 'string', enum: ['low', 'medium', 'high', 'critical'] }, metadata: { type: 'object' } } } } } }, responses: { '200': { description: 'Watchlist operation result' }, '400': { description: 'Missing required fields' }, '500': { description: 'Watchlist operation failed' } } } },
      '/audit-trail': { post: { operationId: 'auditTrail', summary: 'Generate immutable compliance audit trail entry with hash chaining and regulatory significance assessment', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['entity_id', 'event_type'], properties: { entity_id: { type: 'string' }, event_type: { type: 'string' }, event_data: { type: 'object' }, actor_id: { type: 'string' }, timestamp: { type: 'string', format: 'date-time' } } } } } }, responses: { '200': { description: 'Audit trail entry' }, '400': { description: 'Missing required fields' }, '500': { description: 'Audit trail failed' } } } },
      '/risk-profile': { post: { operationId: 'riskProfile', summary: 'Build composite compliance risk profile aggregating KYC, AML, sanctions and behavioral signals', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['entity_id', 'entity_type'], properties: { entity_id: { type: 'string' }, entity_type: { type: 'string' }, transaction_history: { type: 'object' }, jurisdiction: { type: 'string' }, business_type: { type: 'string' } } } } } }, responses: { '200': { description: 'Risk profile result' }, '400': { description: 'Missing required fields' }, '500': { description: 'Risk profile failed' } } } },
      '/compliance-report': { post: { operationId: 'complianceReport', summary: 'Generate compliance report summarizing KYC, AML, sanctions, risk and regulatory obligations for a period', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['entity_id', 'report_type'], properties: { entity_id: { type: 'string' }, report_type: { type: 'string', enum: ['full', 'kyc', 'aml', 'sanctions', 'risk'] }, period_start: { type: 'string', format: 'date-time' }, period_end: { type: 'string', format: 'date-time' }, include_sections: { type: 'array', items: { type: 'string' } } } } } } }, responses: { '200': { description: 'Compliance report' }, '400': { description: 'Missing required fields' }, '500': { description: 'Report generation failed' } } } },
      '/execution-gate': { post: { operationId: 'complianceExecutionGate', summary: 'Gate compliance-sensitive actions with full KYC, sanctions, AML and jurisdiction checks', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['entity_id', 'action_type', 'action_context'], properties: { entity_id: { type: 'string' }, action_type: { type: 'string' }, action_context: { type: 'object' }, risk_threshold: { type: 'number', minimum: 0, maximum: 1 } } } } } }, responses: { '200': { description: 'Compliance gate decision' }, '400': { description: 'Missing required fields' }, '500': { description: 'Gate check failed' } } } },
    },
  });
});

export default router;
