import { Router, Request, Response } from 'express';
const router = Router();

const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string', format: 'date-time' }, success: { type: 'boolean' } };
const provenance = { type: 'object', properties: { provider: { type: 'string' }, retrieved_at: { type: 'string', format: 'date-time' }, freshness_score: { type: 'number', minimum: 0, maximum: 1 } } };
const chainFields = { source_provenance: provenance, cache_ttl_seconds: { type: 'integer' }, cache_recommended: { type: 'boolean' }, recommended_next_api: { type: 'string' }, recommended_next_endpoint: { type: 'string' }, automation_safe: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Token Metadata API', version: '1.0.0', description: 'Look up token metadata, verify authenticity, get social stats and compare tokens for DeFi and NFT agent workflows', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 300 }, pay_per_call: { lookup: '$0.002', verify: '$0.003', social: '$0.003', 'execution-gate': '$0.001', 'token-intelligence': '$0.008', compare: '$0.004', batch: '$0.015' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/token-metadata' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/lookup': { post: { operationId: 'lookupToken', summary: 'Look up token metadata by address or symbol', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { address: { type: 'string' }, chain: { type: 'string' }, symbol: { type: 'string' } } } } } }, responses: { '200': { description: 'Token metadata', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, symbol: { type: 'string' }, name: { type: 'string' }, decimals: { type: 'integer' }, token_type: { type: 'string' }, verified: { type: 'boolean' }, ...chainFields, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } } } } },
      '/verify': { post: { operationId: 'verifyToken', summary: 'Verify token authenticity and check honeypot risk', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { address: { type: 'string' }, chain: { type: 'string' }, symbol: { type: 'string' } } } } } }, responses: { '200': { description: 'Verification result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, is_verified: { type: 'boolean' }, honeypot_risk: { type: 'boolean' }, trust_score: { type: 'number' }, warnings: { type: 'array', items: { type: 'string' } }, ...chainFields, privacy } } } } } } } },
      '/social': { post: { operationId: 'getTokenSocial', summary: 'Get token social stats and community metrics', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { address: { type: 'string' }, symbol: { type: 'string' } } } } } }, responses: { '200': { description: 'Social stats', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, twitter_followers: { type: 'integer' }, community_score: { type: 'number' }, developer_activity: { type: 'string' }, ...chainFields, privacy } } } } } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { address: { type: 'string' }, symbol: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, ...chainFields, privacy } } } } } } } },
      '/token-intelligence': { post: { operationId: 'tokenIntelligence', summary: 'ONE-CALL: metadata + verification + social + risk summary', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { address: { type: 'string' }, chain: { type: 'string' }, symbol: { type: 'string' } } } } } }, responses: { '200': { description: 'Full token intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, is_verified: { type: 'boolean' }, trust_score: { type: 'number' }, risk_summary: { type: 'string' }, key_risks: { type: 'array', items: { type: 'string' } }, ...chainFields, confidence_per_section: confidence, privacy } } } } } } } },
      '/compare': { post: { operationId: 'compareTokens', summary: 'Compare two tokens on fundamentals', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['token_a', 'token_b'], properties: { token_a: { type: 'string' }, token_b: { type: 'string' } } } } } }, responses: { '200': { description: 'Token comparison', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, stronger_fundamentals: { type: 'string' }, key_differences: { type: 'array', items: { type: 'string' } }, ...chainFields, privacy } } } } } } } },
      '/batch': { post: { operationId: 'batchTokens', summary: 'Batch lookup up to 5 tokens', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['tokens'], properties: { tokens: { type: 'array', items: { type: 'object' }, maxItems: 5 } } } } } }, responses: { '200': { description: 'Batch results', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, batch_count: { type: 'integer' }, results: { type: 'array', items: { type: 'object' } }, ...chainFields } } } } } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
