import { Router, Request, Response } from 'express';
const router = Router();
const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string' }, success: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Shipping Rate API', version: '1.0.0', description: 'Estimate shipping rates by carrier, track shipments, and compare carrier rates for e-commerce, logistics, and fulfillment automation agents', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 100, requests_per_month: 3000 }, pay_per_call: { estimate: '$0.003', track: '$0.002', 'carrier-compare': '$0.005', 'execution-gate': '$0.001', lookup: '$0.006' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/shipping-rate' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/estimate': { post: { operationId: 'estimateRate', summary: 'Estimate shipping rate by carrier', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['origin_zip', 'dest_zip', 'weight_lbs'], properties: { origin_zip: { type: 'string' }, dest_zip: { type: 'string' }, weight_lbs: { type: 'number' }, carrier: { type: 'string' } } } } } }, responses: { '200': { description: 'Rate estimates', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, estimates: { type: 'array', items: { type: 'object' } }, cheapest: { type: 'object' }, fastest: { type: 'object' }, disclaimer: { type: 'string' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing fields' }, '500': { description: 'Failed' } } } },
      '/track': { post: { operationId: 'trackShipment', summary: 'Track a shipment by tracking number', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['tracking_number'], properties: { tracking_number: { type: 'string' } } } } } }, responses: { '200': { description: 'Shipment tracking', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, tracking_number: { type: 'string' }, carrier: { type: 'string' }, status: { type: 'string' }, events: { type: 'array', items: { type: 'object' } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing tracking_number' }, '500': { description: 'Failed' } } } },
      '/carrier-compare': { post: { operationId: 'carrierCompare', summary: 'Compare rates across all major carriers', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['origin_zip', 'dest_zip', 'weight_lbs'], properties: { origin_zip: { type: 'string' }, dest_zip: { type: 'string' }, weight_lbs: { type: 'number' } } } } } }, responses: { '200': { description: 'Carrier comparison', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, carriers: { type: 'array', items: { type: 'object' } }, winner_cost: { type: 'object' }, winner_speed: { type: 'object' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing fields' }, '500': { description: 'Failed' } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['origin_zip', 'dest_zip'], properties: { origin_zip: { type: 'string' }, dest_zip: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, next_api: { type: 'string' }, blocking_flags: actions, confidence_per_section: confidence, privacy } } } } } } } },
      '/lookup': { post: { operationId: 'lookup', summary: 'ONE-CALL: full shipping intelligence — all rates + recommendation + zone', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['origin_zip', 'dest_zip', 'weight_lbs'], properties: { origin_zip: { type: 'string' }, dest_zip: { type: 'string' }, weight_lbs: { type: 'number' } } } } } }, responses: { '200': { description: 'Full shipping intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, all_options: { type: 'array', items: { type: 'object' } }, recommended: { type: 'object' }, zone: { type: 'number' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing fields' }, '500': { description: 'Failed' } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
