import { Router, Request, Response } from 'express';
const router = Router();

const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string', format: 'date-time' }, success: { type: 'boolean' } };
const provenance = { type: 'object', properties: { provider: { type: 'string' }, retrieved_at: { type: 'string', format: 'date-time' }, freshness_score: { type: 'number', minimum: 0, maximum: 1 } } };
const chainFields = { source_provenance: provenance, cache_ttl_seconds: { type: 'integer' }, cache_recommended: { type: 'boolean' }, recommended_next_api: { type: 'string' }, recommended_next_endpoint: { type: 'string' }, automation_safe: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Thumbnail Analysis API', version: '1.0.0', description: 'Analyze thumbnail quality, score click-through potential, suggest improvements and compare thumbnails for content creators and media agents', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 200 }, pay_per_call: { analyze: '$0.005', score: '$0.003', suggest: '$0.004', 'execution-gate': '$0.001', 'thumbnail-intelligence': '$0.010', compare: '$0.005', batch: '$0.020' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/thumbnail-analysis' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/analyze': { post: { operationId: 'analyzeThumbnail', summary: 'Analyze thumbnail quality and composition', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['image_url'], properties: { image_url: { type: 'string' }, context: { type: 'string' } } } } } }, responses: { '200': { description: 'Thumbnail analysis', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, visual_quality: { type: 'string' }, composition_score: { type: 'number' }, text_readability: { type: 'string' }, color_contrast: { type: 'string' }, ...chainFields, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } } } } },
      '/score': { post: { operationId: 'scoreThumbnail', summary: 'Score click-through potential 0-100', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['image_url'], properties: { image_url: { type: 'string' }, platform: { type: 'string' }, niche: { type: 'string' } } } } } }, responses: { '200': { description: 'CTR score', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, ctr_score: { type: 'integer' }, grade: { type: 'string' }, score_breakdown: { type: 'object' }, ...chainFields, privacy } } } } } } } },
      '/suggest': { post: { operationId: 'suggestImprovements', summary: 'Suggest thumbnail improvements', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['image_url'], properties: { image_url: { type: 'string' }, goal: { type: 'string' } } } } } }, responses: { '200': { description: 'Improvement suggestions', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, suggestions: { type: 'array', items: { type: 'string' } }, priority_fix: { type: 'string' }, expected_improvement: { type: 'string' }, ...chainFields, privacy } } } } } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['image_url'], properties: { image_url: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, ...chainFields, privacy } } } } } } } },
      '/thumbnail-intelligence': { post: { operationId: 'thumbnailIntelligence', summary: 'ONE-CALL: analyze + score + suggest + platform fit', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['image_url'], properties: { image_url: { type: 'string' }, platform: { type: 'string' }, niche: { type: 'string' } } } } } }, responses: { '200': { description: 'Full thumbnail intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, ctr_score: { type: 'integer' }, grade: { type: 'string' }, top_issues: { type: 'array', items: { type: 'string' } }, quick_wins: { type: 'array', items: { type: 'string' } }, platform_fit: { type: 'string' }, ...chainFields, confidence_per_section: confidence, privacy } } } } } } } },
      '/compare': { post: { operationId: 'compareThumbnails', summary: 'Compare two thumbnails head-to-head', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['image_url_a', 'image_url_b'], properties: { image_url_a: { type: 'string' }, image_url_b: { type: 'string' }, platform: { type: 'string' } } } } } }, responses: { '200': { description: 'Comparison result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, winner: { type: 'string' }, scores: { type: 'object' }, win_reason: { type: 'string' }, ...chainFields, privacy } } } } } } } },
      '/batch': { post: { operationId: 'batchThumbnails', summary: 'Batch score up to 5 thumbnails', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['thumbnails'], properties: { thumbnails: { type: 'array', items: { type: 'object' }, maxItems: 5 } } } } } }, responses: { '200': { description: 'Batch results', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, batch_count: { type: 'integer' }, results: { type: 'array', items: { type: 'object' } }, ...chainFields } } } } } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
