import { Router, Request, Response } from 'express';
const router = Router();
const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string' }, success: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'PDF Text Extraction API', version: '1.0.0', description: 'Extract clean text, structured tables, and metadata from PDF files for document intelligence, RAG ingestion, and autonomous research workflows.', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 200, requests_per_month: 6000 }, pay_per_call: { 'extract-text': '$0.004', 'extract-tables': '$0.006', metadata: '$0.002', 'execution-gate': '$0.001', extract: '$0.008' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/pdf-extraction' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/extract-text': { post: { operationId: 'extractText', summary: 'Extract clean text from PDF — full text, word count, language, per-page breakdown', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['pdf_url'], properties: { pdf_url: { type: 'string' }, pages: { type: 'string', description: 'Page range e.g. "1-5"' } } } } } }, responses: { '200': { description: 'Extracted text', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, pdf_url: { type: 'string' }, text: { type: 'object', properties: { full_text: { type: 'string' }, word_count: { type: 'number' }, language: { type: 'string' } } }, reading_time_minutes: { type: 'number' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing pdf_url' }, '500': { description: 'Failed' } } } },
      '/extract-tables': { post: { operationId: 'extractTables', summary: 'Extract structured tables from PDF — headers, rows, confidence per table', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['pdf_url'], properties: { pdf_url: { type: 'string' }, pages: { type: 'string' } } } } } }, responses: { '200': { description: 'Extracted tables', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, pdf_url: { type: 'string' }, tables: { type: 'array', items: { type: 'object', properties: { table_id: { type: 'number' }, page: { type: 'number' }, headers: { type: 'array', items: { type: 'string' } }, rows: { type: 'array', items: { type: 'array', items: { type: 'string' } } }, confidence: { type: 'number' } } } }, table_count: { type: 'number' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing pdf_url' }, '500': { description: 'Failed' } } } },
      '/metadata': { post: { operationId: 'getPdfMetadata', summary: 'Extract PDF metadata — title, author, page count, encryption status', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['pdf_url'], properties: { pdf_url: { type: 'string' } } } } } }, responses: { '200': { description: 'PDF metadata', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, pdf_url: { type: 'string' }, metadata: { type: 'object', properties: { title: { type: 'string' }, author: { type: 'string' }, page_count: { type: 'number' }, is_encrypted: { type: 'boolean' }, is_searchable: { type: 'boolean' }, language: { type: 'string' } } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing pdf_url' }, '500': { description: 'Failed' } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['pdf_url'], properties: { pdf_url: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, next_api: { type: 'string' }, blocking_flags: actions, confidence_per_section: confidence, privacy } } } } } } } },
      '/extract': { post: { operationId: 'extract', summary: 'ONE-CALL: full PDF extraction — text + tables + metadata + RAG chunks', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['pdf_url'], properties: { pdf_url: { type: 'string' }, pages: { type: 'string' } } } } } }, responses: { '200': { description: 'Full PDF extraction', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, pdf_url: { type: 'string' }, metadata: { type: 'object' }, text: { type: 'object' }, tables: { type: 'array', items: { type: 'object' } }, rag_chunks: { type: 'array', items: { type: 'object' } }, summary: { type: 'string' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing pdf_url' }, '500': { description: 'Failed' } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
