import { Router, Request, Response } from 'express';
const router = Router();
const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string' }, success: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Flight Status API', version: '1.0.0', description: 'Get real-time flight status, airport delay information, and route details for travel automation, expense management, and logistics coordination agents', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 100, requests_per_month: 3000 }, pay_per_call: { status: '$0.003', 'airport-delays': '$0.002', route: '$0.004', 'execution-gate': '$0.001', lookup: '$0.006' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/flight-status' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/status': { post: { operationId: 'getFlightStatus', summary: 'Get real-time flight status', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['flight_number'], properties: { flight_number: { type: 'string' }, date: { type: 'string' } } } } } }, responses: { '200': { description: 'Flight status', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, flight_number: { type: 'string' }, status: { type: 'string', enum: ['scheduled', 'active', 'landed', 'cancelled', 'diverted', 'unknown'] }, departure: { type: 'object' }, arrival: { type: 'object' }, on_time: { type: 'boolean' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing flight_number' }, '500': { description: 'Failed' } } } },
      '/airport-delays': { post: { operationId: 'airportDelays', summary: 'Get delay information for an airport (IATA code)', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['airport_code'], properties: { airport_code: { type: 'string', description: 'IATA airport code' } } } } } }, responses: { '200': { description: 'Airport delays', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, airport: { type: 'object' }, delay_status: { type: 'string', enum: ['no_delays', 'minor_delays', 'significant_delays', 'severe_delays', 'ground_stop'] }, average_delay_minutes: { type: 'number' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing airport_code' }, '500': { description: 'Failed' } } } },
      '/route': { post: { operationId: 'getRoute', summary: 'Find flights on a route between two airports', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['origin', 'destination'], properties: { origin: { type: 'string', description: 'IATA airport code' }, destination: { type: 'string', description: 'IATA airport code' }, date: { type: 'string' } } } } } }, responses: { '200': { description: 'Route flights', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, flights: { type: 'array', items: { type: 'object' } }, direct_flights: { type: 'number' }, distance_miles: { type: 'number' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing origin or destination' }, '500': { description: 'Failed' } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['flight_number'], properties: { flight_number: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, next_api: { type: 'string' }, blocking_flags: actions, confidence_per_section: confidence, privacy } } } } } } } },
      '/lookup': { post: { operationId: 'lookup', summary: 'ONE-CALL: full flight intelligence — status + route + airport delays + delay risk', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['flight_number'], properties: { flight_number: { type: 'string' } } } } } }, responses: { '200': { description: 'Full flight intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, flight_number: { type: 'string' }, status: { type: 'string' }, departure: { type: 'object' }, arrival: { type: 'object' }, delay_risk: { type: 'string', enum: ['high', 'medium', 'low', 'none'] }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing flight_number' }, '500': { description: 'Failed' } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
