import { Router, Request, Response } from 'express';
const router = Router();

router.get('/', (req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: {
      title: 'Lead Scoring API',
      version: '1.0.0',
      description: 'AI-powered lead scoring, BANT qualification, ICP fit, intent signals, and sales intelligence for autonomous agents.',
      'x-agent-callable': true,
      'x-mcp-compatible': true
    },
    servers: [{ url: 'https://orbis-apis.onrender.com/lead-scoring' }],
    paths: {
      '/score-lead': { post: { operationId: 'scoreLead', summary: 'Score a lead 0-100 with grade and qualification status', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['company_name', 'industry'], properties: { company_name: { type: 'string' }, industry: { type: 'string' }, company_size: { type: 'string' }, revenue: { type: 'string' }, technology_stack: { type: 'array', items: { type: 'string' } }, engagement_signals: { type: 'array', items: { type: 'string' } }, budget_range: { type: 'string' }, timeline: { type: 'string' }, pain_points: { type: 'array', items: { type: 'string' } } } } } } }, responses: { '200': { description: 'Lead score, grade, fit dimensions, recommended actions' }, '400': { description: 'Missing required fields' }, '500': { description: 'Scoring error' } } } },
      '/qualify-bant': { post: { operationId: 'qualifyBant', summary: 'Full BANT qualification with evidence and gaps', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['lead_data'], properties: { lead_data: { type: 'object' }, conversation_notes: { type: 'string' }, discovery_answers: { type: 'object' } } } } } }, responses: { '200': { description: 'BANT scores, verdict, discovery questions' }, '400': { description: 'Missing lead_data' }, '500': { description: 'Error' } } } },
      '/icp-fit': { post: { operationId: 'icpFit', summary: 'Score lead against Ideal Customer Profile', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['lead_profile', 'icp_definition'], properties: { lead_profile: { type: 'object' }, icp_definition: { type: 'object' } } } } } }, responses: { '200': { description: 'ICP fit score, grade, matching criteria, persona match' }, '400': { description: 'Missing fields' }, '500': { description: 'Error' } } } },
      '/intent-signals': { post: { operationId: 'intentSignals', summary: 'Analyze buyer intent signals and buying stage', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['company_name'], properties: { company_name: { type: 'string' }, behavioral_data: { type: 'object' }, firmographic_data: { type: 'object' }, engagement_history: { type: 'array', items: { type: 'object' } } } } } } }, responses: { '200': { description: 'Intent score, buying stage, signal categories' }, '400': { description: 'Missing company_name' }, '500': { description: 'Error' } } } },
      '/priority-rank': { post: { operationId: 'priorityRank', summary: 'Rank and tier multiple leads by sales priority', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['leads'], properties: { leads: { type: 'array', items: { type: 'object' } }, scoring_weights: { type: 'object' }, capacity: { type: 'number' } } } } } }, responses: { '200': { description: 'Ranked leads with tiers and distribution' }, '400': { description: 'Missing leads' }, '500': { description: 'Error' } } } },
      '/disqualify': { post: { operationId: 'disqualify', summary: 'Evaluate lead for disqualification with salvage potential', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['lead_data'], properties: { lead_data: { type: 'object' }, disqualification_criteria: { type: 'object' } } } } } }, responses: { '200': { description: 'Verdict, flags, salvage potential, recycle timeline' }, '400': { description: 'Missing lead_data' }, '500': { description: 'Error' } } } },
      '/enrich-profile': { post: { operationId: 'enrichProfile', summary: 'AI-enrich lead with inferred firmographics and persona', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['basic_lead_info'], properties: { basic_lead_info: { type: 'object' }, enrichment_context: { type: 'object' } } } } } }, responses: { '200': { description: 'Enriched profile, persona, company intelligence, conversation starters' }, '400': { description: 'Missing basic_lead_info' }, '500': { description: 'Error' } } } },
      '/conversion-predict': { post: { operationId: 'conversionPredict', summary: 'Predict conversion probability and close date', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['lead_score', 'current_stage'], properties: { lead_score: { type: 'number' }, current_stage: { type: 'string' }, deal_size: { type: 'number' }, sales_cycle_data: { type: 'object' }, historical_patterns: { type: 'object' } } } } } }, responses: { '200': { description: 'Conversion probability, close date, forecast category' }, '400': { description: 'Missing fields' }, '500': { description: 'Error' } } } },
      '/competitive-position': { post: { operationId: 'competitivePosition', summary: 'Analyze competitive positioning for this lead', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['lead_data', 'your_solution'], properties: { lead_data: { type: 'object' }, your_solution: { type: 'object' }, known_competitors: { type: 'array', items: { type: 'string' } } } } } } }, responses: { '200': { description: 'Threat matrix, win themes, objection predictions, deal risk' }, '400': { description: 'Missing fields' }, '500': { description: 'Error' } } } },
      '/routing-decision': { post: { operationId: 'routingDecision', summary: 'Determine optimal team/rep routing for a lead', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['lead_data'], properties: { lead_data: { type: 'object' }, team_structure: { type: 'object' }, routing_rules: { type: 'object' } } } } } }, responses: { '200': { description: 'Routing decision, SLA tier, handoff notes' }, '400': { description: 'Missing lead_data' }, '500': { description: 'Error' } } } },
      '/score-batch': { post: { operationId: 'scoreBatch', summary: 'Batch score up to 20 leads simultaneously', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['leads'], properties: { leads: { type: 'array', items: { type: 'object' }, maxItems: 20 }, scoring_model: { type: 'object' } } } } } }, responses: { '200': { description: 'All leads scored with batch summary' }, '400': { description: 'Missing leads' }, '422': { description: 'Exceeds 20 lead limit' }, '500': { description: 'Error' } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Gate — checks if lead is ready for outreach pipeline', 'x-agent-callable': true, requestBody: { required: false, content: { 'application/json': { schema: { type: 'object', properties: { lead_score: { type: 'number' }, qualification_status: { type: 'string' }, intent_score: { type: 'number' }, icp_fit_score: { type: 'number' } } } } } }, responses: { '200': { description: 'Execution readiness, blocking flags, next API in pipeline' } } } },
      '/analyze-lead': { post: { operationId: 'analyzeLead', summary: 'Full one-call lead intelligence workflow', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['company_name', 'industry'], properties: { company_name: { type: 'string' }, industry: { type: 'string' }, lead_data: { type: 'object' }, icp_definition: { type: 'object' }, known_competitors: { type: 'array', items: { type: 'string' } }, your_solution: { type: 'object' } } } } } }, responses: { '200': { description: 'Complete lead analysis: score, BANT, ICP, intent, competitive, conversion, routing' }, '400': { description: 'Missing fields' }, '500': { description: 'Error' } } } }
    }
  });
});

export default router;
