import { Router, Request, Response } from 'express';
const router = Router();
router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: {
      title: 'Social Sentiment API',
      version: '1.0.0',
      description: 'Real-time crypto social sentiment analysis. Track sentiment scores, velocity, volume changes and trending signals across BTC, ETH, SOL and 20+ major assets.',
      'x-agent-callable': true,
      'x-mcp-compatible': true,
      'x-human-approval-required': true,
      'x-execution-gate-required': true,
      'x-paper-mode-recommended': true,
      'x-crypto-safety': 'Sentiment data is for informational purposes only. Do not use as sole basis for financial decisions.',
      'x-pricing': { '/crypto-sentiment/{symbol}': 0.002, '/signals': 0.002, '/trending': 0.001, 
      '/history/{symbol}': { get: { operationId: 'getSentimentHistory', summary: 'Get historical sentiment trend for a crypto asset over 1d, 3d or 7d windows', 'x-agent-callable': true, 'x-human-approval-required': true,
        parameters: [
          { name: 'symbol', in: 'path', required: true, schema: { type: 'string', enum: ['BTC','ETH','SOL','BNB','XRP','ADA','DOGE','AVAX','LINK','DOT','MATIC','UNI','ARB','OP','SUI','APT','PEPE','WIF','BONK','INJ','TIA','ATOM','NEAR','FET'] } },
          { name: 'window', in: 'query', required: false, schema: { type: 'string', enum: ['1d','3d','7d'], default: '7d' } },
        ],
        responses: { '200': { description: 'Sentiment history', content: { 'application/json': { schema: { type: 'object', required: ['symbol', 'window', 'trend_windows'], properties: {
          symbol: { type: 'string' },
          window: { type: 'string' },
          trend_windows: { type: 'array', items: { type: 'object', properties: { window: { type: 'string' }, sentiment_score: { type: 'number', minimum: -1, maximum: 1 }, trend: { type: 'string' }, confidence: { type: 'number', minimum: 0, maximum: 1 } } } },
          momentum: { type: 'number', description: 'Score change over window' },
          momentum_direction: { type: 'string', enum: ['improving','deteriorating','stable'] },
          current_score: { type: 'number', minimum: -1, maximum: 1 },
          current_trend: { type: 'string', enum: ['bullish','bearish','neutral'] },
          confidence: { type: 'number', minimum: 0, maximum: 1 },
          recommended_actions_priority_order: { type: 'array', items: { type: 'string' } },
          chain_to: { type: 'array', items: { type: 'string' } },
          privacy: { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } },
          timestamp: { type: 'string', format: 'date-time' },
        } } } } } } } },
      '/narrative-cluster': { post: { operationId: 'narrativeCluster', summary: 'Group sentiment themes into narrative clusters with portfolio impact estimation', 'x-agent-callable': true,
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['symbol', 'themes'], properties: {
          symbol: { type: 'string' },
          themes: { type: 'array', items: { type: 'string' }, minItems: 1, maxItems: 20 },
          posts: { type: 'array', items: { type: 'object', properties: { title: { type: 'string' }, text: { type: 'string' } } }, maxItems: 30 },
        }}}}},
        responses: { '200': { description: 'Narrative clusters', content: { 'application/json': { schema: { type: 'object', required: ['symbol', 'clusters'], properties: {
          symbol: { type: 'string' },
          clusters: { type: 'array', items: { type: 'object', properties: {
            cluster_name: { type: 'string' }, themes: { type: 'array', items: { type: 'string' } },
            sentiment: { type: 'string', enum: ['bullish','bearish','neutral'] },
            strength: { type: 'string', enum: ['high','medium','low'] },
            narrative_summary: { type: 'string' },
            portfolio_impact: { type: 'string', enum: ['positive','negative','neutral'] },
            estimated_duration: { type: 'string', enum: ['short_term','medium_term','long_term'] },
          }}},
          dominant_narrative: { type: 'string' },
          narrative_conflict: { type: 'boolean' },
          conflict_reason: { type: 'string', nullable: true },
          confidence: { type: 'number', minimum: 0, maximum: 1 },
          recommended_actions_priority_order: { type: 'array', items: { type: 'string' } },
          chain_to: { type: 'array', items: { type: 'string' } },
          privacy: { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } },
          timestamp: { type: 'string', format: 'date-time' },
        } } } } } } } },
      '/event-extract': { post: { operationId: 'eventExtract', summary: 'Detect and classify market-moving events from sentiment content', 'x-agent-callable': true,
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['symbol'], properties: {
          symbol: { type: 'string' },
          content: { type: 'string', maxLength: 10000 },
          posts: { type: 'array', items: { type: 'object', properties: { title: { type: 'string' }, text: { type: 'string' } } }, maxItems: 30 },
        }}}}},
        responses: { '200': { description: 'Extracted market events', content: { 'application/json': { schema: { type: 'object', required: ['symbol', 'events'], properties: {
          symbol: { type: 'string' },
          events: { type: 'array', items: { type: 'object', properties: {
            event_type: { type: 'string', enum: ['regulatory','partnership','hack','listing','whale_move','macro','technical','sentiment_shift'] },
            title: { type: 'string' }, description: { type: 'string' },
            impact: { type: 'string', enum: ['high','medium','low'] },
            direction: { type: 'string', enum: ['bullish','bearish','neutral'] },
            confidence: { type: 'number', minimum: 0, maximum: 1 },
            time_sensitivity: { type: 'string', enum: ['immediate','24h','week'] },
            portfolio_impact_estimate: { type: 'string' },
          }}},
          event_count: { type: 'integer' },
          highest_impact_event: { type: 'string', nullable: true },
          overall_event_sentiment: { type: 'string', enum: ['bullish','bearish','neutral'] },
          recommended_actions_priority_order: { type: 'array', items: { type: 'string' } },
          chain_to: { type: 'array', items: { type: 'string' } },
          privacy: { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } },
          timestamp: { type: 'string', format: 'date-time' },
        } } } } } } } },
      '/execution-gate': 0.001 },
      privacy: { data_stored: false, retention: 'none' },
      disclaimer: 'For informational purposes only. Not financial advice.',
    },
    servers: [{ url: 'https://orbis-apis.onrender.com/social-sentiment' }],
    security: [{ ApiKeyAuth: [] }],
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
    paths: {
      '/': { get: { summary: 'API discovery', operationId: 'discovery', 'x-agent-callable': true,
      responses: { '200': { description: 'API info', content: { 'application/json': { schema: { type: 'object', properties: {
        title: { type: 'string' }, version: { type: 'string' }, description: { type: 'string' },
        status: { type: 'string', enum: ['ok'] },
        privacy: { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } },
        endpoints: { type: 'array', items: { type: 'object', properties: { path: { type: 'string' }, method: { type: 'string' }, price_usdc: { type: 'number' }, description: { type: 'string' } } } },
      } } } } } } } },
      '/crypto-sentiment/{symbol}': { get: { operationId: 'getCryptoSentiment', summary: 'Get real-time social sentiment for a crypto asset', 'x-agent-callable': true, 'x-human-approval-required': true,
        parameters: [{ name: 'symbol', in: 'path', required: true, schema: { type: 'string', enum: ['BTC','ETH','SOL','BNB','XRP','ADA','DOGE','AVAX','LINK','DOT','MATIC','UNI','ARB','OP','SUI','APT','PEPE','WIF','BONK','INJ','TIA','ATOM','NEAR','FET'] }, description: 'Crypto asset symbol' }],
        responses: { '200': { description: 'Sentiment analysis result', content: { 'application/json': { schema: { type: 'object', properties: {
          symbol: { type: 'string' },
          sentiment_score: { type: 'number', minimum: -1, maximum: 1, description: 'Aggregate sentiment score (-1 bearish to 1 bullish)' },
          trend: { type: 'string', enum: ['bullish', 'bearish', 'neutral'] },
          mentions: { type: 'integer', description: 'Total mention count across sources' },
          signal: { type: 'string', enum: ['strong_buy', 'buy', 'neutral', 'sell', 'strong_sell'] },
          confidence: { type: 'number', minimum: 0, maximum: 1 },
          velocity: { type: 'string', enum: ['increasing', 'stable', 'decreasing'], description: 'Sentiment momentum direction' },
          volume_change_24h: { type: 'string', description: 'Mention volume change over 24h' },
          reason: { type: 'string', description: 'Human-readable sentiment explanation' },
          top_themes: { type: 'array', items: { type: 'string' }, description: 'Top sentiment themes detected' },
          sources: { type: 'array', items: { type: 'string' }, description: 'Data sources used' },
          confidence_per_section: { type: 'object', properties: { sentiment: { type: 'number' }, themes: { type: 'number' }, velocity: { type: 'number' } } },
          recommended_actions_priority_order: { type: 'array', items: { type: 'string' } },
          chain_to: { type: 'array', items: { type: 'string' }, description: 'Suggested next APIs e.g. alpha-signal, onchain-signal' },
          privacy: { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } },
          trace_id: { type: 'string', description: 'Unique trace ID for this request' },
          execution_id: { type: 'string', description: 'Execution tracking ID' },
          source_provenance: { type: 'array', items: { type: 'object', properties: { source: { type: 'string' }, weight: { type: 'number' }, mention_count: { type: 'integer' }, confidence: { type: 'number', minimum: 0, maximum: 1 } } }, description: 'Per-source sentiment weighting and confidence' },
          timestamp: { type: 'string', format: 'date-time' },
        } } } } } } } },
      '/signals': { get: { operationId: 'getSentimentSignals', summary: 'Get aggregated sentiment signals across all tracked assets', 'x-agent-callable': true, 'x-human-approval-required': true,
        responses: { '200': { description: 'Sentiment signals', content: { 'application/json': { schema: { type: 'object', properties: {
          signals: { type: 'array', items: { type: 'object', properties: {
            symbol: { type: 'string' },
            sentiment_score: { type: 'number', minimum: -1, maximum: 1 },
            signal: { type: 'string', enum: ['strong_buy', 'buy', 'neutral', 'sell', 'strong_sell'] },
            confidence: { type: 'number', minimum: 0, maximum: 1 },
            trend: { type: 'string', enum: ['bullish', 'bearish', 'neutral'] },
          }}},
          count: { type: 'integer' },
          confidence_per_section: { type: 'object', properties: { signals: { type: 'number' } } },
          recommended_actions_priority_order: { type: 'array', items: { type: 'string' } },
          chain_to: { type: 'array', items: { type: 'string' } },
          privacy: { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } },
          timestamp: { type: 'string', format: 'date-time' },
        } } } } } } } },
      '/trending': { get: { operationId: 'getTrending', summary: 'Get trending crypto assets by social mention volume', 'x-agent-callable': true, 'x-human-approval-required': true,
        responses: { '200': { description: 'Trending assets', content: { 'application/json': { schema: { type: 'object', properties: {
          trending: { type: 'array', items: { type: 'object', properties: {
            symbol: { type: 'string' },
            mention_volume: { type: 'integer' },
            sentiment_score: { type: 'number', minimum: -1, maximum: 1 },
            velocity: { type: 'string', enum: ['increasing', 'stable', 'decreasing'] },
            confidence: { type: 'number', minimum: 0, maximum: 1 },
            rank: { type: 'integer' },
          }}},
          count: { type: 'integer' },
          recommended_actions_priority_order: { type: 'array', items: { type: 'string' } },
          chain_to: { type: 'array', items: { type: 'string' } },
          privacy: { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } },
          timestamp: { type: 'string', format: 'date-time' },
        } } } } } } } },
      
      '/history/{symbol}': { get: { operationId: 'getSentimentHistory', summary: 'Get historical sentiment trend for a crypto asset over 1d, 3d or 7d windows', 'x-agent-callable': true, 'x-human-approval-required': true,
        parameters: [
          { name: 'symbol', in: 'path', required: true, schema: { type: 'string', enum: ['BTC','ETH','SOL','BNB','XRP','ADA','DOGE','AVAX','LINK','DOT','MATIC','UNI','ARB','OP','SUI','APT','PEPE','WIF','BONK','INJ','TIA','ATOM','NEAR','FET'] } },
          { name: 'window', in: 'query', required: false, schema: { type: 'string', enum: ['1d','3d','7d'], default: '7d' } },
        ],
        responses: { '200': { description: 'Sentiment history', content: { 'application/json': { schema: { type: 'object', required: ['symbol', 'window', 'trend_windows'], properties: {
          symbol: { type: 'string' },
          window: { type: 'string' },
          trend_windows: { type: 'array', items: { type: 'object', properties: { window: { type: 'string' }, sentiment_score: { type: 'number', minimum: -1, maximum: 1 }, trend: { type: 'string' }, confidence: { type: 'number', minimum: 0, maximum: 1 } } } },
          momentum: { type: 'number', description: 'Score change over window' },
          momentum_direction: { type: 'string', enum: ['improving','deteriorating','stable'] },
          current_score: { type: 'number', minimum: -1, maximum: 1 },
          current_trend: { type: 'string', enum: ['bullish','bearish','neutral'] },
          confidence: { type: 'number', minimum: 0, maximum: 1 },
          recommended_actions_priority_order: { type: 'array', items: { type: 'string' } },
          chain_to: { type: 'array', items: { type: 'string' } },
          privacy: { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } },
          timestamp: { type: 'string', format: 'date-time' },
        } } } } } } } },
      '/narrative-cluster': { post: { operationId: 'narrativeCluster', summary: 'Group sentiment themes into narrative clusters with portfolio impact estimation', 'x-agent-callable': true,
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['symbol', 'themes'], properties: {
          symbol: { type: 'string' },
          themes: { type: 'array', items: { type: 'string' }, minItems: 1, maxItems: 20 },
          posts: { type: 'array', items: { type: 'object', properties: { title: { type: 'string' }, text: { type: 'string' } } }, maxItems: 30 },
        }}}}},
        responses: { '200': { description: 'Narrative clusters', content: { 'application/json': { schema: { type: 'object', required: ['symbol', 'clusters'], properties: {
          symbol: { type: 'string' },
          clusters: { type: 'array', items: { type: 'object', properties: {
            cluster_name: { type: 'string' }, themes: { type: 'array', items: { type: 'string' } },
            sentiment: { type: 'string', enum: ['bullish','bearish','neutral'] },
            strength: { type: 'string', enum: ['high','medium','low'] },
            narrative_summary: { type: 'string' },
            portfolio_impact: { type: 'string', enum: ['positive','negative','neutral'] },
            estimated_duration: { type: 'string', enum: ['short_term','medium_term','long_term'] },
          }}},
          dominant_narrative: { type: 'string' },
          narrative_conflict: { type: 'boolean' },
          conflict_reason: { type: 'string', nullable: true },
          confidence: { type: 'number', minimum: 0, maximum: 1 },
          recommended_actions_priority_order: { type: 'array', items: { type: 'string' } },
          chain_to: { type: 'array', items: { type: 'string' } },
          privacy: { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } },
          timestamp: { type: 'string', format: 'date-time' },
        } } } } } } } },
      '/event-extract': { post: { operationId: 'eventExtract', summary: 'Detect and classify market-moving events from sentiment content', 'x-agent-callable': true,
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['symbol'], properties: {
          symbol: { type: 'string' },
          content: { type: 'string', maxLength: 10000 },
          posts: { type: 'array', items: { type: 'object', properties: { title: { type: 'string' }, text: { type: 'string' } } }, maxItems: 30 },
        }}}}},
        responses: { '200': { description: 'Extracted market events', content: { 'application/json': { schema: { type: 'object', required: ['symbol', 'events'], properties: {
          symbol: { type: 'string' },
          events: { type: 'array', items: { type: 'object', properties: {
            event_type: { type: 'string', enum: ['regulatory','partnership','hack','listing','whale_move','macro','technical','sentiment_shift'] },
            title: { type: 'string' }, description: { type: 'string' },
            impact: { type: 'string', enum: ['high','medium','low'] },
            direction: { type: 'string', enum: ['bullish','bearish','neutral'] },
            confidence: { type: 'number', minimum: 0, maximum: 1 },
            time_sensitivity: { type: 'string', enum: ['immediate','24h','week'] },
            portfolio_impact_estimate: { type: 'string' },
          }}},
          event_count: { type: 'integer' },
          highest_impact_event: { type: 'string', nullable: true },
          overall_event_sentiment: { type: 'string', enum: ['bullish','bearish','neutral'] },
          recommended_actions_priority_order: { type: 'array', items: { type: 'string' } },
          chain_to: { type: 'array', items: { type: 'string' } },
          privacy: { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } },
          timestamp: { type: 'string', format: 'date-time' },
        } } } } } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Gate agent action based on sentiment signal strength', 'x-agent-callable': true,
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['symbol', 'action'], properties: {
          symbol: { type: 'string' },
          action: { type: 'string' },
          min_sentiment_score: { type: 'number', minimum: -1, maximum: 1, default: 0.3 },
          min_confidence: { type: 'number', minimum: 0, maximum: 1, default: 0.6 },
        }}}}},
        responses: { '200': { description: 'Gate decision', content: { 'application/json': { schema: { type: 'object', properties: {
          execute: { type: 'boolean' },
          confidence: { type: 'number', minimum: 0, maximum: 1 },
          blocking_flags: { type: 'array', items: { type: 'string' } },
          recommended_actions_priority_order: { type: 'array', items: { type: 'string' } },
          chain_to: { type: 'array', items: { type: 'string' } },
          privacy: { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } },
        } } } } } } } },
    },
  });
});
export default router;
