import { Router, Request, Response } from 'express';
const router = Router();

router.get('/', (req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Competitor Monitor API', version: '1.0.0', description: 'AI-powered competitor monitoring, analysis, positioning intelligence and threat detection for autonomous agents.', 'x-agent-callable': true, 'x-mcp-compatible': true },
    servers: [{ url: 'https://orbis-apis.onrender.com/competitor-monitor' }],
    paths: {
      '/analyze-competitor': { post: { operationId: 'analyzeCompetitor', summary: 'Full competitor analysis with threat level and strategic direction', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['competitor_name', 'industry'], properties: { competitor_name: { type: 'string' }, your_company: { type: 'string' }, industry: { type: 'string' }, focus_areas: { type: 'array', items: { type: 'string' } } } } } } }, responses: { '200': { description: 'Threat level, strengths, weaknesses, market position, vulnerability gaps' }, '400': { description: 'Missing required fields' }, '500': { description: 'Error' } } } },
      '/compare-features': { post: { operationId: 'compareFeatures', summary: 'Side-by-side feature comparison matrix', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['your_product', 'competitor_product'], properties: { your_product: { type: 'object' }, competitor_product: { type: 'object' }, feature_list: { type: 'array', items: { type: 'string' } }, industry: { type: 'string' } } } } } }, responses: { '200': { description: 'Comparison matrix, gaps, advantages, positioning recommendations' }, '400': { description: 'Missing fields' }, '500': { description: 'Error' } } } },
      '/pricing-intelligence': { post: { operationId: 'pricingIntelligence', summary: 'Competitive pricing analysis and positioning recommendations', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['competitor_name', 'industry'], properties: { competitor_name: { type: 'string' }, your_pricing: { type: 'object' }, known_competitor_pricing: { type: 'object' }, industry: { type: 'string' }, segment: { type: 'string' } } } } } }, responses: { '200': { description: 'Pricing position, gap analysis, vulnerabilities, recommendations' }, '400': { description: 'Missing fields' }, '500': { description: 'Error' } } } },
      '/detect-threats': { post: { operationId: 'detectThreats', summary: 'Detect and rank competitive threats with recommended responses', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['your_company', 'industry'], properties: { your_company: { type: 'string' }, competitors: { type: 'array', items: { type: 'string' } }, market_signals: { type: 'array', items: { type: 'object' } }, industry: { type: 'string' } } } } } }, responses: { '200': { description: 'Threat matrix, emerging threats, defensive priorities, offensive opportunities' }, '400': { description: 'Missing fields' }, '500': { description: 'Error' } } } },
      '/positioning-map': { post: { operationId: 'positioningMap', summary: 'Generate competitive positioning map with white space opportunities', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['your_company', 'industry'], properties: { your_company: { type: 'string' }, competitors: { type: 'array', items: { type: 'string' } }, dimensions: { type: 'array', items: { type: 'string' } }, industry: { type: 'string' } } } } } }, responses: { '200': { description: 'Positioning map, quadrants, white space, repositioning opportunities' }, '400': { description: 'Missing fields' }, '500': { description: 'Error' } } } },
      '/battlecard': { post: { operationId: 'battlecard', summary: 'Generate sales battlecard with trap questions and win themes', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['competitor_name', 'your_solution'], properties: { competitor_name: { type: 'string' }, your_solution: { type: 'object' }, industry: { type: 'string' }, deal_context: { type: 'object' } } } } } }, responses: { '200': { description: 'Battlecard with talk tracks, trap questions, objection responses, win themes' }, '400': { description: 'Missing fields' }, '500': { description: 'Error' } } } },
      '/monitor-changes': { post: { operationId: 'monitorChanges', summary: 'Detect and interpret competitor changes and strategic shifts', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['competitor_name'], properties: { competitor_name: { type: 'string' }, previous_state: { type: 'object' }, current_signals: { type: 'array', items: { type: 'object' } }, monitoring_areas: { type: 'array', items: { type: 'string' } } } } } } }, responses: { '200': { description: 'Change summary, impact score, strategic implications, alert triggers' }, '400': { description: 'Missing competitor_name' }, '500': { description: 'Error' } } } },
      '/win-loss-analysis': { post: { operationId: 'winLossAnalysis', summary: 'Analyze win-loss patterns against competitors', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['deals'], properties: { deals: { type: 'array', items: { type: 'object' } }, competitor_name: { type: 'string' }, industry: { type: 'string' } } } } } }, responses: { '200': { description: 'Win rate, loss patterns, improvement opportunities, competitive win rates' }, '400': { description: 'Missing deals array' }, '500': { description: 'Error' } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Gate — checks competitive position before proceeding', 'x-agent-callable': true, requestBody: { required: false, content: { 'application/json': { schema: { type: 'object', properties: { threat_level: { type: 'string' }, competitive_score: { type: 'number' }, monitoring_active: { type: 'boolean' }, industry: { type: 'string' } } } } } }, responses: { '200': { description: 'Execution readiness, blocking flags, next API' } } } },
      '/analyze-competitive-landscape': { post: { operationId: 'analyzeCompetitiveLandscape', summary: 'ONE-CALL: full competitive landscape analysis', 'x-agent-callable': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['your_company', 'industry'], properties: { your_company: { type: 'string' }, competitors: { type: 'array', items: { type: 'string' } }, industry: { type: 'string' }, strategic_goals: { type: 'array', items: { type: 'string' } } } } } } }, responses: { '200': { description: 'Full landscape: market overview, threat matrix, positioning, opportunity map, strategic recommendations' }, '400': { description: 'Missing fields' }, '500': { description: 'Error' } } } }
    }
  });
});

export default router;
