// Illustrative example (NOT drift-locked — this API fetches live data, so output varies per call/address).
export const verdictExample: any = {
  trace_id: 'wv-1780000000000',
  request_id: 'wv-1780000000000',
  computed_at: '2026-06-21T12:00:00.000Z',
  success: true,
  latency_ms: 1840,
  address: '0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045',
  chain: 'ethereum',
  chain_family: 'evm',
  composite_risk_score: 22,
  trust_tier: 'neutral',
  verdict: 'allow',
  hard_block: false,
  is_sanctioned: false,
  sources_used: ['address_risk', 'reputation', 'balance', 'ofac_sanctions', 'onchain'],
  unavailable_sources: [],
  source_fetches: [
    { source: 'address_risk', status: 'ok', latency_ms: 1700, detail: 'AML risk 25/100' },
    { source: 'reputation', status: 'ok', latency_ms: 420, detail: 'reputation 78/100 (good)' },
    { source: 'balance', status: 'ok', latency_ms: 510, detail: '$4200 ETH' },
    { source: 'ofac_sanctions', status: 'ok', latency_ms: 12, detail: 'no OFAC SDN match' },
    { source: 'onchain', status: 'ok', latency_ms: 640, detail: 'ETH balance 1.84, 312 tx, 2200d old' },
  ],
  fetched: {
    sanctions: { checked: true, listed: false, source: 'OFAC SDN crypto-address list (treasury.gov, OFAC-derived)', list_size: 612, detail: 'no OFAC SDN match' },
    onchain: { checked: true, exists: true, is_contract: false, native_balance: 1.84, native_symbol: 'ETH', tx_count: 312, age_days: 2200, risk_score: 12, flags: ['established_history'], provider: 'etherscan-v2', detail: 'ETH balance 1.84, 312 tx, 2200d old' },
    address_risk: { risk_score: 25, risk_level: 'low', is_sanctioned: false, is_mixer: false, illicit_exposure_pct: 2 },
    reputation: { score: 78, rating: 'good' },
    balance: { native_balance_usd: 4200, native_symbol: 'ETH', last_activity: '2026-06-18T00:00:00.000Z' },
  },
  contributions: [
    { source: 'address_risk', risk: 17, weight: 0.8, weighted: 13.6, note: 'address_risk contributed 17/100 at re-normalized weight 0.8.' },
    { source: 'reputation', risk: 22, weight: 0.2, weighted: 4.4, note: 'reputation contributed 22/100 at re-normalized weight 0.2.' },
  ],
  data_unavailable: false,
  risk_disclaimer: 'Composite verdict for the supplied address. is_sanctioned is grounded in the real OFAC SDN list …',
  confidence_score: 0.87,
  confidence_per_section: { fetch: 1, sanctions: 1, fusion: 1, interpretation: 0.7 },
  recommended_actions_priority_order: ['…'],
  chain_to: [],
  privacy: { data_stored: false, retention: 'none' },
  execution_metadata: { model: 'deterministic', automation_safe: true },
};
export const lookupExample: any = { ...verdictExample, reasoning: { why_result_generated: '…', key_factors: ['…'], invalidators: ['…'] } };
