import { Router, Request, Response } from 'express';
const router = Router();
const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string' }, success: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Currency Formatting API', version: '1.0.0', description: 'Format currency amounts for any locale, convert between currencies with formatting, and look up currency symbols and metadata for invoicing and finance automation agents', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 100, requests_per_month: 3000 }, pay_per_call: { format: '$0.001', convert: '$0.001', symbols: '$0.001', 'execution-gate': '$0.001', lookup: '$0.002' } }, 'x-financial-disclaimer': 'Exchange rates are indicative only. Verify with authoritative source before use in financial transactions.' },
    servers: [{ url: 'https://orbis-apis.onrender.com/currency-formatting' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/format': { post: { operationId: 'formatCurrency', summary: 'Format a currency amount for a locale', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['amount', 'currency'], properties: { amount: { type: 'number' }, currency: { type: 'string', description: 'ISO 4217 code' }, locale: { type: 'string', default: 'en-US' } } } } } }, responses: { '200': { description: 'Formatted currency', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, formatted: { type: 'string' }, symbol: { type: 'string' }, decimal_places: { type: 'number' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing fields' }, '500': { description: 'Failed' } } } },
      '/convert': { post: { operationId: 'convertCurrency', summary: 'Convert amount between currencies with formatting', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['amount', 'from_currency', 'to_currency'], properties: { amount: { type: 'number' }, from_currency: { type: 'string' }, to_currency: { type: 'string' } } } } } }, responses: { '200': { description: 'Converted amount with formatting', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, original: { type: 'object' }, converted: { type: 'object' }, exchange_rate: { type: 'number' }, financial_disclaimer: { type: 'string' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing fields' }, '500': { description: 'Failed' } } } },
      '/symbols': { post: { operationId: 'getCurrencySymbols', summary: 'List currency symbols and metadata', requestBody: { required: false, content: { 'application/json': { schema: { type: 'object', properties: { region: { type: 'string' } } } } } }, responses: { '200': { description: 'Currency symbols', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, currencies: { type: 'array', items: { type: 'object', properties: { code: { type: 'string' }, name: { type: 'string' }, symbol: { type: 'string' } } } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['currency'], properties: { currency: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, next_api: { type: 'string' }, blocking_flags: actions, confidence_per_section: confidence, privacy } } } } } } } },
      '/lookup': { post: { operationId: 'lookup', summary: 'ONE-CALL: full currency intelligence — metadata + examples + major pairs', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['currency'], properties: { currency: { type: 'string' } } } } } }, responses: { '200': { description: 'Full currency intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, metadata: { type: 'object' }, countries_using: { type: 'array', items: { type: 'string' } }, formatting_examples: { type: 'array', items: { type: 'object' } }, major_pairs: { type: 'array', items: { type: 'object' } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing currency' }, '500': { description: 'Failed' } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
