export const SCHEMAS: Record<string, { fields: Record<string, string>; context: string }> = {
  lead: {
    context: 'Extract contact and company information for a sales lead',
    fields: {
      name: 'string',
      email: 'string',
      phone: 'string',
      company: 'string',
      role: 'string',
      linkedin: 'string',
      location: 'string',
      industry: 'string',
    },
  },
  invoice: {
    context: 'Extract invoice and billing information',
    fields: {
      invoice_number: 'string',
      vendor_name: 'string',
      vendor_email: 'string',
      client_name: 'string',
      issue_date: 'string',
      due_date: 'string',
      total_amount: 'number',
      currency: 'string',
      line_items: 'array of {description, quantity, unit_price, total}',
      tax_amount: 'number',
      payment_terms: 'string',
    },
  },
  resume: {
    context: 'Extract professional profile and career information from a resume or CV',
    fields: {
      name: 'string',
      email: 'string',
      phone: 'string',
      location: 'string',
      linkedin: 'string',
      summary: 'string',
      skills: 'array of strings',
      experience: 'array of {company, role, start_date, end_date, description}',
      education: 'array of {institution, degree, field, graduation_year}',
      certifications: 'array of strings',
    },
  },
  contract: {
    context: 'Extract key terms and parties from a legal contract or agreement',
    fields: {
      contract_type: 'string',
      party_one: 'string',
      party_two: 'string',
      effective_date: 'string',
      expiration_date: 'string',
      value: 'number',
      currency: 'string',
      governing_law: 'string',
      payment_terms: 'string',
      termination_clause: 'string',
      key_obligations: 'array of strings',
    },
  },
  receipt: {
    context: 'Extract purchase and payment information from a receipt',
    fields: {
      merchant_name: 'string',
      merchant_address: 'string',
      date: 'string',
      total_amount: 'number',
      currency: 'string',
      items: 'array of {name, quantity, price}',
      tax: 'number',
      payment_method: 'string',
      receipt_number: 'string',
    },
  },
};
