import { Router, Request, Response } from 'express';
const router = Router();

const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string', format: 'date-time' }, success: { type: 'boolean' } };
const provenance = { type: 'object', properties: { provider: { type: 'string' }, retrieved_at: { type: 'string', format: 'date-time' }, freshness_score: { type: 'number', minimum: 0, maximum: 1 } } };
const chainFields = { source_provenance: provenance, cache_ttl_seconds: { type: 'integer' }, cache_recommended: { type: 'boolean' }, recommended_next_api: { type: 'string' }, recommended_next_endpoint: { type: 'string' }, automation_safe: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Insider Trades API', version: '1.0.0', description: 'Look up SEC Form 4 insider trades, generate signals and analyze trading trends for investment research agents', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 200 }, pay_per_call: { lookup: '$0.003', signals: '$0.004', summary: '$0.003', 'execution-gate': '$0.001', 'insider-intelligence': '$0.010', trend: '$0.004', batch: '$0.018' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/insider-trades' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/lookup': { post: { operationId: 'lookupInsiderTrades', summary: 'Look up recent insider trades for a ticker', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['ticker'], properties: { ticker: { type: 'string' }, limit: { type: 'integer' } } } } } }, responses: { '200': { description: 'Insider trades', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, ticker: { type: 'string' }, trades: { type: 'array', items: { type: 'object' } }, total_trades: { type: 'integer' }, ...chainFields, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } } } } },
      '/signals': { post: { operationId: 'getInsiderSignals', summary: 'Generate insider trading signals', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['ticker'], properties: { ticker: { type: 'string' } } } } } }, responses: { '200': { description: 'Trading signals', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, signal: { type: 'string', enum: ['bullish', 'bearish', 'neutral'] }, signal_strength: { type: 'string' }, buy_sell_ratio: { type: 'number' }, ...chainFields, privacy } } } } } } } },
      '/summary': { post: { operationId: 'summarizeTrades', summary: 'Summarize recent insider trading activity', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['ticker'], properties: { ticker: { type: 'string' }, period_days: { type: 'integer' } } } } } }, responses: { '200': { description: 'Activity summary', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, total_buys: { type: 'integer' }, total_sells: { type: 'integer' }, net_activity_usd: { type: 'number' }, ...chainFields, privacy } } } } } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['ticker'], properties: { ticker: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, ...chainFields, privacy } } } } } } } },
      '/insider-intelligence': { post: { operationId: 'insiderIntelligence', summary: 'ONE-CALL: trades + signals + trend + investment implication', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['ticker'], properties: { ticker: { type: 'string' }, context: { type: 'string' } } } } } }, responses: { '200': { description: 'Full insider intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, overall_signal: { type: 'string' }, notable_transactions: { type: 'array', items: { type: 'object' } }, investment_implication: { type: 'string' }, ...chainFields, confidence_per_section: confidence, privacy } } } } } } } },
      '/trend': { post: { operationId: 'analyzeTrend', summary: 'Analyze insider trading trend over time', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['ticker'], properties: { ticker: { type: 'string' } } } } } }, responses: { '200': { description: 'Trade trend', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, trend: { type: 'string' }, momentum_score: { type: 'number' }, predictive_signal: { type: 'string' }, ...chainFields, privacy } } } } } } } },
      '/batch': { post: { operationId: 'batchTickers', summary: 'Batch get insider signals for up to 5 tickers', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['tickers'], properties: { tickers: { type: 'array', items: { type: 'string' }, maxItems: 5 } } } } } }, responses: { '200': { description: 'Batch results', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, batch_count: { type: 'integer' }, results: { type: 'array', items: { type: 'object' } }, ...chainFields } } } } } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
