import { Router, Request, Response } from 'express';
const router = Router();

const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string', format: 'date-time' }, success: { type: 'boolean' } };
const provenance = { type: 'object', properties: { provider: { type: 'string' }, retrieved_at: { type: 'string', format: 'date-time' }, freshness_score: { type: 'number', minimum: 0, maximum: 1 } } };
const chainFields = { source_provenance: provenance, cache_ttl_seconds: { type: 'integer' }, cache_recommended: { type: 'boolean' }, recommended_next_api: { type: 'string' }, recommended_next_endpoint: { type: 'string' }, automation_safe: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'ETF Holdings API', version: '1.0.0', description: 'Look up ETF holdings, sector breakdowns, and compare funds for portfolio allocation and investment research agents', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 200 }, pay_per_call: { lookup: '$0.003', 'top-holdings': '$0.003', 'sector-breakdown': '$0.003', 'execution-gate': '$0.001', 'etf-intelligence': '$0.010', compare: '$0.005', batch: '$0.018' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/etf-holdings' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/lookup': { post: { operationId: 'lookupEtf', summary: 'Look up ETF holdings data', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['ticker'], properties: { ticker: { type: 'string' } } } } } }, responses: { '200': { description: 'ETF holdings', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, ticker: { type: 'string' }, name: { type: 'string' }, aum_usd: { type: 'number' }, top_holdings: { type: 'array', items: { type: 'object' } }, ...chainFields, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } } } } },
      '/top-holdings': { post: { operationId: 'getTopHoldings', summary: 'Get top N holdings with weights', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['ticker'], properties: { ticker: { type: 'string' }, limit: { type: 'integer' } } } } } }, responses: { '200': { description: 'Top holdings', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, top_holdings: { type: 'array', items: { type: 'object' } }, concentration_top10_pct: { type: 'number' }, ...chainFields, privacy } } } } } } } },
      '/sector-breakdown': { post: { operationId: 'getSectorBreakdown', summary: 'Analyze sector and geography allocation', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['ticker'], properties: { ticker: { type: 'string' } } } } } }, responses: { '200': { description: 'Sector breakdown', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, sector_allocation: { type: 'array', items: { type: 'object' } }, geography_allocation: { type: 'array', items: { type: 'object' } }, ...chainFields, privacy } } } } } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['ticker'], properties: { ticker: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, ...chainFields, privacy } } } } } } } },
      '/etf-intelligence': { post: { operationId: 'etfIntelligence', summary: 'ONE-CALL: holdings + sectors + analysis + investment thesis', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['ticker'], properties: { ticker: { type: 'string' }, context: { type: 'string' } } } } } }, responses: { '200': { description: 'Full ETF intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, name: { type: 'string' }, expense_ratio: { type: 'number' }, top_10_holdings: { type: 'array', items: { type: 'object' } }, investment_thesis: { type: 'string' }, ...chainFields, confidence_per_section: confidence, privacy } } } } } } } },
      '/compare': { post: { operationId: 'compareEtfs', summary: 'Compare two ETFs side by side', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['ticker_a', 'ticker_b'], properties: { ticker_a: { type: 'string' }, ticker_b: { type: 'string' } } } } } }, responses: { '200': { description: 'ETF comparison', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, comparison: { type: 'object' }, recommendation: { type: 'string' }, ...chainFields, privacy } } } } } } } },
      '/batch': { post: { operationId: 'batchEtfs', summary: 'Batch lookup up to 5 ETFs', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['tickers'], properties: { tickers: { type: 'array', items: { type: 'string' }, maxItems: 5 } } } } } }, responses: { '200': { description: 'Batch results', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, batch_count: { type: 'integer' }, results: { type: 'array', items: { type: 'object' } }, ...chainFields } } } } } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
