export default {
  name: 'Unified Multi-Provider Agent Completion API',
  slug: 'unified-ai-completion-api',
  version: '1.0.0',
  description: 'Route AI completions across 10+ providers with automatic cost optimization, confidence scoring, and agent-native chain routing.',
  category: 'AI / LLM Infrastructure',
  tags: ['ai', 'llm', 'gemini', 'openai', 'claude', 'routing', 'completions', 'agent', 'orbis'],
  baseRoute: '/api/unified-ai',
  endpoints: [
    { method: 'GET',  path: '/',                    description: 'Discovery endpoint' },
    { method: 'POST', path: '/v1/chat/completions', description: 'Unified completion' },
    { method: 'GET',  path: '/health',              description: 'Health check' },
  ],
  auth: { required: true, type: 'x-api-key' },
  pricing: { model: 'per-call', tiers: ['free', 'small', 'medium', 'large', 'premium'] },
  orbisCompliance: 'A+',
  agentCallable: true,
  mcpCompatible: true,
  x402Enabled: true,
  confidence: 0.97,
  executionGateRequired: false,
  privacyPolicy: 'No data retained. No training use. PII scrubbed.',
  chainTo: ['POST /api/sentiment', 'POST /api/entity-extraction', 'POST /api/fact-verification'],
};
