import { Router, Request, Response } from 'express';
const router = Router();
const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string' }, success: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Tax Rate Lookup API', version: '1.0.0', description: 'Look up US sales tax rates, VAT rates by country, and jurisdiction-level tax data for e-commerce checkout automation, invoicing, and compliance workflows', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 100, requests_per_month: 3000 }, pay_per_call: { 'sales-tax': '$0.002', vat: '$0.002', jurisdiction: '$0.003', 'execution-gate': '$0.001', lookup: '$0.004' } }, 'x-compliance-disclaimer': 'Tax rates are indicative. Verify with a licensed tax professional before use in compliance workflows.' },
    servers: [{ url: 'https://orbis-apis.onrender.com/tax-rate' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/sales-tax': { post: { operationId: 'getSalesTax', summary: 'Look up US sales tax rate by zip code', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['zip_code'], properties: { zip_code: { type: 'string' }, state: { type: 'string' } } } } } }, responses: { '200': { description: 'Sales tax rate', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, zip_code: { type: 'string' }, rates: { type: 'object', properties: { state_rate: { type: 'number' }, county_rate: { type: 'number' }, city_rate: { type: 'number' }, total_rate: { type: 'number' } } }, compliance_disclaimer: { type: 'string' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing zip_code' }, '500': { description: 'Failed' } } } },
      '/vat': { post: { operationId: 'getVat', summary: 'Look up VAT rate by country', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['country'], properties: { country: { type: 'string', description: 'ISO 3166-1 alpha-2 country code' } } } } } }, responses: { '200': { description: 'VAT rates', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, country: { type: 'string' }, vat_rates: { type: 'object' }, compliance_disclaimer: { type: 'string' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing country' }, '500': { description: 'Failed' } } } },
      '/jurisdiction': { post: { operationId: 'getJurisdiction', summary: 'Look up tax jurisdiction and rates by address', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['address'], properties: { address: { type: 'string' } } } } } }, responses: { '200': { description: 'Jurisdiction tax data', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, jurisdiction: { type: 'object' }, tax_rates: { type: 'object' }, nexus_risk: { type: 'string', enum: ['high', 'medium', 'low'] }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing address' }, '500': { description: 'Failed' } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['address'], properties: { address: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, next_api: { type: 'string' }, blocking_flags: actions, confidence_per_section: confidence, privacy } } } } } } } },
      '/lookup': { post: { operationId: 'lookup', summary: 'ONE-CALL: full tax rate intelligence — sales tax + VAT + jurisdiction + sample calculation', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['address'], properties: { address: { type: 'string' } } } } } }, responses: { '200': { description: 'Full tax intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, jurisdiction: { type: 'object' }, tax_rates: { type: 'object' }, sample_calculation: { type: 'object' }, compliance_disclaimer: { type: 'string' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing address' }, '500': { description: 'Failed' } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
