import { Router, Request, Response } from 'express';
const router = Router();
const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string' }, success: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Company Enrichment API', version: '1.0.0', description: 'Full company enrichment — profile, firmographics, technographics, and batch enrichment for autonomous agents', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 100, requests_per_month: 3000 }, pay_per_call: { 'company-profile': '$0.004', firmographics: '$0.005', technographics: '$0.005', batch: '$0.003', enrich: '$0.006', execution_gate: '$0.001' } }, 'x-compliance': { compliance_notice: 'Data sourced from public records and AI synthesis. Verify freshness before use in critical workflows.', data_retention: 'none' } },
    servers: [{ url: 'https://orbis-apis.onrender.com/company-enrichment' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/company-profile': { post: { operationId: 'companyProfile', summary: 'Basic company profile — name, domain, description, industry, founded, HQ', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { company_name: { type: 'string' }, domain: { type: 'string' } } } } } }, responses: { '200': { description: 'Company profile', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, company: { type: 'object', properties: { name: { type: 'string' }, domain: { type: 'string' }, description: { type: 'string' }, industry: { type: 'string' }, founded: { type: 'number' }, headquarters: { type: 'string' } } }, source_provenance: { type: 'object', properties: { source: { type: 'string' }, last_updated: { type: 'string' }, data_freshness_score: { type: 'number' } } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing identifier' }, '500': { description: 'Failed' } } } },
      '/firmographics': { post: { operationId: 'firmographics', summary: 'Firmographic data — employee count, revenue range, growth stage, SIC code', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { company_name: { type: 'string' }, domain: { type: 'string' } } } } } }, responses: { '200': { description: 'Firmographic data', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, firmographics: { type: 'object', properties: { employee_count_range: { type: 'string' }, revenue_range: { type: 'string' }, growth_stage: { type: 'string', enum: ['pre-seed', 'seed', 'series-a', 'series-b', 'series-c', 'growth', 'public', 'enterprise'] }, sic_code: { type: 'string' }, public_or_private: { type: 'string', enum: ['public', 'private'] } } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing identifier' }, '500': { description: 'Failed' } } } },
      '/technographics': { post: { operationId: 'technographics', summary: 'Tech stack signals — tools used, categories, stack maturity', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { company_name: { type: 'string' }, domain: { type: 'string' } } } } } }, responses: { '200': { description: 'Tech stack data', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, technographics: { type: 'object', properties: { stack_maturity: { type: 'string', enum: ['early', 'growing', 'mature', 'legacy'] }, cloud_provider: { type: 'string', enum: ['aws', 'gcp', 'azure', 'multi', 'unknown'] }, ai_ml_adoption: { type: 'string' } } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing identifier' }, '500': { description: 'Failed' } } } },
      '/batch': { post: { operationId: 'batchEnrich', summary: 'Enrich up to 10 companies at once', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['companies'], properties: { companies: { type: 'array', items: { type: 'string' }, maxItems: 10 } } } } } }, responses: { '200': { description: 'Batch enrichment results', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, results: { type: 'array', items: { type: 'object', properties: { company_name: { type: 'string' }, industry: { type: 'string' }, employee_range: { type: 'string' }, enrichment_confidence: { type: 'number' } } } }, batch_summary: { type: 'object', properties: { total: { type: 'number' }, enriched: { type: 'number' }, failed: { type: 'number' } } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing companies' }, '500': { description: 'Failed' } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { company_name: { type: 'string' }, domain: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, next_api: { type: 'string' }, blocking_flags: actions, confidence_per_section: confidence, privacy } } } } } } } },
      '/enrich': { post: { operationId: 'enrichCompany', summary: 'ONE-CALL: full company enrichment — profile + firmographics + technographics + signals', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { company_name: { type: 'string' }, domain: { type: 'string' } } } } } }, responses: { '200': { description: 'Full enrichment', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, company: { type: 'object' }, firmographics: { type: 'object' }, technographics: { type: 'object' }, icp_score: { type: 'number' }, outreach_priority: { type: 'string', enum: ['high', 'medium', 'low'] }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing identifier' }, '500': { description: 'Failed' } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
