import { Router, Request, Response } from 'express';
const router = Router();
const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string' }, success: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Website Screenshot API', version: '1.0.0', description: 'Screenshot capture planning, mobile configs, visual diff, and accessibility signals for autonomous agents', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 50, requests_per_month: 1500 }, pay_per_call: { screenshot: '$0.005', 'mobile-screenshot': '$0.004', diff: '$0.005', batch: '$0.003', capture: '$0.007', execution_gate: '$0.001' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/website-screenshot' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/screenshot': { post: { operationId: 'screenshot', summary: 'Desktop screenshot capture config with visual analysis', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['url'], properties: { url: { type: 'string' }, viewport: { type: 'object', properties: { width: { type: 'number', default: 1440 }, height: { type: 'number', default: 900 } } }, full_page: { type: 'boolean', default: false } } } } } }, responses: { '200': { description: 'Screenshot config', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, url: { type: 'string' }, screenshot_url: { type: 'string' }, image_base64: { type: 'string' }, asset_id: { type: 'string' }, capture_config: { type: 'object', properties: { viewport: { type: 'object' }, recommended_tool: { type: 'string', enum: ['playwright', 'puppeteer', 'selenium'] }, wait_for: { type: 'string', enum: ['networkidle', 'domcontentloaded', 'load'] } } }, visual_analysis: { type: 'object', properties: { layout_type: { type: 'string' }, cta_visibility: { type: 'string', enum: ['prominent', 'moderate', 'low', 'none'] } } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing url' }, '500': { description: 'Failed' } } } },
      '/mobile-screenshot': { post: { operationId: 'mobileScreenshot', summary: 'Mobile viewport config with device presets (iPhone, Android, tablet)', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['url'], properties: { url: { type: 'string' }, device: { type: 'string', default: 'iphone' } } } } } }, responses: { '200': { description: 'Mobile config', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, device_presets: { type: 'array', items: { type: 'object', properties: { device: { type: 'string' }, width: { type: 'number' }, height: { type: 'number' }, pixel_ratio: { type: 'number' } } } }, recommended_device: { type: 'string' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing url' }, '500': { description: 'Failed' } } } },
      '/diff': { post: { operationId: 'visualDiff', summary: 'Compare two URLs or timestamps — visual diff analysis, change classification', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['url_a'], properties: { url_a: { type: 'string' }, url_b: { type: 'string' }, timestamp_a: { type: 'string' }, timestamp_b: { type: 'string' } } } } } }, responses: { '200': { description: 'Visual diff result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, diff_summary: { type: 'object', properties: { change_detected: { type: 'boolean' }, change_magnitude: { type: 'string', enum: ['major', 'moderate', 'minor', 'none'] }, change_categories: actions } }, changes: { type: 'array', items: { type: 'object', properties: { area: { type: 'string' }, type: { type: 'string', enum: ['added', 'removed', 'modified'] }, severity: { type: 'string' } } } }, layout_stability_score: { type: 'number' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing url_a' }, '500': { description: 'Failed' } } } },
      '/batch': { post: { operationId: 'batchCapture', summary: 'Batch capture plan for up to 10 URLs', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['urls'], properties: { urls: { type: 'array', items: { type: 'string' }, maxItems: 10 }, viewport: { type: 'object' } } } } } }, responses: { '200': { description: 'Batch plan', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, batch_plan: { type: 'array', items: { type: 'object' } }, total_urls: { type: 'number' }, estimated_duration_ms: { type: 'number' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing urls' }, '500': { description: 'Failed' } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['url'], properties: { url: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, blocking_flags: actions, confidence_per_section: confidence, privacy } } } } } } } },
      '/capture': { post: { operationId: 'capture', summary: 'ONE-CALL: full capture + visual analysis + accessibility signals', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['url'], properties: { url: { type: 'string' }, device: { type: 'string', enum: ['desktop', 'mobile', 'tablet'] } } } } } }, responses: { '200': { description: 'Full capture analysis', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, url: { type: 'string' }, capture_config: { type: 'object' }, visual_analysis: { type: 'object' }, accessibility_signals: { type: 'array', items: { type: 'object' } }, overall_quality_score: { type: 'number' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing url' }, '500': { description: 'Failed' } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
