import { Router, Request, Response } from 'express';
const router = Router();
const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string' }, success: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Logo Finder API', version: '1.0.0', description: 'Retrieve company logos, brand assets, and favicons from domain names for UI enrichment, CRM automation, and brand intelligence workflows.', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 200, requests_per_month: 6000 }, pay_per_call: { logo: '$0.002', 'brand-assets': '$0.003', favicon: '$0.001', 'execution-gate': '$0.001', lookup: '$0.004' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/logo-finder' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/logo': { post: { operationId: 'getLogo', summary: 'Retrieve primary logo URL, format, and dimensions for a domain', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['domain'], properties: { domain: { type: 'string' } } } } } }, responses: { '200': { description: 'Logo data', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, domain: { type: 'string' }, logo: { type: 'object', properties: { url: { type: 'string' }, format: { type: 'string' }, width: { type: 'number' }, height: { type: 'number' }, background: { type: 'string' }, alt_text: { type: 'string' } } }, clearbit_url: { type: 'string' }, fallback_urls: { type: 'array', items: { type: 'string' } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing domain' }, '500': { description: 'Failed' } } } },
      '/brand-assets': { post: { operationId: 'getBrandAssets', summary: 'Retrieve full brand asset kit — logos, icons, colors, fonts', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['domain'], properties: { domain: { type: 'string' } } } } } }, responses: { '200': { description: 'Brand assets', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, domain: { type: 'string' }, brand_assets: { type: 'object', properties: { primary_logo: { type: 'object' }, dark_logo: { type: 'object' }, icon: { type: 'object' }, favicon: { type: 'object' }, brand_colors: { type: 'array', items: { type: 'string' } }, font_family: { type: 'string' } } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing domain' }, '500': { description: 'Failed' } } } },
      '/favicon': { post: { operationId: 'getFavicon', summary: 'Retrieve favicon URL, format, and size for a domain', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['domain'], properties: { domain: { type: 'string' } } } } } }, responses: { '200': { description: 'Favicon data', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, domain: { type: 'string' }, favicon: { type: 'object', properties: { url: { type: 'string' }, format: { type: 'string' }, size: { type: 'string' }, accessible: { type: 'boolean' } } }, apple_touch_icon: { type: 'string' }, android_icon: { type: 'string' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing domain' }, '500': { description: 'Failed' } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['domain'], properties: { domain: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, next_api: { type: 'string' }, blocking_flags: actions, confidence_per_section: confidence, privacy } } } } } } } },
      '/lookup': { post: { operationId: 'lookup', summary: 'ONE-CALL: full brand intelligence — logo + favicon + brand assets', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['domain'], properties: { domain: { type: 'string' } } } } } }, responses: { '200': { description: 'Full brand intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, domain: { type: 'string' }, logo: { type: 'object' }, favicon: { type: 'object' }, brand_assets: { type: 'object' }, clearbit_url: { type: 'string' }, brand_quality_score: { type: 'number' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing domain' }, '500': { description: 'Failed' } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
