import { Router, Request, Response } from 'express';
const router = Router();

const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string', format: 'date-time' }, success: { type: 'boolean' } };
const provenance = { type: 'object', properties: { provider: { type: 'string' }, retrieved_at: { type: 'string', format: 'date-time' }, freshness_score: { type: 'number', minimum: 0, maximum: 1 } } };
const chainFields = { source_provenance: provenance, cache_ttl_seconds: { type: 'integer' }, cache_recommended: { type: 'boolean' }, recommended_next_api: { type: 'string' }, recommended_next_endpoint: { type: 'string' }, automation_safe: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Trend Velocity API', version: '1.0.0', description: 'Measure trend momentum, forecast growth trajectories, detect early signals and identify breakout topics for content and marketing agents', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 300 }, pay_per_call: { measure: '$0.003', forecast: '$0.004', signals: '$0.003', 'execution-gate': '$0.001', 'trend-intelligence': '$0.009', breakout: '$0.004', batch: '$0.020' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/trend-velocity' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/measure': { post: { operationId: 'measureTrend', summary: 'Measure current trend velocity and momentum', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['topic'], properties: { topic: { type: 'string' }, region: { type: 'string' }, timeframe: { type: 'string' } } } } } }, responses: { '200': { description: 'Trend velocity', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, velocity_score: { type: 'number' }, momentum: { type: 'string' }, growth_rate: { type: 'string' }, peak_date: { type: 'string' }, ...chainFields, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } } } } },
      '/forecast': { post: { operationId: 'forecastTrend', summary: 'Forecast trend trajectory 7-30 days out', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['topic'], properties: { topic: { type: 'string' }, horizon_days: { type: 'integer' } } } } } }, responses: { '200': { description: 'Trend forecast', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, forecast_direction: { type: 'string' }, peak_window: { type: 'string' }, confidence_level: { type: 'string' }, ...chainFields, privacy } } } } } } } },
      '/signals': { post: { operationId: 'trendSignals', summary: 'Get early trend signals and leading indicators', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['topic'], properties: { topic: { type: 'string' }, signal_types: { type: 'array', items: { type: 'string' } } } } } } }, responses: { '200': { description: 'Trend signals', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, signals: { type: 'array', items: { type: 'object' } }, signal_strength: { type: 'string' }, actionable_insight: { type: 'string' }, ...chainFields, privacy } } } } } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['topic'], properties: { topic: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, ...chainFields, privacy } } } } } } } },
      '/trend-intelligence': { post: { operationId: 'trendIntelligence', summary: 'ONE-CALL: velocity + forecast + signals + opportunity window', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['topic'], properties: { topic: { type: 'string' }, region: { type: 'string' } } } } } }, responses: { '200': { description: 'Full trend intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, velocity_score: { type: 'number' }, momentum: { type: 'string' }, forecast_direction: { type: 'string' }, opportunity_window: { type: 'string' }, action_recommendation: { type: 'string' }, ...chainFields, confidence_per_section: confidence, privacy } } } } } } } },
      '/breakout': { post: { operationId: 'detectBreakout', summary: 'Detect breakout topics in a category', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['category'], properties: { category: { type: 'string' }, region: { type: 'string' }, min_velocity: { type: 'number' } } } } } }, responses: { '200': { description: 'Breakout topics', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, breakout_topics: { type: 'array', items: { type: 'object' } }, top_breakout: { type: 'string' }, ...chainFields, privacy } } } } } } } },
      '/batch': { post: { operationId: 'batchTrends', summary: 'Batch measure up to 10 topics', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['topics'], properties: { topics: { type: 'array', items: { type: 'string' }, maxItems: 10 } } } } } }, responses: { '200': { description: 'Batch results', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, batch_count: { type: 'integer' }, results: { type: 'array', items: { type: 'object' } }, ...chainFields } } } } } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
