import { Router, Request, Response } from 'express';
const router = Router();

const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string', format: 'date-time' }, success: { type: 'boolean' } };
const provenance = { type: 'object', properties: { provider: { type: 'string' }, retrieved_at: { type: 'string', format: 'date-time' }, freshness_score: { type: 'number', minimum: 0, maximum: 1 } } };
const chainFields = { source_provenance: provenance, cache_ttl_seconds: { type: 'integer' }, cache_recommended: { type: 'boolean' }, recommended_next_api: { type: 'string' }, recommended_next_endpoint: { type: 'string' }, automation_safe: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Receipt Parser API', version: '2.0.0', description: 'Parse receipts, categorize expenses, extract totals, and generate expense reports for finance automation agents', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 500 }, pay_per_call: { parse: '$0.002', categorize: '$0.002', 'extract-totals': '$0.001', 'execution-gate': '$0.001', 'receipt-intelligence': '$0.005', 'expense-report': '$0.008', batch: '$0.015' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/receipt-parser' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/parse': { post: { operationId: 'parseReceipt', summary: 'Parse receipt and extract all fields', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['receipt_text'], properties: { receipt_text: { type: 'string' } } } } } }, responses: { '200': { description: 'Parsed receipt', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, merchant: { type: 'object' }, total: { type: 'number' }, currency: { type: 'string' }, items: { type: 'array', items: { type: 'object' } }, ...chainFields, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } } } } },
      '/categorize': { post: { operationId: 'categorizeExpense', summary: 'Categorize expense and check policy compliance', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { receipt_text: { type: 'string' }, merchant_name: { type: 'string' }, total: { type: 'number' } } } } } }, responses: { '200': { description: 'Expense category', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, category: { type: 'string' }, reimbursable: { type: 'boolean' }, policy_compliant: { type: 'boolean' }, ...chainFields, confidence_per_section: confidence, privacy } } } } } } } },
      '/extract-totals': { post: { operationId: 'extractTotals', summary: 'Extract financial totals and tax breakdown', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['receipt_text'], properties: { receipt_text: { type: 'string' } } } } } }, responses: { '200': { description: 'Totals', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, subtotal: { type: 'number' }, tax_amount: { type: 'number' }, total: { type: 'number' }, math_valid: { type: 'boolean' }, ...chainFields, confidence_per_section: confidence, privacy } } } } } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['receipt_text'], properties: { receipt_text: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, ...chainFields, confidence_per_section: confidence, privacy } } } } } } } },
      '/receipt-intelligence': { post: { operationId: 'receiptIntelligence', summary: 'ONE-CALL: parse + categorize + policy check + approval', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['receipt_text'], properties: { receipt_text: { type: 'string' }, employee_id: { type: 'string' } } } } } }, responses: { '200': { description: 'Full receipt intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, merchant: { type: 'string' }, total: { type: 'number' }, category: { type: 'string' }, approval_recommendation: { type: 'string' }, ...chainFields, confidence_per_section: confidence, privacy } } } } } } } },
      '/expense-report': { post: { operationId: 'generateExpenseReport', summary: 'Generate expense report from multiple receipts', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['receipts'], properties: { receipts: { type: 'array', items: { type: 'object' } }, period: { type: 'string' }, employee: { type: 'string' } } } } } }, responses: { '200': { description: 'Expense report', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, total_expenses: { type: 'number' }, reimbursable_total: { type: 'number' }, by_category: { type: 'array', items: { type: 'object' } }, ...chainFields, confidence_per_section: confidence, privacy } } } } } } } },
      '/batch': { post: { operationId: 'batchReceipts', summary: 'Batch parse up to 10 receipts', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['receipts'], properties: { receipts: { type: 'array', items: { type: 'object' }, maxItems: 10 } } } } } }, responses: { '200': { description: 'Batch results', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, batch_count: { type: 'integer' }, results: { type: 'array', items: { type: 'object' } }, ...chainFields } } } } } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
