import { Router, Request, Response } from 'express';
const router = Router();
const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string' }, success: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Product Data API', version: '1.0.0', description: 'Look up product details, extract structured product data from URLs, and compare products for e-commerce, procurement, and shopping intelligence agents.', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 200, requests_per_month: 6000 }, pay_per_call: { lookup: '$0.003', extract: '$0.004', compare: '$0.006', 'execution-gate': '$0.001', enrich: '$0.008' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/product-data' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/lookup': { post: { operationId: 'lookup', summary: 'Look up product details by name and brand — SKU, UPC, ASIN, specs, pricing', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['product_name'], properties: { product_name: { type: 'string' }, brand: { type: 'string' } } } } } }, responses: { '200': { description: 'Product details', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, product_name: { type: 'string' }, product: { type: 'object', properties: { name: { type: 'string' }, brand: { type: 'string' }, sku: { type: 'string' }, upc: { type: 'string' }, asin: { type: 'string' }, category: { type: 'string' } } }, pricing: { type: 'object' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing product_name' }, '500': { description: 'Failed' } } } },
      '/extract': { post: { operationId: 'extract', summary: 'Extract structured product data from URL — name, price, specs, variants', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['url'], properties: { url: { type: 'string' } } } } } }, responses: { '200': { description: 'Product data extracted', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, url: { type: 'string' }, product: { type: 'object', properties: { name: { type: 'string' }, brand: { type: 'string' }, price: { type: 'object' }, in_stock: { type: 'boolean' }, rating: { type: 'number' }, specifications: { type: 'object' } } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing url' }, '500': { description: 'Failed' } } } },
      '/compare': { post: { operationId: 'compare', summary: 'Compare up to 5 products — winner, comparison matrix, pros/cons', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['product_ids'], properties: { product_ids: { type: 'array', items: { type: 'string' }, maxItems: 5 } } } } } }, responses: { '200': { description: 'Product comparison', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, products: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, name: { type: 'string' }, price: { type: 'number' }, rating: { type: 'number' }, pros: { type: 'array', items: { type: 'string' } }, cons: { type: 'array', items: { type: 'string' } } } } }, winner: { type: 'object' }, comparison_matrix: { type: 'object' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing product_ids' }, '500': { description: 'Failed' } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['product_name'], properties: { product_name: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, next_api: { type: 'string' }, blocking_flags: actions, confidence_per_section: confidence, privacy } } } } } } } },
      '/enrich': { post: { operationId: 'enrich', summary: 'ONE-CALL: full product enrichment — data + specs + ratings + SEO + pricing', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['url'], properties: { url: { type: 'string' } } } } } }, responses: { '200': { description: 'Full product intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, url: { type: 'string' }, product: { type: 'object' }, pricing: { type: 'object' }, specifications: { type: 'object' }, ratings: { type: 'object' }, seo_data: { type: 'object' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing url' }, '500': { description: 'Failed' } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
