import { Router, Request, Response } from 'express';
const router = Router();

const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string', format: 'date-time' }, success: { type: 'boolean' } };
const provenance = { type: 'object', properties: { provider: { type: 'string' }, retrieved_at: { type: 'string', format: 'date-time' }, freshness_score: { type: 'number', minimum: 0, maximum: 1 } } };
const chainFields = { source_provenance: provenance, cache_ttl_seconds: { type: 'integer' }, cache_recommended: { type: 'boolean' }, recommended_next_api: { type: 'string' }, recommended_next_endpoint: { type: 'string' }, automation_safe: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Onchain Labeling API', version: '1.0.0', description: 'Label wallet addresses, classify entity types, verify known entities and bulk label for AML and compliance agent workflows', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 300 }, pay_per_call: { label: '$0.002', classify: '$0.003', verify: '$0.003', 'execution-gate': '$0.001', 'label-intelligence': '$0.008', 'bulk-label': '$0.015', batch: '$0.015' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/onchain-labeling' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/label': { post: { operationId: 'labelAddress', summary: 'Label wallet address with entity name and type', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['address'], properties: { address: { type: 'string' }, chain: { type: 'string' } } } } } }, responses: { '200': { description: 'Address label', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, label: { type: 'string' }, entity_name: { type: 'string' }, entity_type: { type: 'string' }, confidence: { type: 'number' }, ...chainFields, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } } } } },
      '/classify': { post: { operationId: 'classifyEntity', summary: 'Classify entity type and risk category', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['address'], properties: { address: { type: 'string' }, chain: { type: 'string' } } } } } }, responses: { '200': { description: 'Entity classification', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, entity_type: { type: 'string' }, risk_category: { type: 'string' }, compliance_category: { type: 'string' }, ...chainFields, privacy } } } } } } } },
      '/verify': { post: { operationId: 'verifyEntity', summary: 'Verify if address matches a known entity', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['address'], properties: { address: { type: 'string' }, chain: { type: 'string' }, expected_entity: { type: 'string' } } } } } }, responses: { '200': { description: 'Verification result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, is_known_entity: { type: 'boolean' }, entity_name: { type: 'string' }, match_confidence: { type: 'number' }, ...chainFields, privacy } } } } } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['address'], properties: { address: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, ...chainFields, privacy } } } } } } } },
      '/label-intelligence': { post: { operationId: 'labelIntelligence', summary: 'ONE-CALL: label + classify + risk + compliance + action', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['address'], properties: { address: { type: 'string' }, chain: { type: 'string' } } } } } }, responses: { '200': { description: 'Full label intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, label: { type: 'string' }, entity_type: { type: 'string' }, risk_category: { type: 'string' }, is_sanctioned: { type: 'boolean' }, action_recommendation: { type: 'string' }, ...chainFields, confidence_per_section: confidence, privacy } } } } } } } },
      '/bulk-label': { post: { operationId: 'bulkLabel', summary: 'Label up to 20 addresses at once', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['addresses'], properties: { addresses: { type: 'array', items: { type: 'string' }, maxItems: 20 }, chain: { type: 'string' } } } } } }, responses: { '200': { description: 'Bulk labels', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, count: { type: 'integer' }, results: { type: 'array', items: { type: 'object' } }, ...chainFields } } } } } } } },
      '/batch': { post: { operationId: 'batchAddresses', summary: 'Batch classify up to 5 addresses', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['addresses'], properties: { addresses: { type: 'array', items: { type: 'object' }, maxItems: 5 } } } } } }, responses: { '200': { description: 'Batch results', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, batch_count: { type: 'integer' }, results: { type: 'array', items: { type: 'object' } }, ...chainFields } } } } } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
