import { Router, Request, Response } from 'express';
const router = Router();

const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string', format: 'date-time' }, success: { type: 'boolean' } };
const provenance = { type: 'object', properties: { provider: { type: 'string' }, retrieved_at: { type: 'string', format: 'date-time' }, freshness_score: { type: 'number', minimum: 0, maximum: 1 } } };
const chainFields = { source_provenance: provenance, cache_ttl_seconds: { type: 'integer' }, cache_recommended: { type: 'boolean' }, recommended_next_api: { type: 'string' }, recommended_next_endpoint: { type: 'string' }, automation_safe: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Founder Background API', version: '1.0.0', description: 'Look up founder profiles, score credibility, analyze exit track records for investor and partnership diligence agents', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 100 }, pay_per_call: { lookup: '$0.005', score: '$0.005', timeline: '$0.004', 'execution-gate': '$0.001', 'founder-intelligence': '$0.012', 'track-record': '$0.006', batch: '$0.025' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/founder-background' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/lookup': { post: { operationId: 'lookupFounder', summary: 'Look up founder profile', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { name: { type: 'string' }, company: { type: 'string' }, linkedin_url: { type: 'string' } } } } } }, responses: { '200': { description: 'Founder profile', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, name: { type: 'string' }, current_company: { type: 'string' }, education: { type: 'array', items: { type: 'object' } }, ...chainFields, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } } } } },
      '/score': { post: { operationId: 'scoreFounder', summary: 'Score founder credibility and success likelihood', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['name'], properties: { name: { type: 'string' }, company: { type: 'string' }, context: { type: 'string' } } } } } }, responses: { '200': { description: 'Founder score', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, credibility_score: { type: 'number' }, success_likelihood: { type: 'number' }, investor_signal: { type: 'string' }, ...chainFields, privacy } } } } } } } },
      '/timeline': { post: { operationId: 'getFounderTimeline', summary: 'Get career and exit timeline', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['name'], properties: { name: { type: 'string' }, company: { type: 'string' } } } } } }, responses: { '200': { description: 'Career timeline', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, timeline: { type: 'array', items: { type: 'object' } }, total_exits: { type: 'integer' }, ...chainFields, privacy } } } } } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['name'], properties: { name: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, ...chainFields, privacy } } } } } } } },
      '/founder-intelligence': { post: { operationId: 'founderIntelligence', summary: 'ONE-CALL: profile + score + track record + diligence verdict', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['name'], properties: { name: { type: 'string' }, company: { type: 'string' }, context: { type: 'string' } } } } } }, responses: { '200': { description: 'Full founder intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, credibility_score: { type: 'number' }, investor_signal: { type: 'string' }, diligence_verdict: { type: 'string' }, due_diligence_questions: { type: 'array', items: { type: 'string' } }, ...chainFields, confidence_per_section: confidence, privacy } } } } } } } },
      '/track-record': { post: { operationId: 'getTrackRecord', summary: 'Analyze exit and investment track record', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['name'], properties: { name: { type: 'string' }, company: { type: 'string' } } } } } }, responses: { '200': { description: 'Track record', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, ventures: { type: 'array', items: { type: 'object' } }, track_record_score: { type: 'number' }, pattern: { type: 'string' }, ...chainFields, privacy } } } } } } } },
      '/batch': { post: { operationId: 'batchFounders', summary: 'Batch score up to 5 founders', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['founders'], properties: { founders: { type: 'array', items: { type: 'object' }, maxItems: 5 } } } } } }, responses: { '200': { description: 'Batch results', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, batch_count: { type: 'integer' }, results: { type: 'array', items: { type: 'object' } }, ...chainFields } } } } } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
