import { Router, Request, Response } from 'express';
const router = Router();
const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string' }, success: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'QR / Barcode API', version: '1.0.0', description: 'Decode QR codes and barcodes from image URLs, generate QR codes from data, and batch-process multiple codes for logistics, retail, and automation workflows.', 'x-agent-callable': true, 'x-mcp-compatible': true, 'x-pricing': { free_tier: { requests_per_day: 200, requests_per_month: 6000 }, pay_per_call: { decode: '$0.002', generate: '$0.002', batch: '$0.008', 'execution-gate': '$0.001', process: '$0.004' } } },
    servers: [{ url: 'https://orbis-apis.onrender.com/qr-barcode' }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      '/decode': { post: { operationId: 'decode', summary: 'Decode QR code or barcode from image URL — format, data, data type', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['image_url'], properties: { image_url: { type: 'string' } } } } } }, responses: { '200': { description: 'Decoded data', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, image_url: { type: 'string' }, decoded: { type: 'object', properties: { format: { type: 'string' }, data: { type: 'string' }, data_type: { type: 'string' }, error_correction: { type: 'string' } } }, parsed_data: { type: 'object' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing image_url' }, '500': { description: 'Failed' } } } },
      '/generate': { post: { operationId: 'generate', summary: 'Generate QR code from data — returns image URL and embed HTML', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['data'], properties: { data: { type: 'string' }, format: { type: 'string', default: 'qr', enum: ['qr', 'barcode', 'datamatrix'] } } } } } }, responses: { '200': { description: 'Generated code', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, data: { type: 'string' }, format: { type: 'string' }, generated: { type: 'object', properties: { image_url: { type: 'string' }, data_url: { type: 'string' }, format: { type: 'string' }, size: { type: 'string' } } }, embed_html: { type: 'string' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing data' }, '500': { description: 'Failed' } } } },
      '/batch': { post: { operationId: 'batchDecode', summary: 'Batch decode up to 20 QR/barcode image URLs', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['image_urls'], properties: { image_urls: { type: 'array', items: { type: 'string' }, maxItems: 20 } } } } } }, responses: { '200': { description: 'Batch results', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, results: { type: 'array', items: { type: 'object', properties: { image_url: { type: 'string' }, format: { type: 'string' }, data: { type: 'string' }, error: { type: 'string', nullable: true } } } }, summary: { type: 'object', properties: { total: { type: 'number' }, successful: { type: 'number' }, failed: { type: 'number' } } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing image_urls' }, '500': { description: 'Failed' } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['image_url'], properties: { image_url: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, next_api: { type: 'string' }, blocking_flags: actions, confidence_per_section: confidence, privacy } } } } } } } },
      '/process': { post: { operationId: 'process', summary: 'ONE-CALL: full QR/barcode intelligence — decode + parse + next-step recommendation', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['image_url'], properties: { image_url: { type: 'string' } } } } } }, responses: { '200': { description: 'Full QR/barcode intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, image_url: { type: 'string' }, decoded: { type: 'object' }, parsed_data: { type: 'object' }, metadata: { type: 'object' }, recommended_next_step: { type: 'string' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing image_url' }, '500': { description: 'Failed' } } } },
    },
    components: { securitySchemes: { ApiKeyAuth: { type: 'apiKey', in: 'header', name: 'X-API-Key' } } },
  });
});

export default router;
