import { Router, Request, Response } from 'express';
const router = Router();
const privacy = { type: 'object', properties: { data_stored: { type: 'boolean' }, retention: { type: 'string' } } };
const confidence = { type: 'object', additionalProperties: { type: 'number' } };
const actions = { type: 'array', items: { type: 'string' } };
const traceFields = { trace_id: { type: 'string' }, computed_at: { type: 'string' }, success: { type: 'boolean' } };

router.get('/', (_req: Request, res: Response) => {
  res.json({
    openapi: '3.1.0',
    info: { title: 'Job Posting Search API', version: '1.0.0', description: 'Search jobs, get company openings, job details, salary estimates, and full job intelligence for autonomous agents', 'x-agent-callable': true, 'x-mcp-compatible': true },
    servers: [{ url: 'https://orbis-apis.onrender.com/job-posting-search' }],
    paths: {
      '/search-jobs': { post: { operationId: 'searchJobs', summary: 'Search jobs by title/skills/location with fit score', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { title: { type: 'string' }, skills: { type: 'array', items: { type: 'string' } }, location: { type: 'string' }, remote: { type: 'boolean' }, experience_level: { type: 'string', enum: ['entry', 'mid', 'senior', 'lead', 'any'] } } } } } }, responses: { '200': { description: 'Job search results', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, job_summaries: { type: 'array', items: { type: 'object', properties: { title: { type: 'string' }, company: { type: 'string' }, location: { type: 'string' }, salary_range: { type: 'string' }, fit_score: { type: 'number' } } } }, salary_benchmark: { type: 'object' }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing title or skills' }, '500': { description: 'Failed' } } } },
      '/company-jobs': { post: { operationId: 'companyJobs', summary: 'All open roles at a company with department breakdown', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['company'], properties: { company: { type: 'string' } } } } } }, responses: { '200': { description: 'Company jobs', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, company: { type: 'string' }, open_roles: { type: 'array', items: { type: 'object', properties: { title: { type: 'string' }, department: { type: 'string' }, seniority: { type: 'string' } } } }, department_breakdown: { type: 'array', items: { type: 'object', properties: { department: { type: 'string' }, open_count: { type: 'number' }, growth_signal: { type: 'string', enum: ['hiring', 'stable', 'reducing'] } } } }, hiring_velocity: { type: 'string', enum: ['fast', 'normal', 'slow'] }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing company' }, '500': { description: 'Failed' } } } },
      '/job-details': { post: { operationId: 'jobDetails', summary: 'Full job details — requirements, skills, salary signals, culture signals', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { posting_url: { type: 'string' }, title: { type: 'string' }, company: { type: 'string' } } } } } }, responses: { '200': { description: 'Job details', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, job: { type: 'object' }, requirements: { type: 'object' }, skills: { type: 'object' }, salary_signals: { type: 'object' }, culture_signals: { type: 'array', items: { type: 'object' } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing posting_url or title' }, '500': { description: 'Failed' } } } },
      '/salary-estimate': { post: { operationId: 'salaryEstimate', summary: 'Estimate salary range — percentiles, remote premium, equity signals', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['title'], properties: { title: { type: 'string' }, location: { type: 'string' }, experience_years: { type: 'number' }, skills: { type: 'array', items: { type: 'string' } } } } } } }, responses: { '200': { description: 'Salary estimate', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, salary_range: { type: 'object', properties: { p10: { type: 'number' }, p25: { type: 'number' }, p50: { type: 'number' }, p75: { type: 'number' }, p90: { type: 'number' }, currency: { type: 'string' } } }, remote_premium_pct: { type: 'number' }, equity_signals: { type: 'object' }, market_demand: { type: 'string', enum: ['high', 'medium', 'low'] }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing title' }, '500': { description: 'Failed' } } } },
      '/execution-gate': { post: { operationId: 'executionGate', summary: 'Execution readiness check', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['title'], properties: { title: { type: 'string' }, objective: { type: 'string' } } } } } }, responses: { '200': { description: 'Gate result', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, execution_ready: { type: 'boolean' }, next_api: { type: 'string' }, blocking_flags: actions, confidence_per_section: confidence, privacy } } } } } } } },
      '/search': { post: { operationId: 'search', summary: 'ONE-CALL: search + enrich top results + salary estimates', 'x-one-call': true, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { title: { type: 'string' }, skills: { type: 'array', items: { type: 'string' } }, location: { type: 'string' }, experience_years: { type: 'number' } } } } } }, responses: { '200': { description: 'Full job search intelligence', content: { 'application/json': { schema: { type: 'object', properties: { ...traceFields, top_jobs: { type: 'array', items: { type: 'object' } }, salary_benchmark: { type: 'object' }, market_insights: { type: 'object' }, application_strategy: { type: 'array', items: { type: 'object' } }, confidence_per_section: confidence, recommended_actions_priority_order: actions, privacy } } } } }, '400': { description: 'Missing title or skills' }, '500': { description: 'Failed' } } } },
    },
  });
});

export default router;
